// ─────────────────────────────────────────────────────────────────────────
// LIBRERIA ITINERARI — CATALOGO AGGIUNTIVO, SECONDO LOTTO (22/08/2026)
//
// Stessa forma e stesse regole di libraryDescriptorsExtra.ts (solo dati,
// nessun import): un secondo giro di zone mondiali e di luoghi per i 17
// temi editoriali, per portare il catalogo oltre i +5.000 descrittori del
// primo lotto. La fusione in libraryDescriptors.ts gestisce da sola i
// doppioni fra i due lotti (stesso taken-set/nomiEsistenti), quindi qui non
// serve verificare a mano contro EXTRA_WORLD_ZONES/EXTRA_THEME_PLACES: un
// nome ripetuto viene scartato in automatico, non duplicato.
// ─────────────────────────────────────────────────────────────────────────

import type { ExtraZone, ExtraThemePlace } from './libraryDescriptorsExtra';

export const EXTRA_WORLD_ZONES_2: ExtraZone[] = [
  // ── ITALIA ──────────────────────────────────────────────────────────
  { c: 'Cefalù', k: 'Italia', lat: 38.04, lon: 14.02, t: 2, n: 'la cattedrale normanna, il Duomo, il lavatoio medievale, la Rocca' },
  { c: 'Erice', k: 'Italia', lat: 38.04, lon: 12.59, t: 3, n: 'il borgo medievale in cima al monte, i dolci delle monache, la vista su Trapani' },
  { c: 'Noto', k: 'Italia', lat: 36.89, lon: 15.07, t: 2, n: 'il barocco UNESCO ricostruito dopo il terremoto del 1693, l\'Infiorata di maggio' },
  { c: 'Modica', k: 'Italia', lat: 36.86, lon: 14.76, t: 3, n: 'la città in due livelli, il cioccolato a freddo, San Giorgio' },
  { c: 'Ragusa Ibla', k: 'Italia', lat: 36.92, lon: 14.73, t: 3, n: 'il barocco sceso dal Ragusa nuovo, il Duomo, i vicoli del Commissario Montalbano' },
  { c: 'Segesta e Selinunte', k: 'Italia', lat: 37.94, lon: 12.83, t: 3, n: 'il tempio dorico incompiuto fra le colline, le rovine sul mare' },
  { c: 'Ustica', k: 'Italia', lat: 38.71, lon: 13.19, t: 3, n: 'la riserva marina, i murales, l\'isola vulcanica senza folla' },
  { c: 'Vulcano e Lipari', k: 'Italia', lat: 38.46, lon: 14.95, t: 3, n: 'il cratere e i fanghi, il museo archeologico eoliano, i faraglioni' },
  { c: 'Panarea', k: 'Italia', lat: 38.63, lon: 15.07, t: 3, n: 'l\'isola senza auto più mondana delle Eolie, le fumarole' },
  { c: 'Isole Pelagie', k: 'Italia', lat: 35.5, lon: 12.6, t: 3, n: 'Lampedusa e Linosa, il mare più a sud d\'Italia, le tartarughe' },
  { c: 'Costa Viola', k: 'Italia', lat: 38.25, lon: 15.68, t: 3, n: 'Scilla e Bagnara, lo Stretto, il pescespada' },
  { c: 'Le Castella', k: 'Italia', lat: 38.9, lon: 17.02, t: 3, n: 'il castello aragonese sull\'isolotto, la costa ionica calabrese' },
  { c: 'Pizzo Calabro', k: 'Italia', lat: 38.73, lon: 16.16, t: 3, n: 'il tartufo di gelato, il castello Murat, la chiesetta di Piedigrotta' },
  { c: 'Capo Colonna', k: 'Italia', lat: 39.02, lon: 17.2, t: 3, n: 'l\'ultima colonna del tempio di Hera Lacinia, Crotone e la Magna Grecia' },
  { c: 'Praiano', k: 'Italia', lat: 40.63, lon: 14.53, t: 3, n: 'la Costiera senza la folla di Positano, il sentiero degli Dei' },
  { c: 'Vico Equense', k: 'Italia', lat: 40.66, lon: 14.43, t: 3, n: 'la pizza a metro, la penisola sorrentina meno battuta' },
  { c: 'Massa Lubrense', k: 'Italia', lat: 40.6, lon: 14.35, t: 3, n: 'la punta della penisola, Marina del Cantone, le baie nascoste' },
  { c: 'Camaldoli e i Colli', k: 'Italia', lat: 40.86, lon: 14.19, t: 3, n: 'il belvedere sopra Napoli, i boschi, la vista sul golfo' },
  { c: 'Sant\'Agata dei Due Golfi', k: 'Italia', lat: 40.6, lon: 14.36, t: 3, n: 'il crinale fra il golfo di Napoli e quello di Salerno' },
  { c: 'Positano', k: 'Italia', lat: 40.63, lon: 14.48, t: 2, n: 'la scalinata verticale sul mare, Fornillo, la ceramica' },
  { c: 'Furore', k: 'Italia', lat: 40.62, lon: 14.55, t: 3, n: 'il fiordo minuscolo, il borgo dei murales' },
  { c: 'Cava de\' Tirreni', k: 'Italia', lat: 40.7, lon: 14.71, t: 3, n: 'i portici, la Badia benedettina, la costiera senza vista mare' },
  { c: 'Amatrice', k: 'Italia', lat: 42.63, lon: 13.29, t: 3, n: 'la ricostruzione dopo il 2016, la piana, l\'amatriciana nel suo paese' },
  { c: 'Arpino', k: 'Italia', lat: 41.65, lon: 13.61, t: 3, n: 'la patria di Cicerone, le mura poligonali, la Ciociaria' },
  { c: 'Sperlonga e Terracina', k: 'Italia', lat: 41.26, lon: 13.43, t: 3, n: 'il borgo bianco e il tempio di Giove, la via Appia' },
  { c: 'Anagni', k: 'Italia', lat: 41.75, lon: 13.15, t: 3, n: 'la città dei papi, la cattedrale, lo schiaffo di Bonifacio VIII' },
  { c: 'Fara Sabina', k: 'Italia', lat: 42.22, lon: 12.73, t: 3, n: 'l\'abbazia di Farfa, gli uliveti della Sabina' },
  { c: 'Bracciano e Anguillara', k: 'Italia', lat: 42.1, lon: 12.18, t: 3, n: 'il lago vulcanico, il castello Odescalchi, i borghi sull\'acqua' },
  { c: 'Nemi e i Castelli', k: 'Italia', lat: 41.72, lon: 12.72, t: 3, n: 'le fragole, il lago vulcanico, le navi romane del museo' },
  { c: 'Palestrina', k: 'Italia', lat: 41.84, lon: 12.9, t: 3, n: 'il santuario della Fortuna sovrapposto alla città, il mosaico nilotico' },
  { c: 'Fabriano', k: 'Italia', lat: 43.34, lon: 12.91, t: 3, n: 'la città della carta UNESCO, le cartiere storiche' },
  { c: 'Fermo', k: 'Italia', lat: 43.16, lon: 13.72, t: 3, n: 'le cisterne romane, la piazza, la costa a Porto San Giorgio' },
  { c: 'Osimo', k: 'Italia', lat: 43.47, lon: 13.48, t: 3, n: 'le grotte sotterranee, la piazza panoramica' },
  { c: 'Jesi', k: 'Italia', lat: 43.52, lon: 13.24, t: 3, n: 'Federico II, il Verdicchio, il centro murato' },
  { c: 'Camerino', k: 'Italia', lat: 43.14, lon: 13.07, t: 3, n: 'l\'università antica, la ricostruzione dopo il sisma' },
  { c: 'Bevagna', k: 'Italia', lat: 42.93, lon: 12.72, t: 3, n: 'il Mercato delle Gaite, la piazza romanica, le antiche gualchiere' },
  { c: 'Trevi', k: 'Italia', lat: 42.88, lon: 12.75, t: 3, n: 'l\'olio DOP, il borgo a spirale sull\'ulivo' },
  { c: 'Città della Pieve', k: 'Italia', lat: 42.96, lon: 12.0, t: 3, n: 'il Perugino, i mattoni rosa, i tartufi' },
  { c: 'Narni', k: 'Italia', lat: 42.52, lon: 12.52, t: 3, n: 'il centro geografico d\'Italia, Narni sotterranea, il ponte romano' },
  { c: 'Otricoli', k: 'Italia', lat: 42.42, lon: 12.47, t: 3, n: 'gli scavi romani sul Tevere, la valle umbra' },
  { c: 'Ferentino', k: 'Italia', lat: 41.69, lon: 13.25, t: 3, n: 'le mura ciclopiche, l\'acropoli, la Ciociaria antica' },
  { c: 'Sermoneta', k: 'Italia', lat: 41.5, lon: 12.98, t: 3, n: 'il castello Caetani, i giardini di Ninfa a valle' },
  { c: 'San Gimignano dintorni Certaldo', k: 'Italia', lat: 43.55, lon: 11.04, t: 3, n: 'il Boccaccio, il borgo alto, le colline del Chianti' },
  { c: 'Montepulciano dintorni', k: 'Italia', lat: 43.1, lon: 11.78, t: 2, n: 'il Nobile, il Tempio di San Biagio, Chiusi etrusca vicina' },
  { c: 'Massa Marittima', k: 'Italia', lat: 43.05, lon: 10.89, t: 3, n: 'il duomo romanico, le miniere medievali, la Maremma collinare' },
  { c: 'Suvereto e Val di Cornia', k: 'Italia', lat: 43.03, lon: 10.7, t: 3, n: 'i borghi minori della Maremma, i vigneti di Bolgheri accanto' },
  { c: 'Anghiari e Sansepolcro', k: 'Italia', lat: 43.54, lon: 12.05, t: 3, n: 'la battaglia di Leonardo, Piero della Francesca, la Valtiberina' },
  { c: 'Barga', k: 'Italia', lat: 44.08, lon: 10.47, t: 3, n: 'la Scozia in Toscana, Pascoli, la Garfagnana' },
  { c: 'Fivizzano', k: 'Italia', lat: 44.22, lon: 10.14, t: 3, n: 'la Lunigiana, le statue stele, i borghi di confine' },
  { c: 'Fontanellato', k: 'Italia', lat: 44.87, lon: 10.17, t: 3, n: 'la Rocca Sanvitale con il fossato, il Parmigianino' },
  { c: 'Brisighella', k: 'Italia', lat: 44.22, lon: 11.77, t: 3, n: 'le tre colline, la via degli Asini, l\'olio DOP' },
  { c: 'Dozza', k: 'Italia', lat: 44.34, lon: 11.7, t: 3, n: 'il borgo dei muri dipinti, la Biennale del Muro Dipinto' },
  { c: 'Vigoleno', k: 'Italia', lat: 44.79, lon: 9.94, t: 3, n: 'il borgo fortificato dei colli piacentini' },
  { c: 'Sabbioneta', k: 'Italia', lat: 44.99, lon: 10.49, t: 3, n: 'la città ideale dei Gonzaga UNESCO, il teatro all\'antica' },
  { c: 'Rovigo e il Polesine', k: 'Italia', lat: 45.07, lon: 11.79, t: 3, n: 'il Delta del Po, le valli, la Torre Donà' },
  { c: 'Marostica e Bassano', k: 'Italia', lat: 45.74, lon: 11.65, t: 3, n: 'la partita a scacchi viventi, il ponte del Palladio' },
  { c: 'Feltre', k: 'Italia', lat: 46.02, lon: 11.9, t: 3, n: 'il centro rinascimentale ai piedi delle Dolomiti Bellunesi' },
  { c: 'Cividale del Friuli', k: 'Italia', lat: 46.09, lon: 13.43, t: 3, n: 'il ponte del Diavolo, i Longobardi UNESCO' },
  { c: 'Gorizia', k: 'Italia', lat: 45.94, lon: 13.62, t: 3, n: 'la città divisa dal confine, il castello, Nova Gorica gemella' },
  { c: 'San Daniele del Friuli', k: 'Italia', lat: 46.16, lon: 13.0, t: 3, n: 'il prosciutto, il duomo, le colline moreniche' },
  { c: 'Sirmione dintorni Desenzano', k: 'Italia', lat: 45.47, lon: 10.54, t: 3, n: 'il porto vecchio, la villa romana, il Garda occidentale' },
  { c: 'Peschiera del Garda', k: 'Italia', lat: 45.44, lon: 10.69, t: 3, n: 'la fortezza veneziana UNESCO, il lago, Gardaland vicino' },
  { c: 'Malcesine', k: 'Italia', lat: 45.77, lon: 10.8, t: 3, n: 'la funivia sul Monte Baldo, il castello scaligero sul lago' },
  { c: 'Limone sul Garda', k: 'Italia', lat: 45.81, lon: 10.79, t: 3, n: 'i limoneti storici, il sentiero del Ponale, il Garda Trentino' },
  { c: 'Salò', k: 'Italia', lat: 45.6, lon: 10.52, t: 3, n: 'il lungolago, il Vittoriale a Gardone accanto, il duomo' },
  { c: 'Trani e la Costa', k: 'Italia', lat: 41.28, lon: 16.42, t: 3, n: 'la cattedrale sul mare, il porto, le cantine del Moscato' },
  { c: 'Molfetta e Giovinazzo', k: 'Italia', lat: 41.2, lon: 16.6, t: 3, n: 'i porti pugliesi meno battuti, la cattedrale pugliese' },
  { c: 'Monopoli', k: 'Italia', lat: 40.95, lon: 17.3, t: 3, n: 'il centro storico bianco sul mare, i frantoi ipogei' },
  { c: 'Ceglie Messapica', k: 'Italia', lat: 40.65, lon: 17.52, t: 3, n: 'la capitale gastronomica della Valle d\'Itria, i fornelli' },
  { c: 'Manduria e il Primitivo', k: 'Italia', lat: 40.4, lon: 17.63, t: 3, n: 'le vigne ad alberello, la civiltà del vino, le mura messapiche' },
  { c: 'Muro Leccese', k: 'Italia', lat: 40.13, lon: 18.33, t: 3, n: 'il Salento profondo, il barocco leccese in miniatura' },
  { c: 'Nardò', k: 'Italia', lat: 40.18, lon: 18.03, t: 3, n: 'il barocco, Porto Selvaggio, la costa ionica' },
  { c: 'Isole Cheradi', k: 'Italia', lat: 40.38, lon: 17.22, t: 3, n: 'San Pietro e San Paolo davanti a Taranto, i due mari' },
  { c: 'Craco', k: 'Italia', lat: 40.38, lon: 16.43, t: 3, n: 'il paese fantasma sui calanchi, set di molti film' },
  { c: 'Pietrapertosa e Castelmezzano', k: 'Italia', lat: 40.55, lon: 15.9, t: 3, n: 'i borghi sospesi delle Dolomiti Lucane, il volo dell\'angelo' },
  { c: 'Melfi', k: 'Italia', lat: 41.0, lon: 15.65, t: 3, n: 'il castello normanno-svevo, il vulcano del Vulture' },
  { c: 'Venosa', k: 'Italia', lat: 40.96, lon: 15.82, t: 3, n: 'la patria di Orazio, l\'abbazia incompiuta della Trinità' },
  { c: 'Amantea e la Costa Tirrenica', k: 'Italia', lat: 39.13, lon: 16.08, t: 3, n: 'il castello sul mare, la Calabria meno turistica' },
  { c: 'Stilo', k: 'Italia', lat: 38.48, lon: 16.47, t: 3, n: 'la Cattolica bizantina, Tommaso Campanella' },
  { c: 'Isole Ciclopi', k: 'Italia', lat: 37.57, lon: 15.16, t: 3, n: 'i faraglioni di Aci Trezza, la leggenda di Polifemo' },
  { c: 'Zafferana Etnea', k: 'Italia', lat: 37.69, lon: 15.11, t: 3, n: 'il miele dell\'Etna, i sentieri sul vulcano dal versante est' },
  { c: 'Nicolosi', k: 'Italia', lat: 37.62, lon: 15.02, t: 3, n: 'la porta sud dell\'Etna, i crateri Silvestri, la funivia' },
  { c: 'Isole dello Stagnone', k: 'Italia', lat: 37.87, lon: 12.45, t: 3, n: 'Mozia fenicia, i mulini a vento, le saline al tramonto' },
  { c: 'Cala Domestica', k: 'Italia', lat: 39.2, lon: 8.44, t: 3, n: 'la vecchia miniera sul mare, il Sulcis Iglesiente' },
  { c: 'Costa Rei', k: 'Italia', lat: 39.24, lon: 9.55, t: 3, n: 'la spiaggia lunghissima, Villasimius accanto' },
  { c: 'Su Nuraxi di Barumini', k: 'Italia', lat: 39.7, lon: 8.99, t: 3, n: 'il nuraghe UNESCO, il cuore della civiltà nuragica' },
  { c: 'Tempio Pausania', k: 'Italia', lat: 40.9, lon: 9.11, t: 3, n: 'il granito della Gallura, le sorgenti, il sughero' },
  { c: 'Ozieri', k: 'Italia', lat: 40.59, lon: 9.0, t: 3, n: 'il Logudoro, le grotte di San Michele, il centro storico' },

  // ── FRANCIA ─────────────────────────────────────────────────────────
  { c: 'Rocamadour dintorni Padirac', k: 'Francia', lat: 44.83, lon: 1.75, t: 3, n: 'il gouffre de Padirac in barca sottoterra, il santuario a picco' },
  { c: 'Conques', k: 'Francia', lat: 44.6, lon: 2.39, t: 3, n: 'la tappa sulla via di Santiago, il tympanum romanico' },
  { c: 'Cordes-sur-Ciel', k: 'Francia', lat: 44.06, lon: 1.95, t: 3, n: 'il borgo medievale sospeso sulla collina, il Tarn' },
  { c: 'Gorges du Tarn', k: 'Francia', lat: 44.3, lon: 3.3, t: 2, n: 'il canyon in kayak, Sainte-Énimie, il causse Méjean' },
  { c: 'Millau', k: 'Francia', lat: 44.1, lon: 3.08, t: 3, n: 'il viadotto di Foster, il Roquefort, il parapendio' },
  { c: 'Aubrac', k: 'Francia', lat: 44.63, lon: 2.97, t: 3, n: 'l\'altopiano vulcanico, le vacche, la via di Santiago' },
  { c: 'Uzès', k: 'Francia', lat: 44.01, lon: 4.42, t: 3, n: 'il primo ducato di Francia, il Pont du Gard a 15 km' },
  { c: 'Pont du Gard', k: 'Francia', lat: 43.95, lon: 4.53, t: 3, n: 'l\'acquedotto romano UNESCO, il fiume Gardon per nuotare sotto' },
  { c: 'Les Baux-de-Provence', k: 'Francia', lat: 43.74, lon: 4.8, t: 3, n: 'il villaggio sulla rupe, le Carrières de Lumières' },
  { c: 'Saint-Rémy-de-Provence', k: 'Francia', lat: 43.79, lon: 4.83, t: 3, n: 'Van Gogh a Saint-Paul-de-Mausole, Glanum romana' },
  { c: 'Fontaine-de-Vaucluse', k: 'Francia', lat: 43.92, lon: 5.13, t: 3, n: 'la sorgente carsica più potente di Francia, Petrarca' },
  { c: 'Vaison-la-Romaine', k: 'Francia', lat: 44.24, lon: 5.08, t: 3, n: 'gli scavi romani, il ponte antico, i dentelles de Montmirail' },
  { c: 'Bandol e la Costa', k: 'Francia', lat: 43.14, lon: 5.75, t: 3, n: 'il vino rosé, le calanche minori, l\'isola di Bendor' },
  { c: 'Îles d\'Hyères', k: 'Francia', lat: 43.0, lon: 6.2, t: 3, n: 'Porquerolles, Port-Cros e Le Levant, senza auto' },
  { c: 'Grimaud e il Golfo', k: 'Francia', lat: 43.27, lon: 6.52, t: 3, n: 'il borgo sopra Saint-Tropez, Port Grimaud veneziana' },
  { c: 'Sospel e la Val Roya', k: 'Francia', lat: 43.88, lon: 7.46, t: 3, n: 'il confine con l\'Italia, i forti Maginot, Tenda' },
  { c: 'Antibes e Juan-les-Pins', k: 'Francia', lat: 43.58, lon: 7.12, t: 3, n: 'Picasso al castello Grimaldi, il Cap d\'Antibes' },
  { c: 'Sainte-Maxime', k: 'Francia', lat: 43.31, lon: 6.64, t: 3, n: 'il golfo di Saint-Tropez dall\'altra sponda, meno mondano' },
  { c: 'Aigues-Mortes', k: 'Francia', lat: 43.57, lon: 4.19, t: 3, n: 'la città murata delle crociate, le saline rosa vicine' },
  { c: 'Sète', k: 'Francia', lat: 43.4, lon: 3.7, t: 3, n: 'la Venezia del Languedoc, i canali, le giostre nautiche' },
  { c: 'Béziers', k: 'Francia', lat: 43.34, lon: 3.22, t: 3, n: 'il canal du Midi UNESCO, la cattedrale, il rugby' },
  { c: 'Pézenas', k: 'Francia', lat: 43.46, lon: 3.42, t: 3, n: 'la città di Molière, gli antiquari' },
  { c: 'Foix e Ariège', k: 'Francia', lat: 42.97, lon: 1.6, t: 3, n: 'il castello dei conti, le grotte, i Pirenei catari' },
  { c: 'Castelli catari', k: 'Francia', lat: 42.87, lon: 2.36, t: 3, n: 'Peyrepertuse e Quéribus in cima alle rupi' },
  { c: 'Cauterets', k: 'Francia', lat: 42.89, lon: -0.11, t: 3, n: 'le terme pirenaiche, il Cirque de Gavarnie a portata' },
  { c: 'Lourdes', k: 'Francia', lat: 43.1, lon: -0.05, t: 3, n: 'il santuario mariano, il pellegrinaggio, i Pirenei attorno' },
  { c: 'Pau', k: 'Francia', lat: 43.3, lon: -0.37, t: 3, n: 'il castello di Enrico IV, la vista sui Pirenei dal boulevard' },
  { c: 'Saint-Jean-de-Luz', k: 'Francia', lat: 43.39, lon: -1.66, t: 3, n: 'il porto basco, la spiaggia, il matrimonio di Luigi XIV' },
  { c: 'Bidart e la Costa Basca', k: 'Francia', lat: 43.44, lon: -1.59, t: 3, n: 'le falesie, il surf, i villaggi baschi' },
  { c: 'Cognac dintorni', k: 'Francia', lat: 45.7, lon: -0.33, t: 3, n: 'le maison storiche, la Charente, i vigneti' },
  { c: 'La Palmyre e la Côte de Beauté', k: 'Francia', lat: 45.68, lon: -1.13, t: 3, n: 'lo zoo sul mare, le spiagge atlantiche, Royan Art Déco' },
  { c: 'Île de Ré', k: 'Francia', lat: 46.19, lon: -1.4, t: 2, n: 'le case bianche con le persiane verdi, la bici ovunque, le ostriche' },
  { c: 'Île d\'Oléron', k: 'Francia', lat: 45.9, lon: -1.25, t: 3, n: 'la più grande isola atlantica dopo la Corsica, le ostriche di Marennes' },
  { c: 'Cap Ferret', k: 'Francia', lat: 44.62, lon: -1.25, t: 3, n: 'le cabanes tchanquées, le ostriche, il faro' },
  { c: 'Périgueux', k: 'Francia', lat: 45.18, lon: 0.72, t: 3, n: 'le cupole bizantine di Saint-Front, la città gallo-romana' },
  { c: 'Lascaux e Les Eyzies', k: 'Francia', lat: 44.94, lon: 1.0, t: 3, n: 'l\'arte rupestre, la capitale della preistoria' },
  { c: 'Rocamadour', k: 'Francia', lat: 44.8, lon: 1.62, t: 3, n: 'già citata: il santuario, la scala dei pellegrini' },
  { c: 'Bourges', k: 'Francia', lat: 47.08, lon: 2.4, t: 3, n: 'la cattedrale gotica UNESCO, il palazzo Jacques Cœur' },
  { c: 'Chinon', k: 'Francia', lat: 47.17, lon: 0.24, t: 3, n: 'la fortezza di Giovanna d\'Arco, la Vienne, il vino rosso' },
  { c: 'Loches', k: 'Francia', lat: 47.13, lon: 0.99, t: 3, n: 'il castello reale, la torre di Agnès Sorel' },
  { c: 'Blois', k: 'Francia', lat: 47.59, lon: 1.33, t: 3, n: 'il castello reale con la scala, la città vecchia sulla Loira' },
  { c: 'Angers', k: 'Francia', lat: 47.47, lon: -0.55, t: 3, n: 'l\'Apocalisse tessuta, il castello nero, i vigneti dell\'Anjou' },
  { c: 'Le Mans', k: 'Francia', lat: 48.01, lon: 0.2, t: 3, n: 'la 24 Ore, la città vecchia romana, il museo delle 24 Ore' },
  { c: 'Domrémy e la Lorena', k: 'Francia', lat: 48.44, lon: 5.68, t: 3, n: 'il villaggio natale di Giovanna d\'Arco' },
  { c: 'Épinal', k: 'Francia', lat: 48.17, lon: 6.45, t: 3, n: 'le stampe popolari, i Vosgi, il museo dell\'immagine' },
  { c: 'Baie de Somme dintorni', k: 'Francia', lat: 50.2, lon: 1.6, t: 3, n: 'Saint-Valery e le foche, il trenino a vapore' },
  { c: 'Boulogne-sur-Mer', k: 'Francia', lat: 50.73, lon: 1.61, t: 3, n: 'il più grande acquario di Francia, la città alta murata' },
  { c: 'Calais', k: 'Francia', lat: 50.95, lon: 1.85, t: 3, n: 'i Borghesi di Rodin, le scogliere bianche a due passi dall\'Inghilterra' },
  { c: 'Compiègne', k: 'Francia', lat: 49.42, lon: 2.83, t: 3, n: 'il vagone dell\'armistizio, la foresta, il castello imperiale' },
  { c: 'Senlis', k: 'Francia', lat: 49.21, lon: 2.59, t: 3, n: 'la città medievale intatta vicino a Chantilly' },
  { c: 'Chantilly', k: 'Francia', lat: 49.19, lon: 2.47, t: 3, n: 'il castello dei Condé, le scuderie, la panna che porta il nome' },

  // ── SPAGNA ──────────────────────────────────────────────────────────
  { c: 'Frigiliana', k: 'Spagna', lat: 36.79, lon: -3.88, t: 3, n: 'il pueblo blanco più votato dell\'Andalusia, sopra Nerja' },
  { c: 'Zahara de la Sierra', k: 'Spagna', lat: 36.84, lon: -5.39, t: 3, n: 'il pueblo blanco sul bacino turchese, la ruta de los Pueblos Blancos' },
  { c: 'Grazalema', k: 'Spagna', lat: 36.76, lon: -5.37, t: 3, n: 'il paese più piovoso di Spagna, il parco naturale' },
  { c: 'Setenil de las Bodegas', k: 'Spagna', lat: 36.87, lon: -5.18, t: 3, n: 'le case scavate sotto la roccia, unico in Spagna' },
  { c: 'Vejer de la Frontera', k: 'Spagna', lat: 36.25, lon: -5.97, t: 3, n: 'il pueblo blanco sulla Costa de la Luz, El Palmar sotto' },
  { c: 'Arcos de la Frontera', k: 'Spagna', lat: 36.75, lon: -5.81, t: 3, n: 'il balcone sul Guadalete, la Ruta dei Pueblos Blancos' },
  { c: 'Baeza dintorni', k: 'Spagna', lat: 38.01, lon: -3.47, t: 3, n: 'il Rinascimento andaluso UNESCO, gli olivi a perdita d\'occhio' },
  { c: 'Alcalá la Real', k: 'Spagna', lat: 37.46, lon: -3.92, t: 3, n: 'la fortezza della Mota, il confine col regno nazarí' },
  { c: 'Antequera', k: 'Spagna', lat: 37.02, lon: -4.56, t: 3, n: 'i dolmen UNESCO, El Torcal e le rocce carsiche, la Peña de los Enamorados' },
  { c: 'Nerja dintorni Maro', k: 'Spagna', lat: 36.76, lon: -3.85, t: 3, n: 'le grotte, la cascata, la Costa Tropical' },
  { c: 'La Alpujarra', k: 'Spagna', lat: 36.95, lon: -3.35, t: 3, n: 'i villaggi berberi sotto la Sierra Nevada, Trevélez e il jamón' },
  { c: 'Almuñécar', k: 'Spagna', lat: 36.73, lon: -3.69, t: 3, n: 'il castello di San Miguel, i canneti tropicali, il faro' },
  { c: 'Aracena', k: 'Spagna', lat: 37.89, lon: -6.56, t: 3, n: 'la Gruta de las Maravillas, il jamón ibérico di ghianda' },
  { c: 'Carmona', k: 'Spagna', lat: 37.47, lon: -5.64, t: 3, n: 'la necropoli romana, l\'alcázar, la campagna sivigliana' },
  { c: 'Écija', k: 'Spagna', lat: 37.54, lon: -5.08, t: 3, n: 'la città delle undici torri, la Baja Andalucía calda' },
  { c: 'Osuna', k: 'Spagna', lat: 37.23, lon: -5.1, t: 3, n: 'l\'università barocca, set del Trono di Spade' },
  { c: 'Alájar e la Sierra de Aracena', k: 'Spagna', lat: 37.87, lon: -6.66, t: 3, n: 'la Peña de Arias Montano, il jamón, i villaggi' },
  { c: 'Estepona', k: 'Spagna', lat: 36.43, lon: -5.15, t: 3, n: 'i murales floreali, la Costa del Sol meno costruita' },
  { c: 'Mijas', k: 'Spagna', lat: 36.6, lon: -4.64, t: 3, n: 'il pueblo bianco sopra Fuengirola, i taxi-asino' },
  { c: 'Nerja e la Costa Tropical', k: 'Spagna', lat: 36.75, lon: -3.87, t: 3, n: 'il balcone d\'Europa, le grotte, la costa selvaggia' },
  { c: 'Almagro', k: 'Spagna', lat: 38.89, lon: -3.7, t: 3, n: 'la plaza mayor con i balconi verdi, il teatro barocco' },
  { c: 'Consuegra', k: 'Spagna', lat: 39.46, lon: -3.6, t: 3, n: 'i mulini a vento di Don Chisciotte, il castello' },
  { c: 'Alcalá de Henares', k: 'Spagna', lat: 40.48, lon: -3.36, t: 3, n: 'la città natale di Cervantes, l\'università UNESCO' },
  { c: 'Chinchón', k: 'Spagna', lat: 40.14, lon: -3.42, t: 3, n: 'la plaza mayor circolare con i balconi, l\'anice' },
  { c: 'Aranjuez', k: 'Spagna', lat: 40.03, lon: -3.6, t: 3, n: 'i giardini reali UNESCO, le fresas con nata' },
  { c: 'Sigüenza', k: 'Spagna', lat: 41.07, lon: -2.64, t: 3, n: 'la cattedrale fortezza, il Doncel, la Castiglia dorata' },
  { c: 'Medinaceli', k: 'Spagna', lat: 41.17, lon: -2.43, t: 3, n: 'l\'arco romano, il borgo sospeso sull\'altopiano' },
  { c: 'Ávila dintorni', k: 'Spagna', lat: 40.66, lon: -4.7, t: 3, n: 'i tori di pietra, il misticismo teresiano' },
  { c: 'Peñíscola dintorni', k: 'Spagna', lat: 40.36, lon: 0.41, t: 3, n: 'il castello sul mare, il set del Trono di Spade' },
  { c: 'Morella', k: 'Spagna', lat: 40.62, lon: -0.1, t: 3, n: 'la città murata su un pinnacolo, il tartufo nero' },
  { c: 'Chulilla', k: 'Spagna', lat: 39.68, lon: -0.89, t: 3, n: 'il canyon del Turia, i ponti sospesi' },
  { c: 'Guadalest', k: 'Spagna', lat: 38.68, lon: -0.19, t: 3, n: 'il castello sulla roccia, il lago turchese' },
  { c: 'Xàtiva', k: 'Spagna', lat: 38.99, lon: -0.52, t: 3, n: 'il castello dei Borgia, la città natale dei papi valenciani' },
  { c: 'Ronda dintorni', k: 'Spagna', lat: 36.74, lon: -5.16, t: 2, n: 'il Tajo, il ponte nuovo, la corrida più antica di Spagna' },
  { c: 'Comillas', k: 'Spagna', lat: 43.38, lon: -4.29, t: 3, n: 'il capriccio di Gaudí, la costa cantabrica' },
  { c: 'Santillana del Mar', k: 'Spagna', lat: 43.39, lon: -4.11, t: 3, n: 'il borgo medievale intatto, Altamira vicina' },
  { c: 'Cangas de Onís', k: 'Spagna', lat: 43.35, lon: -5.13, t: 3, n: 'il ponte romano, la porta dei Picos de Europa' },
  { c: 'Fuenterrabía', k: 'Spagna', lat: 43.36, lon: -1.79, t: 3, n: 'la città a colori sul confine francese, il porto peschereccio' },
  { c: 'Getaria', k: 'Spagna', lat: 43.3, lon: -2.2, t: 3, n: 'il paese di Balenciaga, il chuletón, il txakoli' },
  { c: 'Laguardia', k: 'Spagna', lat: 42.55, lon: -2.59, t: 3, n: 'il borgo murato della Rioja Alavesa, le cantine sotterranee' },
  { c: 'Olite', k: 'Spagna', lat: 42.48, lon: -1.65, t: 3, n: 'il castello gotico dei re di Navarra' },
  { c: 'Estella e il Cammino', k: 'Spagna', lat: 42.67, lon: -2.03, t: 3, n: 'la tappa navarra del Cammino di Santiago, il romanico' },
  { c: 'Zumaia', k: 'Spagna', lat: 43.3, lon: -2.26, t: 3, n: 'il flysch geologico, set del Trono di Spade sulla scogliera' },
  { c: 'Roncisvalle', k: 'Spagna', lat: 43.01, lon: -1.32, t: 3, n: 'il valico dei Pirenei, l\'inizio spagnolo del Cammino francese' },

  // ── PORTOGALLO ──────────────────────────────────────────────────────
  { c: 'Monsaraz', k: 'Portogallo', lat: 38.44, lon: -7.38, t: 3, n: 'il borgo murato sull\'Alqueva, il cielo più buio d\'Europa' },
  { c: 'Marvão', k: 'Portogallo', lat: 39.4, lon: -7.38, t: 3, n: 'il paese sulla rupe al confine spagnolo' },
  { c: 'Elvas', k: 'Portogallo', lat: 38.88, lon: -7.16, t: 3, n: 'le fortificazioni UNESCO, l\'acquedotto, il confine' },
  { c: 'Estremoz', k: 'Portogallo', lat: 38.84, lon: -7.59, t: 3, n: 'il marmo dell\'Alentejo, il castello bianco' },
  { c: 'Portalegre', k: 'Portogallo', lat: 39.29, lon: -7.43, t: 3, n: 'gli arazzi, la Serra de São Mamede' },
  { c: 'Beja', k: 'Portogallo', lat: 38.02, lon: -7.86, t: 3, n: 'il castello, la pianura infinita dell\'Alentejo profondo' },
  { c: 'Mértola', k: 'Portogallo', lat: 37.64, lon: -7.66, t: 3, n: 'il paese museo sul fiume Guadiana, l\'eredità islamica' },
  { c: 'Setúbal', k: 'Portogallo', lat: 38.53, lon: -8.89, t: 3, n: 'i delfini del Sado, il parco dell\'Arrábida, il vino Moscatel' },
  { c: 'Ericeira', k: 'Portogallo', lat: 38.96, lon: -9.42, t: 3, n: 'la riserva mondiale del surf, il centro bianco e blu' },
  { c: 'Óbidos dintorni', k: 'Portogallo', lat: 39.36, lon: -9.16, t: 3, n: 'la ginjinha, il lago di Óbidos, il festival del cioccolato' },
  { c: 'Peniche', k: 'Portogallo', lat: 39.36, lon: -9.38, t: 3, n: 'le onde di Supertubos, l\'isola di Berlenga' },
  { c: 'Tomar', k: 'Portogallo', lat: 39.6, lon: -8.42, t: 3, n: 'il convento di Cristo UNESCO, i Templari' },
  { c: 'Fátima', k: 'Portogallo', lat: 39.63, lon: -8.67, t: 3, n: 'il santuario mariano, il pellegrinaggio di maggio e ottobre' },
  { c: 'Batalha', k: 'Portogallo', lat: 39.66, lon: -8.83, t: 3, n: 'il monastero gotico UNESCO, la vittoria di Aljubarrota' },
  { c: 'Alcobaça', k: 'Portogallo', lat: 39.55, lon: -8.98, t: 3, n: 'il monastero cistercense, la tomba di Pedro e Inês' },
  { c: 'Viana do Castelo', k: 'Portogallo', lat: 41.69, lon: -8.83, t: 3, n: 'il santuario sul monte, il centro rinascimentale, l\'Atlantico' },
  { c: 'Ponte de Lima', k: 'Portogallo', lat: 41.77, lon: -8.58, t: 3, n: 'il ponte romano, il vinho verde, il borgo più antico del Portogallo' },
  { c: 'Amarante', k: 'Portogallo', lat: 41.27, lon: -8.08, t: 3, n: 'il ponte sul Tâmega, il convento, i dolci di São Gonçalo' },
  { c: 'Lamego', k: 'Portogallo', lat: 41.1, lon: -7.81, t: 3, n: 'la scalinata barocca del santuario, il Douro, lo spumante' },
  { c: 'Bragança', k: 'Portogallo', lat: 41.81, lon: -6.76, t: 3, n: 'la cittadella medievale, il Parco di Montesinho' },
  { c: 'Portimão e Praia da Rocha', k: 'Portogallo', lat: 37.14, lon: -8.54, t: 3, n: 'le grotte di Benagil, la spiaggia rossa, le sardine' },
  { c: 'Sagres', k: 'Portogallo', lat: 37.01, lon: -8.94, t: 3, n: 'la fine del mondo di Enrico il Navigatore, il surf' },
  { c: 'Silves', k: 'Portogallo', lat: 37.19, lon: -8.44, t: 3, n: 'il castello arabo in mattoni rossi, la cattedrale gotica' },
  { c: 'Tavira', k: 'Portogallo', lat: 37.13, lon: -7.65, t: 3, n: 'i sette ponti, le isole della Ria Formosa' },
  { c: 'Faro', k: 'Portogallo', lat: 37.02, lon: -7.93, t: 3, n: 'la Ria Formosa, la cappella delle ossa, il centro storico' },

  // ── REGNO UNITO E IRLANDA ───────────────────────────────────────────
  { c: 'Whitby', k: 'Regno Unito', lat: 54.49, lon: -0.61, t: 3, n: 'l\'abbazia di Dracula, il porto dei pescatori, il jet nero' },
  { c: 'Scarborough', k: 'Regno Unito', lat: 54.28, lon: -0.4, t: 3, n: 'la prima località balneare d\'Inghilterra, il castello' },
  { c: 'Ludlow', k: 'Regno Unito', lat: 52.37, lon: -2.72, t: 3, n: 'la capitale gastronomica delle Marche gallesi, il castello' },
  { c: 'Chester', k: 'Regno Unito', lat: 53.19, lon: -2.89, t: 3, n: 'le Rows medievali, le mura romane complete' },
  { c: 'Warwick', k: 'Regno Unito', lat: 52.28, lon: -1.59, t: 3, n: 'il castello con le giostre, il fiume Avon' },
  { c: 'Rye', k: 'Regno Unito', lat: 50.95, lon: 0.73, t: 3, n: 'il paese medievale del Sussex, i vicoli acciottolati' },
  { c: 'Whitstable', k: 'Regno Unito', lat: 51.36, lon: 1.03, t: 3, n: 'le ostriche, le casette da pescatori, il molo' },
  { c: 'St Andrews', k: 'Regno Unito', lat: 56.34, lon: -2.8, t: 3, n: 'la culla del golf, l\'università, le rovine della cattedrale' },
  { c: 'Loch Lomond', k: 'Regno Unito', lat: 56.1, lon: -4.63, t: 3, n: 'il lago più grande della Scozia, il Trossachs National Park' },
  { c: 'Fort William', k: 'Regno Unito', lat: 56.82, lon: -5.11, t: 3, n: 'il Ben Nevis, il Jacobite Steam Train di Harry Potter' },
  { c: 'Isola di Arran', k: 'Regno Unito', lat: 55.58, lon: -5.25, t: 3, n: 'la Scozia in miniatura, il whisky, i sentieri' },
  { c: 'Isole Orcadi', k: 'Regno Unito', lat: 58.98, lon: -2.96, t: 3, n: 'Skara Brae neolitica, le scogliere, i venti' },
  { c: 'Isole Shetland', k: 'Regno Unito', lat: 60.15, lon: -1.15, t: 3, n: 'i pony, i puffin, più vicine alla Norvegia che a Londra' },
  { c: 'Snowdon dintorni', k: 'Regno Unito', lat: 53.07, lon: -4.08, t: 3, n: 'la vetta gallese, il trenino, Betws-y-Coed' },
  { c: 'St Davids', k: 'Regno Unito', lat: 51.88, lon: -5.27, t: 3, n: 'la città più piccola del Regno Unito, la cattedrale, la costa' },
  { c: 'Peak District', k: 'Regno Unito', lat: 53.28, lon: -1.73, t: 3, n: 'Chatsworth House, Bakewell e le sue tart, i sentieri' },
  { c: 'New Forest', k: 'Regno Unito', lat: 50.86, lon: -1.58, t: 3, n: 'i pony selvatici, le brughiere, la costa vicina' },
  { c: 'Isola di Wight', k: 'Regno Unito', lat: 50.69, lon: -1.32, t: 3, n: 'Osborne House della regina Vittoria, i Needles' },
  { c: 'Galway dintorni Connemara', k: 'Irlanda', lat: 53.27, lon: -9.05, t: 3, n: 'la porta del selvaggio ovest, la musica nei pub' },
  { c: 'Waterford', k: 'Irlanda', lat: 52.26, lon: -7.11, t: 3, n: 'il cristallo, la città vichinga più antica d\'Irlanda' },
  { c: 'Wicklow', k: 'Irlanda', lat: 52.98, lon: -6.05, t: 3, n: 'Glendalough monastico, i giardini, un\'ora da Dublino' },
  { c: 'Westport', k: 'Irlanda', lat: 53.8, lon: -9.52, t: 3, n: 'il Croagh Patrick, la baia di Clew, la Wild Atlantic Way' },
  { c: 'Achill Island', k: 'Irlanda', lat: 53.97, lon: -10.05, t: 3, n: 'la più grande isola d\'Irlanda, le spiagge deserte' },

  // ── GERMANIA, AUSTRIA, SVIZZERA ─────────────────────────────────────
  { c: 'Rothenburg ob der Tauber', k: 'Germania', lat: 49.38, lon: 10.18, t: 2, n: 'la città medievale sulla Romantische Strasse, le mura percorribili' },
  { c: 'Dinkelsbühl', k: 'Germania', lat: 49.07, lon: 10.32, t: 3, n: 'la città a graticcio intatta, la Romantische Strasse' },
  { c: 'Wurzburg', k: 'Germania', lat: 49.79, lon: 9.93, t: 3, n: 'la Residenz UNESCO, il vino della Franconia' },
  { c: 'Marburgo', k: 'Germania', lat: 50.81, lon: 8.77, t: 3, n: 'il castello sopra la città universitaria, i fratelli Grimm' },
  { c: 'Celle', k: 'Germania', lat: 52.62, lon: 10.08, t: 3, n: 'la più grande città a graticcio della Germania, il castello ducale' },
  { c: 'Wernigerode', k: 'Germania', lat: 51.84, lon: 10.78, t: 3, n: 'la porta dell\'Harz, il trenino a vapore per il Brocken' },
  { c: 'Quedlinburg', k: 'Germania', lat: 51.79, lon: 11.15, t: 3, n: 'la città a graticcio UNESCO, 1.300 case storiche' },
  { c: 'Görlitz', k: 'Germania', lat: 51.15, lon: 14.99, t: 3, n: 'la città più intatta di Germania, set di Grand Budapest Hotel' },
  { c: 'Passau', k: 'Germania', lat: 48.57, lon: 13.43, t: 3, n: 'la confluenza di tre fiumi, l\'organo più grande del mondo' },
  { c: 'Freiburg dintorni Kaiserstuhl', k: 'Germania', lat: 48.0, lon: 7.85, t: 3, n: 'i vigneti vulcanici, il vino più caldo di Germania' },
  { c: 'Heidelberg dintorni', k: 'Germania', lat: 49.41, lon: 8.71, t: 2, n: 'il castello in rovina romantica, il ponte vecchio, l\'università' },
  { c: 'Schwerin', k: 'Germania', lat: 53.63, lon: 11.42, t: 3, n: 'il castello sul lago, la Svizzera del nord' },
  { c: 'Meersburg', k: 'Germania', lat: 47.69, lon: 9.27, t: 3, n: 'il castello più antico abitato di Germania, il lago di Costanza' },
  { c: 'Konstanz', k: 'Germania', lat: 47.66, lon: 9.18, t: 3, n: 'il lago di Costanza, il Concilio, la Svizzera al di là del confine' },
  { c: 'Freudenstadt', k: 'Germania', lat: 48.46, lon: 8.41, t: 3, n: 'la porta sud della Foresta Nera, la piazza più grande di Germania' },
  { c: 'Melk', k: 'Austria', lat: 48.23, lon: 15.34, t: 3, n: 'l\'abbazia barocca sopra il Danubio, la Wachau' },
  { c: 'Dürnstein', k: 'Austria', lat: 48.4, lon: 15.53, t: 3, n: 'il borgo sul Danubio, la prigione di Riccardo Cuor di Leone' },
  { c: 'Steyr', k: 'Austria', lat: 48.04, lon: 14.42, t: 3, n: 'la città a graticcio dell\'Alta Austria, la confluenza dei fiumi' },
  { c: 'Villaco', k: 'Austria', lat: 46.61, lon: 13.85, t: 3, n: 'il triangolo delle frontiere, il Wörthersee vicino' },
  { c: 'Reutte', k: 'Austria', lat: 47.48, lon: 10.72, t: 3, n: 'i ponti sospesi Highline 179, i castelli di Ehrenberg' },
  { c: 'Alpbach', k: 'Austria', lat: 47.4, lon: 11.9, t: 3, n: 'il villaggio più bello d\'Austria, i tetti in legno' },
  { c: 'Sciaffusa', k: 'Svizzera', lat: 47.7, lon: 8.63, t: 3, n: 'le cascate del Reno, la più grande d\'Europa' },
  { c: 'Stein am Rhein', k: 'Svizzera', lat: 47.66, lon: 8.86, t: 3, n: 'le facciate affrescate medievali sul Reno' },
  { c: 'Gruyères dintorni', k: 'Svizzera', lat: 46.58, lon: 7.08, t: 3, n: 'il castello, il formaggio, il cioccolato Cailler' },
  { c: 'Sion', k: 'Svizzera', lat: 46.23, lon: 7.36, t: 3, n: 'i due castelli sulle colline, il Vallese vinicolo' },
  { c: 'Appenzell', k: 'Svizzera', lat: 47.33, lon: 9.41, t: 3, n: 'le facciate dipinte, il formaggio, l\'Alpstein' },
  { c: 'Rapperswil', k: 'Svizzera', lat: 47.23, lon: 8.82, t: 3, n: 'la città delle rose sul lago di Zurigo, il castello' },
  { c: 'Neuchâtel', k: 'Svizzera', lat: 46.99, lon: 6.93, t: 3, n: 'la città color biscotto, il lago, l\'orologeria' },

  // ── PAESI BASSI, BELGIO, SCANDINAVIA, EST EUROPA ────────────────────
  { c: 'Volendam e Marken', k: 'Paesi Bassi', lat: 52.5, lon: 5.07, t: 3, n: 'i costumi tradizionali, le case di legno sull\'ex Zuiderzee' },
  { c: 'Zaanse Schans', k: 'Paesi Bassi', lat: 52.47, lon: 4.82, t: 3, n: 'i mulini a vento funzionanti, gli zoccoli, il formaggio' },
  { c: 's-Hertogenbosch', k: 'Paesi Bassi', lat: 51.69, lon: 5.3, t: 3, n: 'Jheronimus Bosch, i canali sotterranei, la cattedrale' },
  { c: 'Middelburg', k: 'Paesi Bassi', lat: 51.5, lon: 3.61, t: 3, n: 'la Zelanda, l\'abbazia, il mare che ha inghiottito i polder' },
  { c: 'Gand dintorni', k: 'Belgio', lat: 51.05, lon: 3.72, t: 2, n: 'l\'Agnello Mistico, i canali senza la folla di Bruges' },
  { c: 'Namur', k: 'Belgio', lat: 50.47, lon: 4.87, t: 3, n: 'la cittadella sulla Mosa, la porta delle Ardenne' },
  { c: 'Spa', k: 'Belgio', lat: 50.49, lon: 5.86, t: 3, n: 'la città che ha dato il nome alle terme, il circuito di Francorchamps' },
  { c: 'Roskilde', k: 'Danimarca', lat: 55.64, lon: 12.08, t: 3, n: 'le navi vichinghe, la cattedrale dei re, il festival' },
  { c: 'Skagen', k: 'Danimarca', lat: 57.72, lon: 10.58, t: 3, n: 'dove due mari si scontrano, i pittori del nord, le case gialle' },
  { c: 'Ribe', k: 'Danimarca', lat: 55.33, lon: 8.77, t: 3, n: 'la più antica città di Danimarca, il giro notturno del guardiano' },
  { c: 'Kristiansand', k: 'Norvegia', lat: 58.15, lon: 8.0, t: 3, n: 'la costa sud norvegese, lo zoo, le isolette' },
  { c: 'Geiranger', k: 'Norvegia', lat: 62.1, lon: 7.21, t: 2, n: 'il fiordo UNESCO, le Sette Sorelle, la strada delle aquile' },
  { c: 'Preikestolen e Lysefjord', k: 'Norvegia', lat: 58.99, lon: 6.19, t: 2, n: 'il Pulpito sospeso sul fiordo, Kjerag' },
  { c: 'Åland', k: 'Finlandia', lat: 60.1, lon: 19.94, t: 3, n: 'le isole autonome fra Finlandia e Svezia, il traghetto' },
  { c: 'Lappeenranta e Saimaa', k: 'Finlandia', lat: 61.06, lon: 28.19, t: 3, n: 'il più grande lago finlandese, le foche saimaa' },
  { c: 'Visby dintorni', k: 'Svezia', lat: 57.64, lon: 18.29, t: 3, n: 'la settimana medievale, le mura, i raukar di Fårö' },
  { c: 'Kalmar', k: 'Svezia', lat: 56.66, lon: 16.36, t: 3, n: 'il castello, l\'unione di Kalmar, l\'isola di Öland' },
  { c: 'Sigulda', k: 'Lettonia', lat: 57.15, lon: 24.85, t: 3, n: 'la Svizzera lettone, i castelli, la valle della Gauja' },
  { c: 'Trakai', k: 'Lituania', lat: 54.65, lon: 24.93, t: 3, n: 'il castello sul lago, la capitale antica dei lituani' },
  { c: 'Palanga', k: 'Lituania', lat: 55.92, lon: 21.07, t: 3, n: 'la costa baltica, il museo dell\'ambra, il molo' },
  { c: 'Zamość', k: 'Polonia', lat: 50.72, lon: 23.25, t: 3, n: 'la città ideale rinascimentale UNESCO' },
  { c: 'Malbork', k: 'Polonia', lat: 54.04, lon: 19.03, t: 3, n: 'il più grande castello gotico in mattoni del mondo, UNESCO' },
  { c: 'Sopot', k: 'Polonia', lat: 54.44, lon: 18.56, t: 3, n: 'il molo di legno più lungo d\'Europa, la Riviera Baltica' },
  { c: 'Wieliczka', k: 'Polonia', lat: 49.98, lon: 20.06, t: 3, n: 'la miniera di sale UNESCO con la cattedrale scavata' },
  { c: 'Telč', k: 'Cechia', lat: 49.19, lon: 15.45, t: 3, n: 'la piazza rinascimentale UNESCO, il lago attorno' },
  { c: 'Olomouc', k: 'Cechia', lat: 49.6, lon: 17.25, t: 3, n: 'la colonna della Trinità UNESCO, la Moravia meno turistica' },
  { c: 'Mikulov', k: 'Cechia', lat: 48.81, lon: 16.64, t: 3, n: 'i vigneti della Moravia, il castello, il confine austriaco' },
  { c: 'Bardejov', k: 'Slovacchia', lat: 49.29, lon: 21.28, t: 3, n: 'la piazza gotica UNESCO, le terme vicine' },
  { c: 'Alti Tatra Štrbské Pleso', k: 'Slovacchia', lat: 49.12, lon: 20.06, t: 3, n: 'il lago glaciale, la porta dei Tatra' },
  { c: 'Sopron', k: 'Ungheria', lat: 47.68, lon: 16.58, t: 3, n: 'la città fedele, il confine austriaco, il vino Kékfrankos' },
  { c: 'Szentendre', k: 'Ungheria', lat: 47.67, lon: 19.08, t: 3, n: 'il villaggio degli artisti sul Danubio, a 20 minuti da Budapest' },
  { c: 'Sibiu', k: 'Romania', lat: 45.79, lon: 24.15, t: 3, n: 'le case con gli occhi sui tetti, capitale culturale 2007' },
  { c: 'Brașov', k: 'Romania', lat: 45.65, lon: 25.61, t: 3, n: 'la città sassone ai piedi dei Carpazi, Bran (il castello di Dracula) vicino' },
  { c: 'Alba Iulia', k: 'Romania', lat: 46.07, lon: 23.58, t: 3, n: 'la cittadella a stella, l\'unione della Romania' },
  { c: 'Nesebar', k: 'Bulgaria', lat: 42.66, lon: 27.73, t: 3, n: 'la penisola bizantina UNESCO sul Mar Nero, le chiese' },
  { c: 'Koprivshtitsa', k: 'Bulgaria', lat: 42.65, lon: 24.35, t: 3, n: 'il villaggio museo del Rinascimento bulgaro' },
  { c: 'Kotor dintorni Perast', k: 'Montenegro', lat: 42.49, lon: 18.69, t: 3, n: 'le isolette artificiali, le Bocche di Cattaro' },
  { c: 'Lovćen', k: 'Montenegro', lat: 42.4, lon: 18.83, t: 3, n: 'il mausoleo di Njegoš, la vista sulle Bocche' },

  // ── GRECIA E TURCHIA ────────────────────────────────────────────────
  { c: 'Monemvasia', k: 'Grecia', lat: 36.69, lon: 23.05, t: 3, n: 'la Gibilterra greca, la città bizantina sull\'isolotto' },
  { c: 'Nafpaktos', k: 'Grecia', lat: 38.39, lon: 21.83, t: 3, n: 'il piccolo porto veneziano, la battaglia di Lepanto' },
  { c: 'Vergina', k: 'Grecia', lat: 40.48, lon: 22.32, t: 3, n: 'la tomba di Filippo II di Macedonia, i tesori intatti' },
  { c: 'Volos e il Pelio', k: 'Grecia', lat: 39.36, lon: 22.94, t: 3, n: 'la porta del Pelio, gli argonauti, il traghetto per Skiathos' },
  { c: 'Ioannina dintorni Zagori', k: 'Grecia', lat: 39.9, lon: 20.75, t: 3, n: 'i ponti in pietra, i villaggi di Zagori, il canyon del Vikos' },
  { c: 'Parga', k: 'Grecia', lat: 39.29, lon: 20.4, t: 3, n: 'il castello veneziano sul mare, le isolette' },
  { c: 'Astypalea', k: 'Grecia', lat: 36.55, lon: 26.35, t: 3, n: 'la farfalla del Dodecaneso, il castello, le spiagge vuote' },
  { c: 'Symi', k: 'Grecia', lat: 36.62, lon: 27.83, t: 3, n: 'le case neoclassiche colorate sul porto, le spugne' },
  { c: 'Karpathos', k: 'Grecia', lat: 35.51, lon: 27.21, t: 3, n: 'i costumi tradizionali di Olympos, le spiagge selvagge' },
  { c: 'Chios', k: 'Grecia', lat: 38.37, lon: 26.14, t: 3, n: 'il mastice UNESCO, i villaggi medievali di Mastichochoria' },
  { c: 'Thassos', k: 'Grecia', lat: 40.78, lon: 24.71, t: 3, n: 'l\'isola verde del nord Egeo, il marmo antico' },
  { c: 'Alonissos', k: 'Grecia', lat: 39.16, lon: 23.86, t: 3, n: 'il parco marino delle foche monache, il villaggio vecchio' },
  { c: 'Antalya dintorni Kaleiçi', k: 'Turchia', lat: 36.89, lon: 30.7, t: 3, n: 'il centro ottomano sul porto, le cascate di Düden' },
  { c: 'Marmaris', k: 'Turchia', lat: 36.86, lon: 28.27, t: 3, n: 'il golfo, la Via Licia, il porto turistico' },
  { c: 'Assos', k: 'Turchia', lat: 39.49, lon: 26.34, t: 3, n: 'il tempio dorico sulla rupe, Aristotele, Lesbo di fronte' },
  { c: 'Bergama (Pergamo)', k: 'Turchia', lat: 39.12, lon: 27.18, t: 3, n: 'l\'acropoli ellenistica, l\'Asclepion, la biblioteca antica' },
  { c: 'Şirince', k: 'Turchia', lat: 37.95, lon: 27.35, t: 3, n: 'il villaggio greco sopra Efeso, il vino di frutta' },
  { c: 'Mardin', k: 'Turchia', lat: 37.31, lon: 40.74, t: 3, n: 'la città in pietra dorata sull\'altopiano mesopotamico' },
  { c: 'Göreme dintorni Cappadocia', k: 'Turchia', lat: 38.64, lon: 34.83, t: 2, n: 'le mongolfiere all\'alba, le case-grotta, le città sotterranee' },

  // ── MEDIO ORIENTE, CAUCASO, AFRICA ───────────────────────────────────
  { c: 'Um Qais', k: 'Giordania', lat: 32.66, lon: 35.68, t: 3, n: 'la Decapoli greco-romana con vista sul lago di Tiberiade' },
  { c: 'Jerash', k: 'Giordania', lat: 32.28, lon: 35.89, t: 3, n: 'la città romana meglio conservata del Medio Oriente' },
  { c: 'Eilat', k: 'Israele', lat: 29.56, lon: 34.95, t: 3, n: 'i coralli del Mar Rosso, il confine con tre paesi a vista' },
  { c: 'Rosh Hanikra', k: 'Israele', lat: 33.09, lon: 35.11, t: 3, n: 'le grotte bianche sul confine libanese, la funivia' },
  { c: 'Sidone e Tiro', k: 'Libano', lat: 33.27, lon: 35.2, t: 3, n: 'le città fenicie, i castelli crociati, le rovine romane sul mare' },
  { c: 'Musandam', k: 'Oman', lat: 26.2, lon: 56.25, t: 3, n: 'la Norvegia d\'Arabia, i fiordi, i dhow' },
  { c: 'Nizwa', k: 'Oman', lat: 22.93, lon: 57.53, t: 3, n: 'il forte, il souk del venerdì, il Jebel Akhdar sopra' },
  { c: 'AlUla dintorni Hegra', k: 'Arabia Saudita', lat: 26.63, lon: 37.9, t: 2, n: 'le tombe nabatee UNESCO, il deserto scolpito' },
  { c: 'Signagi', k: 'Georgia', lat: 41.62, lon: 45.92, t: 3, n: 'la città dell\'amore sulla Kakheti vinicola' },
  { c: 'Vardzia', k: 'Georgia', lat: 41.39, lon: 43.28, t: 3, n: 'la città-monastero scavata nella roccia' },
  { c: 'Erevan dintorni Khor Virap', k: 'Armenia', lat: 39.87, lon: 44.5, t: 3, n: 'il monastero con l\'Ararat sullo sfondo' },
  { c: 'Shali di Grozny', k: 'Russia', lat: 43.15, lon: 45.7, t: 3, n: 'il Caucaso ceceno, i villaggi torre di Vedeno' },
  { c: 'Chefchaouen dintorni', k: 'Marocco', lat: 35.17, lon: -5.27, t: 2, n: 'la città blu del Rif, le cascate di Akchour' },
  { c: 'Aït Benhaddou dintorni', k: 'Marocco', lat: 31.05, lon: -7.13, t: 3, n: 'il ksar UNESCO, set del Gladiatore e del Trono di Spade' },
  { c: 'Merzouga', k: 'Marocco', lat: 31.1, lon: -4.01, t: 2, n: 'le dune di Erg Chebbi, le notti nel deserto, i cammelli' },
  { c: 'Ifrane', k: 'Marocco', lat: 33.53, lon: -5.11, t: 3, n: 'la Svizzera del Marocco, la neve nel Medio Atlante' },
  { c: 'Kairouan', k: 'Tunisia', lat: 35.68, lon: 10.1, t: 3, n: 'la quarta città santa dell\'Islam, la grande moschea' },
  { c: 'Matmata', k: 'Tunisia', lat: 33.54, lon: 9.97, t: 3, n: 'le case-grotta berbere, set di Star Wars' },
  { c: 'Siwa', k: 'Egitto', lat: 29.2, lon: 25.52, t: 3, n: 'l\'oasi isolata di Alessandro Magno, le sorgenti di Cleopatra' },
  { c: 'Gondar', k: 'Etiopia', lat: 12.6, lon: 37.47, t: 3, n: 'i castelli reali, il Camelot d\'Africa, il lago Tana vicino' },
  { c: 'Axum', k: 'Etiopia', lat: 14.13, lon: 38.72, t: 3, n: 'gli obelischi del regno aksumita, l\'Arca dell\'Alleanza (secondo la tradizione)' },
  { c: 'Zanzibar Stone Town', k: 'Tanzania', lat: -6.16, lon: 39.19, t: 3, n: 'la città vecchia UNESCO, le porte scolpite, il mercato delle spezie' },
  { c: 'Lamu', k: 'Kenya', lat: -2.27, lon: 40.9, t: 3, n: 'l\'isola swahili senza auto, le dhow, l\'architettura in corallo' },
  { c: 'Franschhoek', k: 'Sudafrica', lat: -33.91, lon: 19.12, t: 3, n: 'i vini francesi del Capo, il treno del vino' },
  { c: 'Hermanus dintorni', k: 'Sudafrica', lat: -34.42, lon: 19.23, t: 3, n: 'le balene dalla scogliera, Fernkloof' },
  { c: 'Knysna', k: 'Sudafrica', lat: -34.04, lon: 23.05, t: 3, n: 'la laguna, le foreste, le ostriche' },
  { c: 'Antananarivo dintorni', k: 'Madagascar', lat: -18.88, lon: 47.5, t: 3, n: 'le rizières terrazzate, i baobab di Morondava a un volo' },

  // ── ASIA ────────────────────────────────────────────────────────────
  { c: 'Ise', k: 'Giappone', lat: 34.49, lon: 136.72, t: 3, n: 'il santuario shintoista più sacro, ricostruito ogni 20 anni' },
  { c: 'Kii Peninsula Kumano Kodo', k: 'Giappone', lat: 33.73, lon: 135.77, t: 3, n: 'il cammino di pellegrinaggio UNESCO, gli onsen lungo il percorso' },
  { c: 'Yakushima', k: 'Giappone', lat: 30.34, lon: 130.51, t: 3, n: 'la foresta pluviale antichissima, ispirazione per Miyazaki' },
  { c: 'Ogimachi Shirakawa-go', k: 'Giappone', lat: 36.26, lon: 136.9, t: 3, n: 'i tetti gassho-zukuri UNESCO, la neve d\'inverno' },
  { c: 'Miyajima', k: 'Giappone', lat: 34.3, lon: 132.32, t: 3, n: 'il torii galleggiante, i cervi liberi, il tempio Itsukushima' },
  { c: 'Otaru', k: 'Giappone', lat: 43.19, lon: 141.0, t: 3, n: 'il canale storico, i carillon, il vetro artigianale' },
  { c: 'Andong', k: 'Corea del Sud', lat: 36.57, lon: 128.73, t: 3, n: 'il villaggio Hahoe UNESCO, le maschere tradizionali' },
  { c: 'Suncheon', k: 'Corea del Sud', lat: 34.95, lon: 127.49, t: 3, n: 'la palude UNESCO, il villaggio del dramma coreano' },
  { c: 'Pingyao', k: 'Cina', lat: 37.2, lon: 112.15, t: 3, n: 'la città murata Ming UNESCO, le prime banche cinesi' },
  { c: 'Datong', k: 'Cina', lat: 40.09, lon: 113.3, t: 3, n: 'le grotte di Yungang UNESCO, il tempio sospeso' },
  { c: 'Wuzhen', k: 'Cina', lat: 30.75, lon: 120.49, t: 3, n: 'la città sull\'acqua vicino Shanghai, i canali di notte' },
  { c: 'Kashgar', k: 'Cina', lat: 39.47, lon: 75.99, t: 3, n: 'l\'ultima oasi della via della seta prima del Pamir' },
  { c: 'Alishan', k: 'Taiwan', lat: 23.51, lon: 120.8, t: 3, n: 'il trenino di montagna, il mare di nuvole, il tè oolong' },
  { c: 'Sun Moon Lake', k: 'Taiwan', lat: 23.86, lon: 120.91, t: 3, n: 'il lago sacro degli Thao, in bici o in barca' },
  { c: 'Battambang dintorni', k: 'Cambogia', lat: 13.1, lon: 103.2, t: 3, n: 'il treno di bambù, i templi minori senza folla' },
  { c: 'Kampot', k: 'Cambogia', lat: 10.61, lon: 104.18, t: 3, n: 'il pepe più pregiato del mondo, il fiume, la vecchia coloniale' },
  { c: 'Dalat dintorni', k: 'Vietnam', lat: 11.94, lon: 108.44, t: 3, n: 'le cascate, il caffè, le ville coloniali francesi' },
  { c: 'Ninh Binh', k: 'Vietnam', lat: 20.25, lon: 105.97, t: 3, n: 'la Baia di Ha Long sulla terraferma, Tam Coc in barca a remi' },
  { c: 'Vientiane dintorni', k: 'Laos', lat: 17.97, lon: 102.6, t: 3, n: 'i templi, il Buddha Park, il tramonto sul Mekong' },
  { c: 'Bagan dintorni', k: 'Myanmar', lat: 21.17, lon: 94.86, t: 2, n: 'le 2.000 pagode nella pianura, la mongolfiera all\'alba' },
  { c: 'Ubud dintorni Tegallalang', k: 'Indonesia', lat: -8.43, lon: 115.28, t: 3, n: 'le risaie a terrazze, il tempio delle scimmie' },
  { c: 'Lombok Senggigi', k: 'Indonesia', lat: -8.49, lon: 116.04, t: 3, n: 'il Rinjani, le spiagge meno affollate di Bali' },
  { c: 'Flores dintorni Kelimutu', k: 'Indonesia', lat: -8.77, lon: 121.82, t: 3, n: 'i tre laghi colorati del vulcano, i villaggi Ngada' },
  { c: 'Baguio', k: 'Filippine', lat: 16.41, lon: 120.6, t: 3, n: 'la città estiva coloniale sulle montagne, il mercato' },
  { c: 'Vigan', k: 'Filippine', lat: 17.57, lon: 120.39, t: 3, n: 'la città coloniale spagnola meglio conservata dell\'Asia, UNESCO' },
  { c: 'Batanes', k: 'Filippine', lat: 20.45, lon: 121.97, t: 3, n: 'le colline verdi sull\'oceano, le case in pietra corallina' },
  { c: 'Ipoh', k: 'Malesia', lat: 4.6, lon: 101.08, t: 3, n: 'lo street food cinese-malese, le grotte calcaree, l\'architettura coloniale' },
  { c: 'Melaka dintorni', k: 'Malesia', lat: 2.19, lon: 102.25, t: 3, n: 'il porto peranakan UNESCO, le case-museo' },
  { c: 'Jaffna', k: 'Sri Lanka', lat: 9.66, lon: 80.02, t: 3, n: 'il nord tamil, i templi indù, le isole vicine' },
  { c: 'Bentota', k: 'Sri Lanka', lat: 6.42, lon: 79.99, t: 3, n: 'il fiume e le mangrovie, le spiagge, gli hotel di Bawa' },
  { c: 'Puri', k: 'India', lat: 19.8, lon: 85.83, t: 3, n: 'il tempio di Jagannath, la spiaggia, la carovana dei carri' },
  { c: 'Hampi dintorni', k: 'India', lat: 15.34, lon: 76.46, t: 2, n: 'i massi giganti, i templi Vijayanagara, il fiume in coracle' },
  { c: 'Munnar', k: 'India', lat: 10.09, lon: 77.06, t: 3, n: 'le piantagioni di tè a perdita d\'occhio, le colline' },
  { c: 'Hampi Badami', k: 'India', lat: 15.92, lon: 75.68, t: 3, n: 'i templi scavati nella roccia rossa, il Karnataka antico' },
  { c: 'Orchha', k: 'India', lat: 25.35, lon: 78.64, t: 3, n: 'i cenotafi sul fiume Betwa, i palazzi abbandonati' },
  { c: 'Mandawa e lo Shekhawati', k: 'India', lat: 28.06, lon: 75.14, t: 3, n: 'gli affreschi delle haveli, la galleria d\'arte a cielo aperto' },
  { c: 'Bikaner', k: 'India', lat: 28.02, lon: 73.31, t: 3, n: 'il forte Junagarh, il tempio dei ratti di Deshnok' },
  { c: 'Wular e Srinagar', k: 'India', lat: 34.08, lon: 74.8, t: 3, n: 'le houseboat sul Dal Lake, i giardini Mughal' },
];

export const EXTRA_THEME_PLACES_2: Record<string, ExtraThemePlace[]> = {
  cinema: [
    { city: 'Palermo dintorni Bagheria', country: 'Italia', lat: 38.08, lon: 13.51, note: 'Nuovo Cinema Paradiso, Baarìa di Tornatore' },
    { city: 'Alberobello', country: 'Italia', lat: 40.78, lon: 17.24, note: 'Pane amore e fantasia, i trulli in molte fiction' },
    { city: 'Orvieto', country: 'Italia', lat: 42.72, lon: 12.11, note: 'La grande bellezza, il duomo in tanti film italiani' },
    { city: 'Certaldo', country: 'Italia', lat: 43.55, lon: 11.04, note: 'Non ci resta che piangere di Troisi e Benigni' },
    { city: 'Filicudi e Panarea', country: 'Italia', lat: 38.57, lon: 14.55, note: 'L\'avventura di Antonioni' },
    { city: 'Como', country: 'Italia', lat: 45.81, lon: 9.09, note: 'Star Wars - Episodio II a Villa del Balbianello, Ocean\'s Twelve' },
    { city: 'Villa d\'Este Tivoli', country: 'Italia', lat: 41.96, lon: 12.8, note: 'La dolce vita, Ben-Hur, molti kolossal hollywoodiani' },
    { city: 'Zaragoza', country: 'Spagna', lat: 41.65, lon: -0.88, note: 'set di molte produzioni storiche spagnole' },
    { city: 'Girona', country: 'Spagna', lat: 41.98, lon: 2.82, note: 'Il Trono di Spade ad Approdo del Re, il Barri Vell' },
    { city: 'Bardenas Reales', country: 'Spagna', lat: 42.19, lon: -1.5, note: 'Il Trono di Spade, il deserto navarro come location aliena' },
    { city: 'Skellig Michael', country: 'Irlanda', lat: 51.77, lon: -10.54, note: 'Star Wars - Il risveglio della Forza e Gli ultimi Jedi' },
    { city: 'Cotswolds', country: 'Regno Unito', lat: 51.83, lon: -1.84, note: 'Il diario di Bridget Jones, Downton Abbey' },
    { city: 'Lacock', country: 'Regno Unito', lat: 51.42, lon: -2.12, note: 'Harry Potter (l\'abbazia), Downton Abbey, Orgoglio e pregiudizio' },
    { city: 'Alnwick Castle', country: 'Regno Unito', lat: 55.42, lon: -1.71, note: 'Harry Potter, i corsi di volo con la scopa' },
    { city: 'Durham', country: 'Regno Unito', lat: 54.78, lon: -1.58, note: 'Harry Potter e la pietra filosofale, i chiostri della cattedrale' },
    { city: 'Freiburg', country: 'Germania', lat: 47.99, lon: 7.85, note: 'set di numerose produzioni tedesche in costume' },
    { city: 'Görlitz', country: 'Germania', lat: 51.15, lon: 14.99, note: 'Grand Budapest Hotel, Inglourious Basterds' },
    { city: 'Locarno', country: 'Svizzera', lat: 46.17, lon: 8.8, note: 'il festival del cinema, Piazza Grande sotto le stelle' },
    { city: 'Kraków dintorni Płaszów', country: 'Polonia', lat: 50.03, lon: 19.97, note: 'Schindler\'s List, l\'ex campo, il quartiere Kazimierz' },
    { city: 'Warszawa', country: 'Polonia', lat: 52.23, lon: 21.01, note: 'Il pianista di Polanski, la ricostruzione del ghetto' },
    { city: 'Dubrovnik dintorni Lokrum', country: 'Croazia', lat: 42.64, lon: 18.12, note: 'Il Trono di Spade: Approdo del Re e Qarth' },
    { city: 'Kotor', country: 'Montenegro', lat: 42.42, lon: 18.77, note: 'Il Trono di Spade, Casino Royale' },
    { city: 'Ait Benhaddou', country: 'Marocco', lat: 31.05, lon: -7.13, note: 'Il gladiatore, Il Trono di Spade, Lawrence d\'Arabia' },
    { city: 'Wadi Rum', country: 'Giordania', lat: 29.58, lon: 35.42, note: 'The Martian, Lawrence d\'Arabia, Dune' },
    { city: 'Chandigarh', country: 'India', lat: 30.73, lon: 76.78, note: 'la città di Le Corbusier in decine di film Bollywood' },
    { city: 'Interlaken dintorni Schilthorn', country: 'Svizzera', lat: 46.56, lon: 7.83, note: 'Agente 007 - Al servizio segreto di Sua Maestà' },
    { city: 'Praga dintorni Barrandov', country: 'Cechia', lat: 50.03, lon: 14.4, note: 'gli studi di Barrandov, Mission: Impossible, Casino Royale' },
    { city: 'Manarola', country: 'Italia', lat: 44.11, lon: 9.73, note: 'ambientazioni delle Cinque Terre in numerosi documentari e fiction' },
    { city: 'Chicago dintorni Wrigley', country: 'Stati Uniti', lat: 41.95, lon: -87.66, note: 'Alto rischio, Wayne\'s World, il quartiere' },
    { city: 'Charleston', country: 'Stati Uniti', lat: 32.78, lon: -79.93, note: 'Il buio oltre la siepe, The Notebook, Cocktail' },
  ],
  fioriture: [
    { city: 'Palo Verde Arizona', country: 'Stati Uniti', lat: 33.45, lon: -111.94, note: 'i saguari in fiore nel deserto di Sonora (maggio-giugno)' },
    { city: 'Bluebell Woods Kent', country: 'Regno Unito', lat: 51.2, lon: 0.6, note: 'i tappeti di giacinti selvatici, Hole Park (aprile-maggio)' },
    { city: 'Andalusia Cadice mandorli', country: 'Spagna', lat: 36.53, lon: -6.29, note: 'i mandorli in fiore della Sierra (febbraio)' },
    { city: 'Puglia mandorli', country: 'Italia', lat: 40.78, lon: 17.24, note: 'gli ulivi e i mandorli della Valle d\'Itria (febbraio-marzo)' },
    { city: 'Formia e il Golfo', country: 'Italia', lat: 41.26, lon: 13.6, note: 'gli agrumi in fiore della Riviera di Ulisse (marzo-aprile)' },
    { city: 'Ronda dintorni', country: 'Spagna', lat: 36.74, lon: -5.16, note: 'i mandorli della Serranía (febbraio)' },
    { city: 'Bhutan Paro', country: 'Bhutan', lat: 27.43, lon: 89.42, note: 'i rododendri himalayani in fiore (aprile-maggio)' },
    { city: 'Sikkim', country: 'India', lat: 27.53, lon: 88.51, note: 'i rododendri del parco di Yumthang, la valle dei fiori himalayana' },
    { city: 'Xinjiang Ili', country: 'Cina', lat: 43.9, lon: 81.3, note: 'i campi di lavanda della valle di Ili (giugno-luglio)' },
    { city: 'Bulgaria Valle delle Rose', country: 'Bulgaria', lat: 42.63, lon: 25.35, note: 'la raccolta all\'alba per l\'olio essenziale (maggio-giugno)' },
    { city: 'Israele Negev', country: 'Israele', lat: 30.7, lon: 34.8, note: 'i fiori del deserto dopo le piogge invernali (marzo)' },
    { city: 'Marocco Tafraoute', country: 'Marocco', lat: 29.72, lon: -8.97, note: 'i mandorli in fiore fra le rocce rosa dell\'Anti Atlante (febbraio)' },
    { city: 'Città del Capo Namaqualand dintorni', country: 'Sudafrica', lat: -30.5, lon: 17.6, note: 'le margherite arancioni dopo le prime piogge (agosto-settembre)' },
    { city: 'Sydney Botanic Garden', country: 'Australia', lat: -33.86, lon: 151.22, note: 'le jacaranda viola della città (ottobre-novembre)' },
    { city: 'Pretoria', country: 'Sudafrica', lat: -25.75, lon: 28.19, note: 'la città viola delle jacaranda (ottobre)' },
    { city: 'Buenos Aires', country: 'Argentina', lat: -34.6, lon: -58.38, note: 'i jacarandá dei viali (ottobre-novembre)' },
    { city: 'Nuova Zelanda Hawke\'s Bay', country: 'Nuova Zelanda', lat: -39.49, lon: 176.92, note: 'i frutteti in fiore, primavera australe (settembre-ottobre)' },
  ],
  fauna: [
    { city: 'Isole Eolie Filicudi', country: 'Italia', lat: 38.57, lon: 14.55, note: 'i delfini e le foche monache avvistate al largo' },
    { city: 'Circeo', country: 'Italia', lat: 41.23, lon: 13.1, note: 'gli aironi e i cinghiali del parco, la palude costiera' },
    { city: 'Maremma parco', country: 'Italia', lat: 42.66, lon: 11.05, note: 'i cavalli maremmani, i daini, le torri costiere' },
    { city: 'Vendicari', country: 'Italia', lat: 36.8, lon: 15.1, note: 'i fenicotteri della riserva, le tartarughe che nidificano' },
    { city: 'Pian Grande Sibillini', country: 'Italia', lat: 42.84, lon: 13.2, note: 'i lupi appenninici e i camosci reintrodotti' },
    { city: 'Ustica marina', country: 'Italia', lat: 38.71, lon: 13.19, note: 'la riserva marina più antica d\'Italia, le cernie' },
    { city: 'Islanda Snæfellsnes', country: 'Islanda', lat: 64.9, lon: -23.7, note: 'le foche della penisola, le orche al largo' },
    { city: 'Isole Shetland', country: 'Regno Unito', lat: 60.15, lon: -1.15, note: 'le pulcinelle di mare di Sumburgh, le foche' },
    { city: 'Mull of Galloway', country: 'Regno Unito', lat: 54.63, lon: -4.85, note: 'le colonie di uccelli marini, i delfini' },
    { city: 'Camargue dintorni Aigues-Mortes', country: 'Francia', lat: 43.57, lon: 4.19, note: 'i cavalli bianchi e i fenicotteri delle saline' },
    { city: 'Baia di Somme Le Crotoy', country: 'Francia', lat: 50.22, lon: 1.63, note: 'le foche a bassa marea, i cavalli di Camargue in visita' },
    { city: 'Ré e le sue foche', country: 'Francia', lat: 46.19, lon: -1.4, note: 'gli uccelli migratori della riserva di Lilleau des Niges' },
    { city: 'Kruger dintorni Sabi Sands', country: 'Sudafrica', lat: -24.7, lon: 31.55, note: 'i big five a distanza ravvicinata, i lodge privati' },
    { city: 'Ngorongoro', country: 'Tanzania', lat: -3.16, lon: 35.59, note: 'il cratere con la più alta densità di predatori d\'Africa' },
    { city: 'Ruaha', country: 'Tanzania', lat: -7.5, lon: 34.5, note: 'i leoni e i baobab, meno turisti del Serengeti' },
    { city: 'Etosha dintorni', country: 'Namibia', lat: -18.86, lon: 16.33, note: 'gli elefanti bianchi coperti di polvere calcarea' },
    { city: 'Isole Galapagos Isabela', country: 'Ecuador', lat: -0.83, lon: -91.0, note: 'le iguane e i fenicotteri, i vulcani attivi' },
    { city: 'Costa Rica Tortuguero', country: 'Costa Rica', lat: 10.54, lon: -83.5, note: 'le tartarughe che nidificano, i bradipi, le scimmie' },
    { city: 'Belize barriera corallina', country: 'Belize', lat: 17.3, lon: -87.5, note: 'il Grande Buco Blu, gli squali balena stagionali' },
    { city: 'Alaska Katmai', country: 'Stati Uniti', lat: 58.5, lon: -155.0, note: 'gli orsi bruni che pescano i salmoni a Brooks Falls' },
    { city: 'Costa Rica Corcovado', country: 'Costa Rica', lat: 8.48, lon: -83.6, note: 'la giungla più densa di biodiversità del pianeta' },
    { city: 'Australia Ningaloo', country: 'Australia', lat: -22.7, lon: 113.7, note: 'gli squali balena, la barriera accessibile dalla spiaggia' },
    { city: 'Malaysia Danum Valley', country: 'Malesia', lat: 4.97, lon: 117.8, note: 'la foresta primaria del Borneo, gli oranghi selvatici' },
  ],
  neve: [
    { city: 'Selva di Val Gardena', country: 'Italia', lat: 46.56, lon: 11.75, note: 'il Sellaronda in senso orario e antiorario' },
    { city: 'San Martino di Castrozza', country: 'Italia', lat: 46.26, lon: 11.8, note: 'le Pale di San Martino, la Val di Fiemme' },
    { city: 'Folgaria e Lavarone', country: 'Italia', lat: 45.93, lon: 11.17, note: 'gli altipiani trentini, gli impianti fra i boschi' },
    { city: 'Pila Aosta', country: 'Italia', lat: 45.68, lon: 7.3, note: 'la funivia da Aosta città alla neve' },
    { city: 'Prato Nevoso', country: 'Italia', lat: 44.32, lon: 7.72, note: 'il Cuneese, la Vialattea vicina' },
    { city: 'Passo Tonale', country: 'Italia', lat: 46.26, lon: 10.58, note: 'il ghiacciaio Presena, il confine fra Trentino e Lombardia' },
    { city: 'Innichen San Candido', country: 'Italia', lat: 46.73, lon: 12.28, note: 'le Tre Cime, il fondovalle pusterese' },
    { city: 'Obertauern', country: 'Austria', lat: 47.25, lon: 13.56, note: 'lo sci facile in quota, il tour delle piste circolare' },
    { city: 'Saalbach-Hinterglemm', country: 'Austria', lat: 47.39, lon: 12.64, note: 'la Skicircus, i rifugi, la vita dopo sci' },
    { city: 'Mayrhofen', country: 'Austria', lat: 47.16, lon: 11.86, note: 'lo Zillertal, l\'Harakiri, la pista più ripida d\'Austria' },
    { city: 'Chatel Portes du Soleil', country: 'Francia', lat: 46.26, lon: 6.83, note: 'il comprensorio franco-svizzero più esteso del mondo' },
    { city: 'La Plagne', country: 'Francia', lat: 45.51, lon: 6.68, note: 'la pista olimpica di bob, il Paradiski con Les Arcs' },
    { city: 'Alpe d\'Huez', country: 'Francia', lat: 45.09, lon: 6.07, note: 'la Sarenne, la salita ciclistica leggendaria d\'estate' },
    { city: 'Serre Chevalier', country: 'Francia', lat: 44.95, lon: 6.55, note: 'i villaggi collegati, il sole delle Alpi del sud' },
    { city: 'Formigal', country: 'Spagna', lat: 42.78, lon: -0.4, note: 'il più grande comprensorio pirenaico spagnolo' },
    { city: 'Grandvalira Andorra', country: 'Andorra', lat: 42.58, lon: 1.67, note: 'il più grande dei Pirenei, i prezzi del duty free' },
    { city: 'Pyhä-Luosto', country: 'Finlandia', lat: 67.0, lon: 27.13, note: 'la Lapponia, le renne, l\'aurora sulle piste' },
    { city: 'Trysil', country: 'Norvegia', lat: 61.31, lon: 12.27, note: 'la stazione più grande di Norvegia' },
    { city: 'Whakapapa Nuova Zelanda', country: 'Nuova Zelanda', lat: -39.25, lon: 175.55, note: 'sciare sul vulcano Ruapehu, Il Signore degli Anelli' },
    { city: 'Perisher Australia', country: 'Australia', lat: -36.4, lon: 148.41, note: 'le Snowy Mountains, il comprensorio più grande dell\'emisfero sud' },
    { city: 'Cerro Bayo', country: 'Argentina', lat: -40.7, lon: -71.55, note: 'la Patagonia, vista sul lago Nahuel Huapi' },
    { city: 'Portillo', country: 'Cile', lat: -32.83, lon: -70.13, note: 'la valle d\'alta quota, la storica sede di gare mondiali' },
  ],
  botteghe: [
    { city: 'Palermo Ballarò', country: 'Italia', lat: 38.11, lon: 13.36, note: 'gli argentieri e gli intagliatori del mercato storico' },
    { city: 'Assisi', country: 'Italia', lat: 43.07, lon: 12.62, note: 'la tessitura francescana, le stampe su tela' },
    { city: 'Orvieto', country: 'Italia', lat: 42.72, lon: 12.11, note: 'la ceramica orvietana, i merletti al tombolo' },
    { city: 'Norcia', country: 'Italia', lat: 42.79, lon: 13.09, note: 'i coltelli e le norcinerie, il tartufo lavorato' },
    { city: 'Anghiari', country: 'Italia', lat: 43.54, lon: 12.05, note: 'i tessuti tradizionali, i telai storici' },
    { city: 'Le Marche Fabriano', country: 'Italia', lat: 43.34, lon: 12.91, note: 'la carta a mano UNESCO, la filigrana' },
    { city: 'Sevilla Triana', country: 'Spagna', lat: 37.38, lon: -6.0, note: 'gli azulejos storici, i laboratori di ceramica sul Guadalquivir' },
    { city: 'Talavera de la Reina', country: 'Spagna', lat: 39.96, lon: -4.83, note: 'la ceramica che dà il nome allo stile spagnolo' },
    { city: 'Fez dintorni Meknès', country: 'Marocco', lat: 33.89, lon: -5.55, note: 'l\'ottone e il cuoio delle botteghe imperiali' },
    { city: 'Cusco San Blas', country: 'Perù', lat: -13.52, lon: -71.97, note: 'gli argentieri e i pittori del quartiere degli artisti' },
    { city: 'Antigua Guatemala', country: 'Guatemala', lat: 14.56, lon: -90.73, note: 'i tessitori maya, il jade, i mercati colorati' },
    { city: 'Bagan', country: 'Myanmar', lat: 21.17, lon: 94.86, note: 'la lacca birmana, i laboratori fra le pagode' },
    { city: 'Luang Prabang', country: 'Laos', lat: 19.89, lon: 102.14, note: 'la tessitura della seta, la carta di gelso, i monaci al mattino' },
    { city: 'Yogyakarta', country: 'Indonesia', lat: -7.8, lon: 110.36, note: 'il batik, l\'argento di Kotagede' },
    { city: 'Marrakech dintorni', country: 'Marocco', lat: 31.63, lon: -8.01, note: 'i tappeti berberi, il cuoio, le lanterne di metallo battuto' },
  ],
  vino: [
    { city: 'Vulture Aglianico', country: 'Italia', lat: 40.96, lon: 15.6, note: 'l\'Aglianico del Vulture sul vulcano spento, Rionero' },
    { city: 'Irpinia Taurasi', country: 'Italia', lat: 41.01, lon: 14.96, note: 'il Barolo del Sud, Mastroberardino' },
    { city: 'Erice e le vigne trapanesi', country: 'Italia', lat: 37.85, lon: 12.65, note: 'il Grillo e lo Zibibbo delle colline trapanesi' },
    { city: 'Chianti Classico Gaiole', country: 'Italia', lat: 43.47, lon: 11.43, note: 'il Gallo Nero, i castelli fra i vigneti' },
    { city: 'Colli Piacentini', country: 'Italia', lat: 44.8, lon: 9.6, note: 'la Malvasia e il Gutturnio, i castelli del Piacentino' },
    { city: 'Douro dintorni Peso da Régua', country: 'Portogallo', lat: 41.16, lon: -7.79, note: 'la stazione da cui parte il treno del Douro' },
    { city: 'Alentejo Vidigueira', country: 'Portogallo', lat: 38.21, lon: -7.8, note: 'i vini in anfora, la tradizione romana del talha' },
    { city: 'Somontano', country: 'Spagna', lat: 42.12, lon: 0.13, note: 'i Pirenei aragonesi, un\'enologia giovane e curata' },
    { city: 'Rueda', country: 'Spagna', lat: 41.4, lon: -4.95, note: 'il Verdejo di Castiglia, le bodegas sotterranee' },
    { city: 'Georgia Kvareli', country: 'Georgia', lat: 41.95, lon: 45.8, note: 'le cantine nel Caucaso, la tradizione degli qvevri' },
    { city: 'Etna Nord Randazzo', country: 'Italia', lat: 37.88, lon: 14.94, note: 'i vigneti sulla lava a 900 metri, il Nerello Mascalese' },
    { city: 'Franschhoek dintorni', country: 'Sudafrica', lat: -33.91, lon: 19.12, note: 'i vitigni francesi portati dagli ugonotti' },
    { city: 'Casablanca Valley', country: 'Cile', lat: -33.32, lon: -71.4, note: 'lo Chardonnay e il Pinot Noir vicino all\'oceano' },
    { city: 'Yarra Valley', country: 'Australia', lat: -37.65, lon: 145.4, note: 'il Pinot Noir a un\'ora da Melbourne' },
    { city: 'Central Otago', country: 'Nuova Zelanda', lat: -45.03, lon: 169.15, note: 'il Pinot Noir più a sud del mondo' },
  ],
  'aperture-straordinarie': [
    { city: 'Firenze Corridoio Vasariano', country: 'Italia', lat: 43.77, lon: 11.25, note: 'riaperto con visite contingentate dal 2022' },
    { city: 'Napoli Palazzo Reale', country: 'Italia', lat: 40.84, lon: 14.25, note: 'gli appartamenti storici aperti a rotazione, il teatro di corte' },
    { city: 'Palermo Palazzo Steri', country: 'Italia', lat: 38.12, lon: 13.36, note: 'le celle dell\'Inquisizione con i graffiti, aperture guidate' },
    { city: 'Torino Palazzina di Caccia Stupinigi', country: 'Italia', lat: 45.0, lon: 7.6, note: 'la reggia sabauda UNESCO, eventi serali' },
    { city: 'Vienna Spanische Hofreitschule', country: 'Austria', lat: 48.21, lon: 16.37, note: 'gli allenamenti mattutini dei Lipizzani aperti al pubblico' },
    { city: 'Berlino Bundestag', country: 'Germania', lat: 52.52, lon: 13.38, note: 'la cupola del Reichstag, prenotazione online gratuita' },
    { city: 'Praga Castello', country: 'Cechia', lat: 50.09, lon: 14.4, note: 'gli appartamenti presidenziali aperti in occasioni speciali' },
    { city: 'Londra Guildhall', country: 'Regno Unito', lat: 51.52, lon: -0.09, note: 'la City medievale aperta nell\'Open House' },
    { city: 'Roma Domus Aurea', country: 'Italia', lat: 41.89, lon: 12.5, note: 'visite guidate con realtà virtuale nei weekend' },
    { city: 'Torino Reggia di Venaria', country: 'Italia', lat: 45.14, lon: 7.63, note: 'la Venaria di notte, le fontane danzanti d\'estate' },
  ],
  memoria: [
    { city: 'Torino Cimitero Monumentale', country: 'Italia', lat: 45.09, lon: 7.68, note: 'la tomba di Cavour, i grandi torinesi' },
    { city: 'Firenze Santa Croce', country: 'Italia', lat: 43.77, lon: 11.26, note: 'le tombe di Michelangelo, Galileo, Machiavelli' },
    { city: 'Ravenna tomba di Dante', country: 'Italia', lat: 44.42, lon: 12.2, note: 'l\'esilio e la tomba del poeta, la lanterna sempre accesa' },
    { city: 'Palermo Cappuccini', country: 'Italia', lat: 38.11, lon: 13.34, note: 'le catacombe con le mummie, un luogo che chiede rispetto assoluto' },
    { city: 'Weimar Goethe-Schiller', country: 'Germania', lat: 50.98, lon: 11.33, note: 'la cripta comune dei due poeti' },
    { city: 'Highgate Cemetery', country: 'Regno Unito', lat: 51.57, lon: -0.15, note: 'Marx, George Eliot, il West e l\'East cemetery' },
    { city: 'Montmartre Cimitero', country: 'Francia', lat: 48.89, lon: 2.33, note: 'Degas, Truffaut, Dalida' },
    { city: 'Vienna Zentralfriedhof', country: 'Austria', lat: 48.15, lon: 16.44, note: 'Beethoven, Schubert, Falco, la tomba onoraria' },
    { city: 'Buchenwald', country: 'Germania', lat: 51.02, lon: 11.25, note: 'il memoriale sulla collina sopra Weimar' },
    { city: 'Yad Vashem Gerusalemme', country: 'Israele', lat: 31.77, lon: 35.18, note: 'il memoriale della Shoah, il Giardino dei Giusti' },
    { city: 'Hiroshima Peace Memorial', country: 'Giappone', lat: 34.4, lon: 132.45, note: 'già citata: approfondimento sul museo e i sopravvissuti' },
    { city: 'Choeung Ek', country: 'Cambogia', lat: 11.48, lon: 104.9, note: 'i campi di sterminio Khmer, l\'audioguida necessaria' },
    { city: 'Robben Island', country: 'Sudafrica', lat: -33.81, lon: 18.37, note: 'la cella di Mandela raccontata da ex prigionieri politici' },
    { city: 'Ground Zero New York', country: 'Stati Uniti', lat: 40.71, lon: -74.01, note: 'le due vasche, i nomi incisi' },
  ],
  souvenir: [
    { city: 'Marsala vino liquoroso', country: 'Italia', lat: 37.8, lon: 12.43, note: 'le bottiglie storiche Florio da portare a casa' },
    { city: 'Alba tartufo', country: 'Italia', lat: 44.7, lon: 8.03, note: 'il tartufo bianco fresco in stagione, i cioccolatini' },
    { city: 'Praga marionette', country: 'Cechia', lat: 50.09, lon: 14.42, note: 'i burattini di legno intagliato a mano' },
    { city: 'Vienna porcellana', country: 'Austria', lat: 48.21, lon: 16.37, note: 'Augarten, le tazze storiche dei caffè' },
    { city: 'Kyoto ventagli', country: 'Giappone', lat: 35.01, lon: 135.77, note: 'i ventagli dipinti a mano, il tè matcha in scatola' },
    { city: 'Marrakech tappeti', country: 'Marocco', lat: 31.63, lon: -8.01, note: 'i tappeti berberi autentici, si contratta sempre' },
    { city: 'Città del Messico artigianato', country: 'Messico', lat: 19.43, lon: -99.13, note: 'gli alebrijes, la ceramica di Talavera' },
    { city: 'Buenos Aires pelle', country: 'Argentina', lat: -34.6, lon: -58.38, note: 'le giacche e borse in pelle, il mate decorato' },
  ],
  'fabbriche-del-gusto': [
    { city: 'Vulture olio', country: 'Italia', lat: 40.96, lon: 15.6, note: 'i frantoi lucani, le noci' },
    { city: 'Salento olio', country: 'Italia', lat: 40.2, lon: 18.2, note: 'i frantoi ipogei del Salento, gli ulivi millenari' },
    { city: 'Colonnata lardo', country: 'Italia', lat: 44.1, lon: 10.17, note: 'già citata: le larderie nelle grotte di marmo' },
    { city: 'Norcia norcineria', country: 'Italia', lat: 42.79, lon: 13.09, note: 'le antiche norcinerie, il tartufo nero' },
    { city: 'Rioja bodegas', country: 'Spagna', lat: 42.47, lon: -2.45, note: 'le bodegas storiche con le botti secolari' },
    { city: 'Champagne Épernay dintorni', country: 'Francia', lat: 49.04, lon: 3.96, note: 'le cantine sotterranee delle grandi maison' },
    { city: 'Cheddar Gorge', country: 'Regno Unito', lat: 51.28, lon: -2.77, note: 'le grotte dove stagiona il vero cheddar' },
    { city: 'Guinness Dublino', country: 'Irlanda', lat: 53.34, lon: -6.29, note: 'già citata: la Storehouse e la pinta panoramica' },
  ],
  'musei-impresa': [
    { city: 'Modena Museo Panini', country: 'Italia', lat: 44.65, lon: 10.93, note: 'la collezione di auto storiche di Umberto Panini' },
    { city: 'Novara Museo Agusta', country: 'Italia', lat: 45.45, lon: 8.62, note: 'le moto da corsa italiane, Gallarate' },
    { city: 'Torino Museo del Cinema Mole', country: 'Italia', lat: 45.07, lon: 7.69, note: 'la Mole Antonelliana come museo, non solo simbolo' },
    { city: 'Barcellona Museo Colección Barcelona', country: 'Spagna', lat: 41.39, lon: 2.17, note: 'il design catalano, la moda locale' },
    { city: 'Copenaghen Carlsberg', country: 'Danimarca', lat: 55.66, lon: 12.53, note: 'la fabbrica storica, gli elefanti del cancello' },
    { city: 'Amsterdam Heineken Experience', country: 'Paesi Bassi', lat: 52.36, lon: 4.89, note: 'la vecchia fabbrica trasformata in museo interattivo' },
    { city: 'Detroit Motown Museum', country: 'Stati Uniti', lat: 42.37, lon: -83.09, note: 'lo studio Hitsville U.S.A. originale' },
  ],
  wellness: [
    { city: 'Ischia Sorgeto', country: 'Italia', lat: 40.71, lon: 13.87, note: 'la baia con l\'acqua calda naturale in mezzo al mare freddo' },
    { city: 'Terme di Cretone', country: 'Italia', lat: 42.13, lon: 12.78, note: 'le terme laziali meno conosciute' },
    { city: 'Furnas Azzorre', country: 'Portogallo', lat: 37.77, lon: -25.32, note: 'le sorgenti vulcaniche, il cozido cotto nel terreno caldo' },
    { city: 'Blue Lagoon Islanda dintorni Myvatn', country: 'Islanda', lat: 65.63, lon: -16.9, note: 'già citata: le terme meno turistiche del nord' },
    { city: 'Onsen di Yudanaka', country: 'Giappone', lat: 36.74, lon: 138.42, note: 'vicino ai macachi delle nevi, i ryokan tradizionali' },
    { city: 'Hot Springs Rotorua dintorni Waimangu', country: 'Nuova Zelanda', lat: -38.28, lon: 176.38, note: 'la valle vulcanica con il lago che fuma' },
  ],
  agriturismi: [
    { city: 'Alta Murgia', country: 'Italia', lat: 41.0, lon: 16.4, note: 'le masserie storiche, i muretti a secco, il grano' },
    { city: 'Val Camonica', country: 'Italia', lat: 46.03, lon: 10.28, note: 'le fattorie fra le incisioni rupestri UNESCO' },
    { city: 'Alentejo Évora dintorni', country: 'Portogallo', lat: 38.57, lon: -7.91, note: 'i montes con le querce da sughero, il maiale nero' },
    { city: 'Toscana Val di Chiana', country: 'Italia', lat: 43.3, lon: 11.85, note: 'la razza chianina, le fattorie sulla piana' },
    { city: 'Andalusia Jaén', country: 'Spagna', lat: 37.77, lon: -3.79, note: 'il mare di olivi, i cortijos' },
    { city: 'Franconia Baviera', country: 'Germania', lat: 49.75, lon: 10.5, note: 'i masi bavaresi, il luppolo, le birre di fattoria' },
  ],
  'scoperta-urbana': [
    { city: 'San Paolo Beco do Batman dintorni', country: 'Brasile', lat: -23.56, lon: -46.69, note: 'i murales politici della città più grande del Sudamerica' },
    { city: 'Città del Capo Woodstock dintorni', country: 'Sudafrica', lat: -33.93, lon: 18.45, note: 'la scena street art del dopo-apartheid' },
    { city: 'Reykjavik centro', country: 'Islanda', lat: 64.15, lon: -21.94, note: 'i murales della capitale più a nord del mondo' },
    { city: 'Valencia Cabanyal', country: 'Spagna', lat: 39.47, lon: -0.32, note: 'il quartiere dei pescatori diventato galleria a cielo aperto' },
    { city: 'Katowice', country: 'Polonia', lat: 50.26, lon: 19.02, note: 'i murales sulle case minerarie della Slesia' },
  ],
  mare: [
    { city: 'Baleari Cabrera', country: 'Spagna', lat: 39.15, lon: 2.93, note: 'il parco nazionale marino, accesso contingentato' },
    { city: 'Corsica Bonifacio', country: 'Francia', lat: 41.39, lon: 9.16, note: 'le falesie bianche, la Sardegna a vista' },
    { city: 'Grecia Milos dintorni', country: 'Grecia', lat: 36.75, lon: 24.43, note: 'già citata: le spiagge vulcaniche minori' },
    { city: 'Seychelles Praslin', country: 'Seychelles', lat: -4.32, lon: 55.73, note: 'Anse Lazio, la Vallée de Mai con le noci di coco de mer' },
    { city: 'Bahamas Exuma', country: 'Bahamas', lat: 23.53, lon: -75.85, note: 'i maiali che nuotano, l\'acqua turchese' },
    { city: 'Mozambico Bazaruto', country: 'Mozambico', lat: -21.65, lon: 35.47, note: 'l\'arcipelago intatto, le dune di sabbia' },
    { city: 'Thailandia Koh Kood', country: 'Thailandia', lat: 11.65, lon: 102.55, note: 'meno sviluppata di Koh Chang, cascate nella giungla' },
    { city: 'Australia Whitsunday Hamilton', country: 'Australia', lat: -20.36, lon: 148.95, note: 'la base per esplorare l\'arcipelago' },
  ],
  'montagna-estate': [
    { city: 'Pirenei Ordesa dintorni', country: 'Spagna', lat: 42.65, lon: -0.06, note: 'già citata: i sentieri meno battuti del versante spagnolo' },
    { city: 'Alpi Retiche Engadina Bassa', country: 'Svizzera', lat: 46.7, lon: 10.3, note: 'il parco nazionale svizzero, gli stambecchi' },
    { city: 'Tatra Zakopane dintorni', country: 'Polonia', lat: 49.25, lon: 19.93, note: 'i sentieri verso i laghi glaciali' },
    { city: 'Nepal Langtang', country: 'Nepal', lat: 28.2, lon: 85.5, note: 'il trekking meno affollato dell\'Everest, i villaggi tamang' },
    { city: 'Cile Torres del Paine dintorni', country: 'Cile', lat: -51.0, lon: -73.0, note: 'già citata: i sentieri minori del parco' },
    { city: 'Canada Yoho', country: 'Canada', lat: 51.44, lon: -116.49, note: 'i laghi turchesi meno affollati di Banff' },
  ],
  'parchi-tematici': [
    { city: 'Ravensburger Spieleland', country: 'Germania', lat: 47.7, lon: 9.6, note: 'il parco dei giochi da tavolo tedeschi' },
    { city: 'Movie Park Germany', country: 'Germania', lat: 51.6, lon: 6.85, note: 'Bottrop, il cinema come tema, gli studios' },
    { city: 'Bellewaerde', country: 'Belgio', lat: 50.85, lon: 2.92, note: 'Ypres, il parco belga con lo zoo integrato' },
    { city: 'Nigloland', country: 'Francia', lat: 48.32, lon: 4.05, note: 'la Champagne, un parco a misura di famiglia' },
    { city: 'Toverland', country: 'Paesi Bassi', lat: 51.33, lon: 5.98, note: 'il Limburgo, temi fantasy curati' },
    { city: 'Gardaland dintorni Movieland', country: 'Italia', lat: 45.47, lon: 10.68, note: 'già citata: il polo dei parchi sul Garda' },
    { city: 'Beto Carrero dintorni', country: 'Brasile', lat: -26.8, lon: -48.62, note: 'già citata: la Riviera catarinense attorno' },
  ],
};
