// ─────────────────────────────────────────────────────────────────────────
// LIBRERIA ITINERARI — CATALOGO MONDIALE DELLE ZONE
//
// Solo DATI: nessuna logica, nessun import (il modulo è caricato anche dal
// server via import dinamico, e libraryDescriptors.ts lo importa per
// generare i descrittori — niente dipendenze circolari).
//
// Criterio di selezione (regola committente "tutto a livello mondiale"):
//   • le città/aree più visitate al mondo (classifiche Euromonitor Top 100
//     City Destinations e Mastercard Global Destination Cities Index);
//   • le mete più visitate dei tre mercati principali dell'app — Italia,
//     Francia, Spagna — anche quando non entrano in classifica mondiale;
//   • i "luoghi" oltre le città: isole, parchi, aree costiere e distretti
//     turistici che si visitano come una zona sola (Cinque Terre, Cappadocia,
//     Val d'Orcia, Uluru, Plitvice…).
// Sono ESCLUSE le 30 città già presenti in ZONE_CITIES (libraryDescriptors.ts):
// hanno già i loro itinerari 1-2-3 giorni × 8 angoli.
//
// Ogni zona genera 2 durate (2 e 3 giorni) × 8 angoli = 16 itinerari, tutti
// ABBINABILI tra loro sulla stessa zona (vedi il blocco COMBINABILITÀ del
// brief in worldZoneDescriptors()).
//
// coords = centro storico/punto di riferimento della zona, non il centroide
// amministrativo: è la coordinata che il generatore usa come ancora e che la
// verifica in codice confronta con le tappe (tolleranza 30 km).
// ─────────────────────────────────────────────────────────────────────────

export interface WorldZone {
  /** Nome della zona come lo cerca l'utente italiano. */
  c: string;
  /** Paese (in italiano). */
  k: string;
  lat: number;
  lon: number;
  /** Priorità di semina: 1 = mete top mondiali, 2 = alta, 3 = media. */
  t: 1 | 2 | 3;
  /** Una riga di contesto locale vero che entra nel brief del generatore. */
  n: string;
}

export const WORLD_ZONES: WorldZone[] = [
  // ══════════════════════════ ITALIA ══════════════════════════
  // (Roma, Firenze, Venezia, Napoli, Milano, Torino, Bologna, Palermo,
  //  Genova e Verona stanno già in ZONE_CITIES)
  { c: 'Siena', k: 'Italia', lat: 43.32, lon: 11.33, t: 1, n: 'il Campo e il Duomo a pochi passi, ma la città vive per contrade: sali sul Facciatone per capire la forma a Y' },
  { c: 'Pisa', k: 'Italia', lat: 43.72, lon: 10.4, t: 1, n: 'la piazza dei Miracoli è mezza giornata, il resto è una città universitaria vera: Borgo Stretto, i Lungarni, la Vettovaglie' },
  { c: 'Lucca', k: 'Italia', lat: 43.84, lon: 10.5, t: 2, n: 'le mura cinquecentesche si girano in bici in un\'ora e sono il modo giusto di leggere la città; piazza Anfiteatro nasce su un anfiteatro romano' },
  { c: 'San Gimignano', k: 'Italia', lat: 43.47, lon: 11.04, t: 2, n: 'le torri e la Vernaccia: mezza giornata basta per il centro, il bello è dormirci e vederlo svuotato dopo le 18' },
  { c: 'Volterra', k: 'Italia', lat: 43.4, lon: 10.86, t: 3, n: 'etrusca prima che medievale: alabastro, teatro romano e le Balze che franano; distanze brevi ma tutte in salita' },
  { c: 'Val d\'Orcia', k: 'Italia', lat: 43.07, lon: 11.68, t: 1, n: 'Pienza, Montalcino, Bagno Vignoni e i cipressi delle cartoline: si gira in auto, le distanze tra i borghi sono di 20-30 minuti' },
  { c: 'Montepulciano', k: 'Italia', lat: 43.1, lon: 11.78, t: 2, n: 'Nobile e cantine scavate nel tufo sotto i palazzi; il corso è una salita continua fino a piazza Grande' },
  { c: 'Arezzo', k: 'Italia', lat: 43.46, lon: 11.88, t: 3, n: 'la Leggenda della Vera Croce di Piero della Francesca è il motivo del viaggio: prenotazione obbligatoria a fasce orarie' },
  { c: 'Cortona', k: 'Italia', lat: 43.27, lon: 11.99, t: 3, n: 'terrazza sulla Valdichiana, etrusca e rinascimentale; ripida davvero, calzature serie' },
  { c: 'Isola d\'Elba', k: 'Italia', lat: 42.81, lon: 10.32, t: 2, n: 'traghetto da Piombino, auto quasi obbligatoria: spiagge diversissime tra costa nord e sud, e le residenze napoleoniche' },
  { c: 'Viareggio', k: 'Italia', lat: 43.87, lon: 10.25, t: 3, n: 'liberty balneare e Carnevale: la passeggiata è il centro, la pineta e il lago di Massaciuccoli il contraltare tranquillo' },
  { c: 'Carrara', k: 'Italia', lat: 44.08, lon: 10.1, t: 3, n: 'le cave di marmo sopra la città sono l\'attrazione vera (visite guidate in fuoristrada); a valle laboratori e Accademia' },
  { c: 'Livorno', k: 'Italia', lat: 43.55, lon: 10.31, t: 3, n: 'la Venezia Nuova coi fossi da girare in battello, il mercato centrale e il cacciucco; Terrazza Mascagni al tramonto' },
  { c: 'Pistoia', k: 'Italia', lat: 43.93, lon: 10.92, t: 3, n: 'piazza del Duomo severa e sottovalutata, il pulpito di Giovanni Pisano e i vivai tutt\'intorno' },
  { c: 'Maremma', k: 'Italia', lat: 42.76, lon: 11.11, t: 3, n: 'Parco dell\'Uccellina, terme libere di Saturnia, borghi del tufo (Pitigliano, Sovana): auto indispensabile' },
  { c: 'Perugia', k: 'Italia', lat: 43.11, lon: 12.39, t: 2, n: 'acropoli etrusca con scale mobili dentro la Rocca Paolina; corso Vannucci è il salotto, il resto scende ripido' },
  { c: 'Assisi', k: 'Italia', lat: 43.07, lon: 12.62, t: 1, n: 'la Basilica superiore e inferiore con Giotto e Cimabue: silenzio richiesto, spalle coperte; Eremo delle Carceri per il respiro' },
  { c: 'Orvieto', k: 'Italia', lat: 42.72, lon: 12.11, t: 2, n: 'il Duomo con la cappella di Signorelli e la città sotterranea nel tufo; funicolare dalla stazione, niente auto in centro' },
  { c: 'Spoleto', k: 'Italia', lat: 42.74, lon: 12.74, t: 3, n: 'il Ponte delle Torri e la Rocca albornoziana; percorsi meccanizzati che risparmiano 200 metri di dislivello' },
  { c: 'Gubbio', k: 'Italia', lat: 43.35, lon: 12.58, t: 3, n: 'medievale integra e verticale: Palazzo dei Consoli, le Tavole Eugubine, la funivia a gabbia per Sant\'Ubaldo' },
  { c: 'Urbino', k: 'Italia', lat: 43.73, lon: 12.64, t: 3, n: 'Palazzo Ducale e la Città Ideale: rinascimento perfetto in scala ridotta, tutto in salita, città universitaria' },
  { c: 'Ancona', k: 'Italia', lat: 43.62, lon: 13.51, t: 3, n: 'l\'unico porto italiano dove il sole sorge e tramonta sul mare; Duomo sul Guasco, Arco di Traiano, Conero a due passi' },
  { c: 'Ascoli Piceno', k: 'Italia', lat: 42.85, lon: 13.58, t: 3, n: 'piazza del Popolo in travertino e il Caffè Meletti liberty; olive ascolane fritte al momento, non da vetrina' },
  { c: 'Rimini', k: 'Italia', lat: 44.06, lon: 12.57, t: 2, n: 'non solo spiaggia: arco di Augusto, ponte di Tiberio, borgo San Giuliano e la Rimini di Fellini raccontata al Fellini Museum' },
  { c: 'Ravenna', k: 'Italia', lat: 44.42, lon: 12.2, t: 1, n: 'otto siti UNESCO di mosaici bizantini a piedi l\'uno dall\'altro: biglietto cumulativo, Galla Placidia a fasce di 5 minuti' },
  { c: 'Ferrara', k: 'Italia', lat: 44.84, lon: 11.62, t: 3, n: 'città estense da girare in bici, addizione erculea a scacchiera e mura di 9 km percorribili' },
  { c: 'Parma', k: 'Italia', lat: 44.8, lon: 10.33, t: 2, n: 'Correggio in Duomo e nella Camera di San Paolo, il Teatro Farnese in legno; caseifici e prosciuttifici visitabili solo su prenotazione mattutina' },
  { c: 'Modena', k: 'Italia', lat: 44.65, lon: 10.93, t: 2, n: 'Duomo e Ghirlandina UNESCO, mercato Albinelli, acetaie di balsamico tradizionale; i musei Ferrari sono due, in due comuni diversi' },
  { c: 'Padova', k: 'Italia', lat: 45.41, lon: 11.88, t: 2, n: 'Cappella degli Scrovegni con prenotazione e camera di compensazione, Prato della Valle, i caffè sotto i portici' },
  { c: 'Vicenza', k: 'Italia', lat: 45.55, lon: 11.55, t: 3, n: 'città di Palladio: Basilica, Teatro Olimpico e le ville fuori porta (la Rotonda si vede anche solo da fuori)' },
  { c: 'Treviso', k: 'Italia', lat: 45.67, lon: 12.24, t: 3, n: 'canali, mura e osterie da ombra e cicchetto; base perfetta per le colline del Prosecco a mezz\'ora' },
  { c: 'Trieste', k: 'Italia', lat: 45.65, lon: 13.78, t: 2, n: 'mitteleuropea: piazza Unità sul mare, caffè storici con lessico proprio, Miramare e la Risiera come memoria' },
  { c: 'Udine', k: 'Italia', lat: 46.06, lon: 13.24, t: 3, n: 'i Tiepolo in Duomo e nel Palazzo Patriarcale, e il rito del tajut in piazza Matteotti' },
  { c: 'Trento', k: 'Italia', lat: 46.07, lon: 11.12, t: 3, n: 'Concilio e Buonconsiglio, il MUSE di Piano; funivia per Sardagna e Monte Bondone alle spalle' },
  { c: 'Bolzano', k: 'Italia', lat: 46.5, lon: 11.35, t: 2, n: 'bilingue davvero: Ötzi al museo archeologico, portici, tre funivie che partono dalla città verso gli altipiani' },
  { c: 'Merano', k: 'Italia', lat: 46.67, lon: 11.16, t: 3, n: 'terme e passeggiate d\'inverno/d\'estate lungo il Passirio, i Giardini di Castel Trauttmansdorff' },
  { c: 'Cortina d\'Ampezzo', k: 'Italia', lat: 46.54, lon: 12.14, t: 2, n: 'conca dolomitica con Tofane, Cinque Torri e Lago di Braies a un\'ora; d\'estate navette obbligatorie per i laghi' },
  { c: 'Val Gardena', k: 'Italia', lat: 46.58, lon: 11.67, t: 2, n: 'Ortisei, Santa Cristina e Selva; Alpe di Siusi chiusa alle auto di giorno, si sale in cabinovia' },
  { c: 'Bergamo', k: 'Italia', lat: 45.7, lon: 9.67, t: 2, n: 'Città Alta murata (UNESCO) e Città Bassa moderna, unite dalla funicolare; Accademia Carrara di livello europeo' },
  { c: 'Brescia', k: 'Italia', lat: 45.54, lon: 10.22, t: 3, n: 'il parco archeologico romano e Santa Giulia UNESCO, la Vittoria Alata; base per Franciacorta e Garda' },
  { c: 'Mantova', k: 'Italia', lat: 45.16, lon: 10.79, t: 2, n: 'tre laghi artificiali attorno alla città: Palazzo Ducale enorme (Camera degli Sposi su prenotazione) e Palazzo Te di Giulio Romano' },
  { c: 'Cremona', k: 'Italia', lat: 45.13, lon: 10.02, t: 3, n: 'liuteria viva: botteghe visitabili, Museo del Violino con audizioni; il Torrazzo è il campanile in muratura più alto d\'Europa' },
  { c: 'Pavia', k: 'Italia', lat: 45.19, lon: 9.16, t: 3, n: 'Ponte Coperto, università antichissima e la Certosa a 8 km, che vale il viaggio da sola' },
  { c: 'Lago di Como', k: 'Italia', lat: 45.98, lon: 9.26, t: 1, n: 'Bellagio, Varenna e Villa del Balbianello: il battello è il mezzo giusto, la strada costiera è stretta e lentissima' },
  { c: 'Lago di Garda', k: 'Italia', lat: 45.49, lon: 10.61, t: 1, n: 'Sirmione e le Grotte di Catullo a sud, Limone e Malcesine a nord: sponde diverse per carattere e clima' },
  { c: 'Lago Maggiore', k: 'Italia', lat: 45.88, lon: 8.53, t: 2, n: 'Stresa e le Isole Borromee in battello, la funivia del Mottarone; il versante piemontese è quello dei giardini' },
  { c: 'Aosta', k: 'Italia', lat: 45.74, lon: 7.32, t: 3, n: 'Roma delle Alpi: teatro, arco e criptoportico, con i castelli della valle (Fénis, Issogne) a mezz\'ora' },
  { c: 'Courmayeur', k: 'Italia', lat: 45.79, lon: 6.97, t: 3, n: 'la Skyway Monte Bianco è l\'esperienza-chiave (biglietto a orario), Val Ferret e Val Veny per il resto' },
  { c: 'Langhe', k: 'Italia', lat: 44.7, lon: 8.04, t: 1, n: 'Alba, Barolo, La Morra, Grinzane: colline UNESCO, cantine solo su appuntamento, tartufo bianco da ottobre a dicembre' },
  { c: 'Asti', k: 'Italia', lat: 44.9, lon: 8.21, t: 3, n: 'torri medievali e Palio di settembre; base economica per il Monferrato e le sue infernot' },
  { c: 'Sanremo', k: 'Italia', lat: 43.82, lon: 7.78, t: 3, n: 'Casinò liberty, la Pigna medievale sopra il centro e la ciclabile sul vecchio tracciato ferroviario fino a Ospedaletti' },
  { c: 'Cinque Terre', k: 'Italia', lat: 44.15, lon: 9.65, t: 1, n: 'Monterosso, Vernazza, Corniglia, Manarola, Riomaggiore: si collegano in treno ogni 20 minuti, i sentieri richiedono la Card e scarpe vere' },
  { c: 'Portofino', k: 'Italia', lat: 44.3, lon: 9.21, t: 2, n: 'piazzetta minuscola e carissima: il senso è il sentiero per San Fruttuoso e Santa Margherita come base realistica' },
  { c: 'Lerici', k: 'Italia', lat: 44.08, lon: 9.91, t: 3, n: 'Golfo dei Poeti: castello sul mare, Tellaro e San Terenzo, battello per Portovenere' },
  { c: 'Costiera Amalfitana', k: 'Italia', lat: 40.63, lon: 14.6, t: 1, n: 'Amalfi, Positano, Ravello: la SS163 è meravigliosa e infernale, in alta stagione conviene il ferry; Sentiero degli Dei al mattino presto' },
  { c: 'Sorrento', k: 'Italia', lat: 40.63, lon: 14.37, t: 1, n: 'base logistica perfetta: Circumvesuviana per Pompei, aliscafi per Capri, discesa a Marina Grande a piedi' },
  { c: 'Capri', k: 'Italia', lat: 40.55, lon: 14.24, t: 1, n: 'due paesi (Capri e Anacapri), seggiovia del Monte Solaro, Grotta Azzurra solo con mare calmo: verifica prima di partire' },
  { c: 'Ischia', k: 'Italia', lat: 40.73, lon: 13.9, t: 2, n: 'isola termale: parchi termali con biglietto giornaliero, Castello Aragonese, spiaggia di Maronti e fumarole' },
  { c: 'Pompei ed Ercolano', k: 'Italia', lat: 40.75, lon: 14.5, t: 1, n: 'Pompei è enorme e senza ombra, Ercolano è più piccola e meglio conservata: mezza giornata l\'una, acqua e cappello' },
  { c: 'Caserta', k: 'Italia', lat: 41.07, lon: 14.33, t: 3, n: 'la Reggia con il parco di 3 km (navetta o bici) e il Giardino Inglese; San Leucio racconta la seta borbonica' },
  { c: 'Salerno', k: 'Italia', lat: 40.68, lon: 14.77, t: 3, n: 'lungomare palmato, Duomo normanno e Giardino della Minerva; porta d\'ingresso economica alla Costiera' },
  { c: 'Paestum', k: 'Italia', lat: 40.42, lon: 15.01, t: 2, n: 'tre templi dorici tra i meglio conservati al mondo e la Tomba del Tuffatore al museo; bufala campana tutt\'intorno' },
  { c: 'Cilento', k: 'Italia', lat: 40.03, lon: 15.29, t: 3, n: 'Palinuro, Marina di Camerota, grotte marine e il Parco Nazionale: mare pulito e servizi essenziali, auto necessaria' },
  { c: 'Bari', k: 'Italia', lat: 41.12, lon: 16.87, t: 2, n: 'Bari Vecchia con le orecchiette fatte in strada in via Arco Basso, San Nicola meta di pellegrinaggio ortodosso, murat per lo shopping' },
  { c: 'Alberobello', k: 'Italia', lat: 40.78, lon: 17.24, t: 1, n: 'i trulli UNESCO: rione Monti turistico e Aia Piccola più vero; si vede in mezza giornata, la Valle d\'Itria è il resto' },
  { c: 'Polignano a Mare', k: 'Italia', lat: 40.99, lon: 17.22, t: 2, n: 'Lama Monachile tra le falesie, grotte marine in barca, Domenico Modugno di casa; parcheggi difficili d\'estate' },
  { c: 'Ostuni', k: 'Italia', lat: 40.73, lon: 17.58, t: 2, n: 'la città bianca sul colle con vista sugli ulivi secolari fino al mare; centro tutto scale, mare a 8 km' },
  { c: 'Lecce', k: 'Italia', lat: 40.35, lon: 18.17, t: 1, n: 'barocco in pietra leccese che si lavora come burro, anfiteatro romano in piazza, cartapesta ancora artigianale' },
  { c: 'Otranto', k: 'Italia', lat: 40.14, lon: 18.49, t: 2, n: 'il mosaico dell\'Albero della Vita in cattedrale e la cripta dei Martiri; punto più a est d\'Italia a Punta Palascìa' },
  { c: 'Gallipoli', k: 'Italia', lat: 40.06, lon: 17.98, t: 3, n: 'città vecchia su un\'isola collegata da un ponte, frantoi ipogei sotto le case, movida estiva a Baia Verde' },
  { c: 'Gargano', k: 'Italia', lat: 41.88, lon: 16.18, t: 2, n: 'Vieste, Peschici, Foresta Umbra e le Tremiti: falesie e trabucchi, distanze reali maggiori di quanto sembri sulla mappa' },
  { c: 'Matera', k: 'Italia', lat: 40.67, lon: 16.61, t: 1, n: 'Sassi Barisano e Caveoso, chiese rupestri affrescate, Murgia Timone di fronte per la vista; saliscendi continui, scarpe serie' },
  { c: 'Tropea', k: 'Italia', lat: 38.68, lon: 15.9, t: 2, n: 'la rupe con Santa Maria dell\'Isola e la spiaggia sotto; Capo Vaticano e Pizzo (tartufo) nel raggio di 20 minuti' },
  { c: 'Reggio Calabria', k: 'Italia', lat: 38.11, lon: 15.65, t: 3, n: 'i Bronzi di Riace al MArRC e il lungomare che D\'Annunzio disse il più bello d\'Italia, con lo Stretto e l\'Etna di fronte' },
  { c: 'Taormina', k: 'Italia', lat: 37.85, lon: 15.29, t: 1, n: 'Teatro Antico con l\'Etna sullo sfondo, Isola Bella sotto (funivia); carissima e affollatissima da giugno a settembre' },
  { c: 'Catania', k: 'Italia', lat: 37.5, lon: 15.09, t: 2, n: 'barocco di lava nera, la Pescheria che urla al mattino, e l\'Etna raggiungibile in giornata dal Rifugio Sapienza' },
  { c: 'Siracusa', k: 'Italia', lat: 37.06, lon: 15.29, t: 1, n: 'Ortigia è un\'isola nell\'isola (Duomo su un tempio greco, fonte Aretusa), Neapolis con il teatro greco è dall\'altra parte' },
  { c: 'Val di Noto', k: 'Italia', lat: 36.93, lon: 14.73, t: 2, n: 'Ragusa Ibla, Modica, Scicli e Noto: barocco UNESCO ricostruito dopo il 1693, cioccolato modicano, set di Montalbano' },
  { c: 'Agrigento', k: 'Italia', lat: 37.31, lon: 13.58, t: 1, n: 'Valle dei Templi da fare all\'alba o di sera d\'estate (aperture serali), Scala dei Turchi spesso interdetta: verifica prima' },
  { c: 'Cefalù', k: 'Italia', lat: 38.04, lon: 14.02, t: 2, n: 'duomo normanno UNESCO col Cristo Pantocratore, spiaggia in centro, la Rocca sopra con un\'ora di salita' },
  { c: 'Trapani ed Erice', k: 'Italia', lat: 38.02, lon: 12.54, t: 2, n: 'saline con mulini tra Trapani e Marsala, funivia per Erice medievale a 750 m; imbarco per Favignana' },
  { c: 'Isole Eolie', k: 'Italia', lat: 38.47, lon: 14.95, t: 2, n: 'Lipari base, Vulcano e Stromboli per i crateri (con guida obbligatoria), Panarea mondana: gli aliscafi saltano col mare mosso' },
  { c: 'Cagliari', k: 'Italia', lat: 39.22, lon: 9.12, t: 2, n: 'quartiere Castello in alto (ascensori pubblici), il Poetto a 10 minuti e i fenicotteri nello stagno di Molentargius' },
  { c: 'Alghero', k: 'Italia', lat: 40.56, lon: 8.32, t: 2, n: 'catalana per lingua e cognomi, bastioni sul mare, Grotta di Nettuno via mare o 654 gradini della Escala del Cabirol' },
  { c: 'Costa Smeralda', k: 'Italia', lat: 40.92, lon: 9.5, t: 2, n: 'Porto Cervo e le cale della Gallura, La Maddalena in traghetto da Palau; prezzi estivi fuori scala, spiagge libere a nord' },
  { c: 'Sinis e Oristano', k: 'Italia', lat: 39.9, lon: 8.59, t: 3, n: 'Tharros punica sul mare, Is Arutas coi granelli di quarzo (vietato portarli via), Bosa colorata a un\'ora' },
  { c: 'Villasimius', k: 'Italia', lat: 39.14, lon: 9.52, t: 3, n: 'Capo Carbonara e area marina protetta: Punta Molentis, Simius, Porto Giunco; molti parcheggi a pagamento con numero chiuso' },
  { c: 'Tivoli', k: 'Italia', lat: 41.96, lon: 12.8, t: 2, n: 'due UNESCO in un giorno: Villa Adriana enorme e archeologica, Villa d\'Este tutta fontane; 45 minuti da Roma in treno' },
  { c: 'Viterbo', k: 'Italia', lat: 42.42, lon: 12.11, t: 3, n: 'quartiere medievale San Pellegrino e il Palazzo dei Papi; terme libere del Bullicame gratuite e sempre aperte' },
  { c: 'Civita di Bagnoregio', k: 'Italia', lat: 42.63, lon: 12.11, t: 3, n: 'la città che muore, raggiungibile solo dal ponte pedonale a pagamento; mezza giornata, poi lago di Bolsena' },
  { c: 'Sperlonga', k: 'Italia', lat: 41.26, lon: 13.43, t: 3, n: 'borgo bianco a picco e la villa di Tiberio con la grotta e il museo dei gruppi scultorei; spiagge lunghe ai due lati' },
  { c: 'L\'Aquila', k: 'Italia', lat: 42.35, lon: 13.4, t: 3, n: 'ricostruzione post-sisma ancora in corso e visibile: Basilica di Collemaggio restituita, Gran Sasso alle spalle' },
  { c: 'Sulmona', k: 'Italia', lat: 42.05, lon: 13.93, t: 3, n: 'acquedotto medievale in piazza Garibaldi, confetti da sette generazioni, Majella per gli eremi di Celestino' },
  { c: 'Pescara', k: 'Italia', lat: 42.46, lon: 14.21, t: 3, n: 'città balneare moderna con il ponte del mare e la casa di D\'Annunzio; base per la Costa dei Trabocchi in bici' },
  { c: 'Benevento', k: 'Italia', lat: 41.13, lon: 14.78, t: 3, n: 'Arco di Traiano intatto e Santa Sofia longobarda UNESCO; il Sannio del Falanghina tutt\'intorno' },
  // ══════════════════════════ FRANCIA ══════════════════════════
  { c: 'Nizza', k: 'Francia', lat: 43.7, lon: 7.27, t: 1, n: 'Promenade des Anglais, Vieux Nice col mercato dei fiori e Cimiez con Matisse e Chagall; spiagge di ciottoli, scarpette utili' },
  { c: 'Cannes', k: 'Francia', lat: 43.55, lon: 7.02, t: 2, n: 'la Croisette e il Suquet vecchio sopra il porto; le Isole di Lérins in 15 minuti di battello cambiano completamente la giornata' },
  { c: 'Antibes', k: 'Francia', lat: 43.58, lon: 7.13, t: 3, n: 'mura sul mare, museo Picasso nel Château Grimaldi, mercato provenzale coperto; Juan-les-Pins per la sera' },
  { c: 'Saint-Tropez', k: 'Francia', lat: 43.27, lon: 6.64, t: 3, n: 'porto delle celebrità e la Ponche autentica dietro; le spiagge vere sono a Pampelonne, 5 km fuori, e si paga tutto' },
  { c: 'Marsiglia', k: 'Francia', lat: 43.3, lon: 5.37, t: 1, n: 'Vieux-Port, Panier e MuCEM; le Calanques si raggiungono in barca o a piedi con accessi contingentati d\'estate' },
  { c: 'Aix-en-Provence', k: 'Francia', lat: 43.53, lon: 5.45, t: 2, n: 'cours Mirabeau, fontane e mercati quotidiani; l\'atelier di Cézanne e la Sainte-Victoire che dipingeva' },
  { c: 'Avignone', k: 'Francia', lat: 43.95, lon: 4.81, t: 2, n: 'Palazzo dei Papi gigantesco e il ponte incompiuto; a luglio il festival raddoppia i prezzi e riempie tutto' },
  { c: 'Arles', k: 'Francia', lat: 43.68, lon: 4.63, t: 2, n: 'anfiteatro romano ancora in uso, i luoghi di Van Gogh segnalati per strada, Camargue con fenicotteri a mezz\'ora' },
  { c: 'Nîmes', k: 'Francia', lat: 43.84, lon: 4.36, t: 3, n: 'l\'arena romana meglio conservata di Francia e la Maison Carrée; Pont du Gard a 25 km' },
  { c: 'Montpellier', k: 'Francia', lat: 43.61, lon: 3.88, t: 3, n: 'universitaria e giovane: Écusson medievale pedonale, tram colorati, spiagge a 20 minuti a Palavas' },
  { c: 'Carcassonne', k: 'Francia', lat: 43.21, lon: 2.35, t: 2, n: 'la Cité murata restaurata da Viollet-le-Duc: dormirci dentro cambia tutto, di giorno è un flusso continuo' },
  { c: 'Tolosa', k: 'Francia', lat: 43.6, lon: 1.44, t: 2, n: 'la ville rose in mattoni, Saint-Sernin romanica, la Cité de l\'Espace e il Canal du Midi' },
  { c: 'Bordeaux', k: 'Francia', lat: 44.84, lon: -0.58, t: 1, n: 'Port de la Lune UNESCO, Miroir d\'eau, Cité du Vin; Saint-Émilion in treno in 40 minuti' },
  { c: 'Biarritz', k: 'Francia', lat: 43.48, lon: -1.56, t: 3, n: 'surf e Belle Époque basca, Rocher de la Vierge; Bayonne e Saint-Jean-de-Luz completano il triangolo' },
  { c: 'Saint-Malo', k: 'Francia', lat: 48.65, lon: -2.03, t: 2, n: 'città corsara murata, maree tra le più ampie d\'Europa: controlla gli orari per le isole raggiungibili a piedi' },
  { c: 'Mont-Saint-Michel', k: 'Francia', lat: 48.64, lon: -1.51, t: 1, n: 'navetta obbligatoria dai parcheggi, abbazia in cima a 350 gradini; le grandi maree sono l\'evento da programmare' },
  { c: 'Rennes', k: 'Francia', lat: 48.11, lon: -1.68, t: 3, n: 'case a graticcio, il mercato des Lices il sabato (il secondo di Francia), studenti ovunque' },
  { c: 'Nantes', k: 'Francia', lat: 47.22, lon: -1.55, t: 3, n: 'le Macchine dell\'Isola con l\'elefante meccanico, castello dei duchi di Bretagna, percorso urbano della Linea Verde' },
  { c: 'La Rochelle', k: 'Francia', lat: 46.16, lon: -1.15, t: 3, n: 'le tre torri del porto vecchio, acquario tra i migliori d\'Europa, Île de Ré in bici via ponte' },
  { c: 'Lione', k: 'Francia', lat: 45.76, lon: 4.83, t: 1, n: 'Vieux Lyon rinascimentale coi traboules, Fourvière in funicolare, bouchons per mangiare; capitale gastronomica dichiarata' },
  { c: 'Annecy', k: 'Francia', lat: 45.9, lon: 6.13, t: 2, n: 'canali e lago alpino balneabile, giro del lago in bici su pista dedicata di 40 km' },
  { c: 'Chamonix', k: 'Francia', lat: 45.92, lon: 6.87, t: 2, n: 'Aiguille du Midi a 3842 m (biglietto a orario, vestiti pesanti anche ad agosto) e Mer de Glace col trenino' },
  { c: 'Strasburgo', k: 'Francia', lat: 48.58, lon: 7.75, t: 1, n: 'cattedrale con orologio astronomico, Petite France a graticcio, istituzioni europee; mercatino di Natale storico' },
  { c: 'Colmar', k: 'Francia', lat: 48.08, lon: 7.36, t: 2, n: 'la piccola Venezia alsaziana e l\'Altare di Issenheim al museo Unterlinden; strada dei vini alsaziana tutt\'intorno' },
  { c: 'Digione e Beaune', k: 'Francia', lat: 47.32, lon: 5.04, t: 3, n: 'il percorso della civetta a Digione e gli Hospices di Beaune col tetto smaltato; Côte d\'Or in mezzo' },
  { c: 'Reims', k: 'Francia', lat: 49.26, lon: 4.03, t: 2, n: 'cattedrale delle incoronazioni e cantine di champagne visitabili sotto la città (prenotazione obbligatoria)' },
  { c: 'Rouen', k: 'Francia', lat: 49.44, lon: 1.1, t: 3, n: 'la cattedrale dipinta da Monet a ogni ora, il Gros-Horloge e il luogo del rogo di Giovanna d\'Arco' },
  { c: 'Honfleur', k: 'Francia', lat: 49.42, lon: 0.23, t: 3, n: 'il Vieux Bassin dipinto dagli impressionisti e la chiesa in legno di Santa Caterina; Deauville a 15 km' },
  { c: 'Lille', k: 'Francia', lat: 50.63, lon: 3.06, t: 3, n: 'fiamminga di mattoni, Vieux-Lille per le birrerie, Palais des Beaux-Arts secondo solo al Louvre' },
  { c: 'Castelli della Loira', k: 'Francia', lat: 47.41, lon: 0.98, t: 1, n: 'Chambord, Chenonceau, Amboise e Villandry: auto o bici sulla Loire à Vélo, due castelli al giorno è già tanto' },
  { c: 'Versailles', k: 'Francia', lat: 48.8, lon: 2.13, t: 1, n: 'reggia, Trianon e Hameau della regina: giornata piena, biglietto a orario, giochi d\'acqua solo in certi giorni' },
  { c: 'Ajaccio', k: 'Francia', lat: 41.93, lon: 8.74, t: 3, n: 'casa natale di Napoleone e museo Fesch; Isole Sanguinarie al tramonto e Calanques di Piana a un\'ora e mezza' },
  { c: 'Bonifacio', k: 'Francia', lat: 41.39, lon: 9.16, t: 3, n: 'cittadella sulle falesie calcaree, scala del Re d\'Aragona, gite alle Lavezzi; Sardegna visibile a occhio nudo' },
  { c: 'Principato di Monaco', k: 'Monaco', lat: 43.73, lon: 7.42, t: 2, n: 'Rocca col cambio della guardia alle 11:55, Casinò, Museo Oceanografico; ascensori pubblici gratuiti per i dislivelli' },
  // ══════════════════════════ SPAGNA ══════════════════════════
  { c: 'Siviglia', k: 'Spagna', lat: 37.39, lon: -5.99, t: 1, n: 'Alcázar e Cattedrale da prenotare con settimane di anticipo, Triana e Santa Cruz a piedi; d\'estate si vive dalle 20 in poi' },
  { c: 'Granada', k: 'Spagna', lat: 37.18, lon: -3.6, t: 1, n: 'Alhambra con biglietto nominativo e fascia oraria per i Nasridi, Albaicín e Sacromonte per il tramonto e il flamenco vero' },
  { c: 'Cordova', k: 'Spagna', lat: 37.89, lon: -4.78, t: 1, n: 'Mezquita-Cattedrale (gratis presto al mattino), Judería e i patii fioriti; a maggio il festival dei cortili riempie tutto' },
  { c: 'Malaga', k: 'Spagna', lat: 36.72, lon: -4.42, t: 2, n: 'Alcazaba e teatro romano affiancati, Picasso di casa, spiagge urbane della Malagueta; base per tutta la Costa del Sol' },
  { c: 'Ronda', k: 'Spagna', lat: 36.74, lon: -5.16, t: 2, n: 'il Puente Nuevo sulla gola del Tajo e la plaza de toros più antica; si vede in un giorno, i pueblos blancos completano' },
  { c: 'Cadice', k: 'Spagna', lat: 36.53, lon: -6.29, t: 3, n: 'quasi un\'isola: mercato centrale, torre Tavira con camera oscura, tramonti sull\'Atlantico e Carnevale famosissimo' },
  { c: 'Marbella', k: 'Spagna', lat: 36.51, lon: -4.89, t: 3, n: 'casco antiguo sorprendentemente autentico dietro il lusso di Puerto Banús; spiagge attrezzate a pagamento' },
  { c: 'Valencia', k: 'Spagna', lat: 39.47, lon: -0.38, t: 1, n: 'Ciudad de las Artes di Calatrava, Mercado Central modernista, il letto del Turia trasformato in parco di 9 km; paella vera all\'Albufera' },
  { c: 'Alicante', k: 'Spagna', lat: 38.35, lon: -0.48, t: 3, n: 'castello di Santa Bárbara con ascensore nella roccia, Explanada e barrio; Tabarca in barca' },
  { c: 'Bilbao', k: 'Spagna', lat: 43.26, lon: -2.93, t: 2, n: 'Guggenheim e casco viejo con i pintxos delle Siete Calles; funicolare di Artxanda per la vista' },
  { c: 'San Sebastián', k: 'Spagna', lat: 43.32, lon: -1.98, t: 1, n: 'la Concha, Parte Vieja con la maggior densità di stelle Michelin d\'Europa, Monte Igueldo col funicolare storico' },
  { c: 'Santander', k: 'Spagna', lat: 43.46, lon: -3.81, t: 3, n: 'Palacio de la Magdalena, Centro Botín di Piano, spiagge del Sardinero; Comillas e Santillana del Mar vicine' },
  { c: 'Oviedo', k: 'Spagna', lat: 43.36, lon: -5.84, t: 3, n: 'preromanico asturiano UNESCO sul Naranco, sidrerie con la spillatura da un metro, cammino primitivo' },
  { c: 'Santiago de Compostela', k: 'Spagna', lat: 42.88, lon: -8.54, t: 1, n: 'arrivo dei pellegrini in Obradoiro, messa e botafumeiro solo in certi giorni, mercato di Abastos' },
  { c: 'Vigo e Rías Baixas', k: 'Spagna', lat: 42.24, lon: -8.72, t: 3, n: 'ostriche in rúa Pescadería, isole Cíes con permesso a numero chiuso, albariño nelle cantine del Salnés' },
  { c: 'Salamanca', k: 'Spagna', lat: 40.97, lon: -5.66, t: 2, n: 'plaza Mayor barocca e l\'università con la rana da trovare in facciata; città di studenti, viva fino a tardi' },
  { c: 'Segovia', k: 'Spagna', lat: 40.95, lon: -4.12, t: 2, n: 'acquedotto romano senza malta, Alcázar da fiaba e cochinillo tagliato col piatto; 30 minuti da Madrid in AVE' },
  { c: 'Toledo', k: 'Spagna', lat: 39.86, lon: -4.02, t: 1, n: 'tre culture in pietra: cattedrale, sinagoghe, moschea del Cristo de la Luz; El Greco ovunque, salite continue' },
  { c: 'Cuenca', k: 'Spagna', lat: 40.07, lon: -2.13, t: 3, n: 'le case sospese sulla gola e il museo di arte astratta dentro; ponte di San Pablo per la vista classica' },
  { c: 'Saragozza', k: 'Spagna', lat: 41.65, lon: -0.89, t: 3, n: 'Basilica del Pilar sull\'Ebro, Aljafería islamica, tapas nel Tubo; a metà strada tra Madrid e Barcellona in AVE' },
  { c: 'Pamplona', k: 'Spagna', lat: 42.81, lon: -1.65, t: 3, n: 'il percorso dell\'encierro si cammina tutto l\'anno in 15 minuti; a luglio San Fermín è un\'altra città' },
  { c: 'Maiorca', k: 'Spagna', lat: 39.57, lon: 2.65, t: 1, n: 'Palma con la cattedrale sul mare, Serra de Tramuntana UNESCO in auto o col trenino di Sóller, cale a nord-est' },
  { c: 'Ibiza', k: 'Spagna', lat: 38.91, lon: 1.43, t: 2, n: 'Dalt Vila murata UNESCO e il mercato hippy; l\'isola ha anche cale silenziose a nord, non solo club' },
  { c: 'Minorca', k: 'Spagna', lat: 39.89, lon: 4.27, t: 3, n: 'la più quieta delle Baleari: Camí de Cavalls attorno all\'isola, Mahón e Ciutadella agli estremi, cale a piedi' },
  { c: 'Tenerife', k: 'Spagna', lat: 28.47, lon: -16.25, t: 1, n: 'Teide col permesso separato per il cratere, Anaga di foresta primordiale, La Laguna UNESCO; due climi tra nord e sud' },
  { c: 'Gran Canaria', k: 'Spagna', lat: 28.12, lon: -15.43, t: 2, n: 'dune di Maspalomas, Las Palmas con la casa di Colombo, Roque Nublo al centro; continente in miniatura' },
  { c: 'Lanzarote', k: 'Spagna', lat: 28.96, lon: -13.55, t: 2, n: 'vulcani di Timanfaya e le opere di César Manrique (Jameos del Agua, Mirador del Río) che sono l\'identità dell\'isola' },
  { c: 'Fuerteventura', k: 'Spagna', lat: 28.5, lon: -13.86, t: 3, n: 'spiagge lunghissime e vento costante: Corralejo, Cofete, Isla de Lobos; poco altro, ed è il punto' },
  { c: 'Girona', k: 'Spagna', lat: 41.98, lon: 2.82, t: 3, n: 'case sull\'Onyar, call ebraico tra i meglio conservati d\'Europa, scalinata della cattedrale nota per Il Trono di Spade' },
  { c: 'Sitges', k: 'Spagna', lat: 41.24, lon: 1.81, t: 3, n: 'diciassette spiagge, modernismo di Santiago Rusiñol e vita notturna LGBTQ+ storica; 40 minuti da Barcellona in treno' },
  { c: 'Tarragona', k: 'Spagna', lat: 41.12, lon: 1.25, t: 3, n: 'anfiteatro romano sul mare, foro e circo UNESCO, Balcó del Mediterrani; PortAventura a 10 minuti' },
  // ══════════════════════════ PORTOGALLO ══════════════════════════
  { c: 'Porto', k: 'Portogallo', lat: 41.15, lon: -8.61, t: 1, n: 'Ribeira e le cantine di Vila Nova de Gaia sull\'altra sponda, libreria Lello a pagamento, azulejos di São Bento' },
  { c: 'Sintra', k: 'Portogallo', lat: 38.8, lon: -9.39, t: 1, n: 'Pena, Quinta da Regaleira e Castelo dos Mouros: biglietti a orario e navette, i palazzi sono lontani tra loro' },
  { c: 'Algarve', k: 'Portogallo', lat: 37.1, lon: -8.67, t: 1, n: 'Lagos, Ponta da Piedade e le grotte di Benagil in barca (solo con mare calmo); Sagres per la fine del mondo' },
  { c: 'Coimbra', k: 'Portogallo', lat: 40.21, lon: -8.43, t: 3, n: 'la biblioteca Joanina con i pipistrelli che proteggono i libri, fado di Coimbra maschile e diverso da quello di Lisbona' },
  { c: 'Évora', k: 'Portogallo', lat: 38.57, lon: -7.91, t: 3, n: 'tempio romano, cappella delle ossa e Alentejo attorno: vino, sughero e silenzio' },
  { c: 'Madeira', k: 'Portogallo', lat: 32.65, lon: -16.91, t: 2, n: 'levadas per camminare in orizzontale, Funchal col mercato e la teleferica, Pico do Arieiro all\'alba' },
  { c: 'Azzorre', k: 'Portogallo', lat: 37.74, lon: -25.67, t: 2, n: 'São Miguel: Sete Cidades, Furnas col cozido cotto nella terra, whale watching da aprile a ottobre' },
  // ══════════════════════════ REGNO UNITO E IRLANDA ══════════════════════════
  { c: 'Edimburgo', k: 'Regno Unito', lat: 55.95, lon: -3.19, t: 1, n: 'Royal Mile tra castello e Holyrood, New Town georgiana, Arthur\'s Seat in un\'ora; ad agosto il Fringe raddoppia i prezzi' },
  { c: 'Glasgow', k: 'Regno Unito', lat: 55.86, lon: -4.25, t: 3, n: 'Mackintosh e vittoriano industriale, musei gratuiti (Kelvingrove, Riverside), scena musicale la sera' },
  { c: 'Highlands', k: 'Regno Unito', lat: 57.48, lon: -4.22, t: 2, n: 'Inverness base per Loch Ness, Glencoe e Skye; distanze lunghe su strade a corsia unica con piazzole di scambio' },
  { c: 'York', k: 'Regno Unito', lat: 53.96, lon: -1.08, t: 2, n: 'mura romane e medievali percorribili, Minster gotico, Shambles strettissima; vichinghi al Jorvik' },
  { c: 'Bath', k: 'Regno Unito', lat: 51.38, lon: -2.36, t: 2, n: 'terme romane e crescent georgiani in pietra dorata; Stonehenge a un\'ora, Cotswolds appena a nord' },
  { c: 'Oxford', k: 'Regno Unito', lat: 51.75, lon: -1.26, t: 2, n: 'college visitabili a orari propri (Christ Church, Bodleian), pub letterari; punting sul Cherwell d\'estate' },
  { c: 'Cambridge', k: 'Regno Unito', lat: 52.21, lon: 0.12, t: 2, n: 'King\'s College Chapel e i Backs, punting con o senza barcaiolo; più raccolta e ciclabile di Oxford' },
  { c: 'Liverpool', k: 'Regno Unito', lat: 53.41, lon: -2.98, t: 3, n: 'Albert Dock, Beatles Story e Cavern Club; due cattedrali agli estremi della stessa via' },
  { c: 'Manchester', k: 'Regno Unito', lat: 53.48, lon: -2.24, t: 3, n: 'industriale riconvertita: Northern Quarter, Science and Industry Museum, i due stadi come pellegrinaggio' },
  { c: 'Brighton', k: 'Regno Unito', lat: 50.82, lon: -0.14, t: 3, n: 'Royal Pavilion orientaleggiante, Lanes per i negozietti, molo vittoriano; un\'ora da Londra' },
  { c: 'Cotswolds', k: 'Regno Unito', lat: 51.88, lon: -1.76, t: 2, n: 'Bourton, Bibury, Stow: villaggi di pietra dorata a 20 minuti l\'uno dall\'altro, auto necessaria, bus rari' },
  { c: 'Lake District', k: 'Regno Unito', lat: 54.38, lon: -2.91, t: 2, n: 'Windermere e Keswick come basi, battelli sui laghi, case di Wordsworth e Beatrix Potter; piove spesso, mettilo in conto' },
  { c: 'Cardiff', k: 'Regno Unito', lat: 51.48, lon: -3.18, t: 3, n: 'castello nel centro, Cardiff Bay riconvertita e il Principality Stadium; castelli gallesi a corona attorno' },
  { c: 'Belfast', k: 'Regno Unito', lat: 54.6, lon: -5.93, t: 3, n: 'Titanic Quarter, murales politici coi black taxi tour; Selciato del Gigante a un\'ora e mezza' },
  { c: 'Dublino', k: 'Irlanda', lat: 53.35, lon: -6.26, t: 1, n: 'Book of Kells al Trinity, Guinness Storehouse, Temple Bar carissimo; i musei nazionali sono gratuiti' },
  { c: 'Galway', k: 'Irlanda', lat: 53.27, lon: -9.05, t: 2, n: 'musica dal vivo nei pub ogni sera, Latin Quarter; Scogliere di Moher e Connemara in giornata' },
  { c: 'Cork', k: 'Irlanda', lat: 51.9, lon: -8.47, t: 3, n: 'English Market storico, Blarney Castle con la pietra dell\'eloquenza, Kinsale gastronomica sulla costa' },
  // ══════════════════════════ GERMANIA, AUSTRIA, SVIZZERA ══════════════════════════
  { c: 'Monaco di Baviera', k: 'Germania', lat: 48.14, lon: 11.58, t: 1, n: 'Marienplatz col carillon, Englischer Garten col surf sull\'Eisbach, birrerie storiche; a fine settembre l\'Oktoberfest cambia tutto' },
  { c: 'Amburgo', k: 'Germania', lat: 53.55, lon: 9.99, t: 2, n: 'Speicherstadt UNESCO in mattoni, Elbphilharmonie con plaza gratuita, mercato del pesce la domenica all\'alba' },
  { c: 'Colonia', k: 'Germania', lat: 50.94, lon: 6.96, t: 2, n: 'il Duomo appena fuori dalla stazione (533 gradini in cima), birrerie di Kölsch nei bicchierini da 20 cl' },
  { c: 'Francoforte', k: 'Germania', lat: 50.11, lon: 8.68, t: 3, n: 'skyline e Römer ricostruito, Museumsufer con dodici musei in fila; Apfelwein a Sachsenhausen' },
  { c: 'Dresda', k: 'Germania', lat: 51.05, lon: 13.74, t: 2, n: 'Zwinger, Frauenkirche ricostruita coi materiali originali e la Terrazza di Brühl; Svizzera sassone a mezz\'ora' },
  { c: 'Norimberga', k: 'Germania', lat: 49.45, lon: 11.08, t: 3, n: 'castello imperiale, luoghi del processo e del regime raccontati senza sconti, mercatino di Natale storico' },
  { c: 'Heidelberg', k: 'Germania', lat: 49.41, lon: 8.69, t: 3, n: 'castello in rovina sopra il Neckar, l\'università più antica di Germania e il Philosophenweg per la vista' },
  { c: 'Romantische Strasse', k: 'Germania', lat: 49.38, lon: 10.19, t: 3, n: 'Rothenburg ob der Tauber murata, Dinkelsbühl e Würzburg: si percorre in auto, tappe da mezza giornata' },
  { c: 'Berchtesgaden', k: 'Germania', lat: 47.63, lon: 13.0, t: 3, n: 'Königssee coi battelli elettrici e l\'eco della tromba, Nido dell\'Aquila raggiungibile solo con bus autorizzati' },
  { c: 'Lipsia', k: 'Germania', lat: 51.34, lon: 12.37, t: 3, n: 'Bach alla Thomaskirche, la rivoluzione pacifica dell\'89 alla Nikolaikirche, Spinnerei per l\'arte contemporanea' },
  { c: 'Salisburgo', k: 'Austria', lat: 47.8, lon: 13.04, t: 1, n: 'fortezza in funicolare, casa di Mozart, Mirabell dei Sound of Music; Hallstatt e le miniere di sale in giornata' },
  { c: 'Innsbruck', k: 'Austria', lat: 47.27, lon: 11.39, t: 2, n: 'Tettuccio d\'Oro e Nordkette raggiungibile in 20 minuti dal centro con la funicolare di Hadid' },
  { c: 'Hallstatt', k: 'Austria', lat: 47.56, lon: 13.65, t: 2, n: 'villaggio-cartolina saturo di visitatori a mezzogiorno: dormirci o arrivare presto, miniera di sale più antica del mondo' },
  { c: 'Graz', k: 'Austria', lat: 47.07, lon: 15.44, t: 3, n: 'Schlossberg con ascensore nella roccia, Kunsthaus a forma di alieno, città universitaria e gastronomica' },
  { c: 'Zurigo', k: 'Svizzera', lat: 47.37, lon: 8.54, t: 2, n: 'Altstadt e Bahnhofstrasse carissima, bagni pubblici sul lago e sulla Limmat d\'estate, Uetliberg per la vista' },
  { c: 'Ginevra', k: 'Svizzera', lat: 46.2, lon: 6.14, t: 3, n: 'Jet d\'Eau, quartiere delle Nazioni, CERN a Meyrin con prenotazione; il lago si gira in battello' },
  { c: 'Lucerna', k: 'Svizzera', lat: 47.05, lon: 8.31, t: 2, n: 'Kapellbrücke in legno, Leone morente, e le due montagne di casa: Pilatus e Rigi con treni a cremagliera' },
  { c: 'Interlaken', k: 'Svizzera', lat: 46.69, lon: 7.86, t: 2, n: 'base per Jungfraujoch (costoso, controlla il meteo prima), Lauterbrunnen delle 72 cascate e Grindelwald' },
  { c: 'Zermatt', k: 'Svizzera', lat: 46.02, lon: 7.75, t: 2, n: 'senz\'auto: si arriva col trenino da Täsch; Cervino dal Gornergrat, Matterhorn Glacier Paradise a 3883 m' },
  { c: 'Berna', k: 'Svizzera', lat: 46.95, lon: 7.45, t: 3, n: 'centro UNESCO con 6 km di portici, Zytglogge, fossa degli orsi e bagno nell\'Aare che attraversa la città' },
  { c: 'Lugano', k: 'Svizzera', lat: 46.0, lon: 8.95, t: 3, n: 'italiana di lingua e svizzera di ordine: LAC, Monte Brè e San Salvatore in funicolare, Gandria sul lago' },
  { c: 'St. Moritz', k: 'Svizzera', lat: 46.5, lon: 9.84, t: 3, n: 'Engadina di lusso, ma il Bernina Express e i laghi ghiacciati valgono anche senza spendere in hotel' },
  // ══════════════════════════ BENELUX E NORDICI ══════════════════════════
  { c: 'Bruges', k: 'Belgio', lat: 51.21, lon: 3.22, t: 1, n: 'centro medievale UNESCO da girare a piedi e in barca sui canali, Beghinaggio silenzioso, birrerie trappiste' },
  { c: 'Gand', k: 'Belgio', lat: 51.05, lon: 3.72, t: 2, n: 'l\'Agnello Mistico dei Van Eyck restaurato, Graslei sull\'acqua, città universitaria molto più viva di Bruges' },
  { c: 'Bruxelles', k: 'Belgio', lat: 50.85, lon: 4.35, t: 2, n: 'Grand-Place e Art Nouveau di Horta, percorso dei fumetti sui muri, quartiere europeo; birre e cozze ovunque' },
  { c: 'Anversa', k: 'Belgio', lat: 51.22, lon: 4.4, t: 3, n: 'Rubens di casa, stazione centrale tra le più belle d\'Europa, distretto dei diamanti e moda d\'avanguardia' },
  { c: 'Rotterdam', k: 'Paesi Bassi', lat: 51.92, lon: 4.48, t: 3, n: 'ricostruita moderna: case cubiche, Markthal, Erasmusbrug; Kinderdijk coi mulini UNESCO in battello' },
  { c: 'L\'Aia', k: 'Paesi Bassi', lat: 52.08, lon: 4.31, t: 3, n: 'Mauritshuis con la Ragazza col turbante, Binnenhof politico, spiaggia di Scheveningen col tram' },
  { c: 'Utrecht', k: 'Paesi Bassi', lat: 52.09, lon: 5.12, t: 3, n: 'canali a doppio livello con le cantine trasformate in caffè, Dom da salire, città di biciclette e studenti' },
  { c: 'Lussemburgo', k: 'Lussemburgo', lat: 49.61, lon: 6.13, t: 3, n: 'casematte del Bock scavate nella roccia, città alta e bassa collegate da ascensore; trasporti pubblici gratuiti in tutto il Paese' },
  { c: 'Copenaghen', k: 'Danimarca', lat: 55.68, lon: 12.57, t: 1, n: 'Nyhavn, Tivoli, Christiania e Refshaleøen con lo street food; tutto in bici, piste separate ovunque' },
  { c: 'Stoccolma', k: 'Svezia', lat: 59.33, lon: 18.07, t: 1, n: 'quattordici isole: Gamla Stan, il Vasa recuperato intero, Fotografiska; arcipelago in battello d\'estate' },
  { c: 'Oslo', k: 'Norvegia', lat: 59.91, lon: 10.75, t: 2, n: 'Opera su cui si cammina, Museo Munch, navi vichinghe; carissima, tanti musei con biglietto unico' },
  { c: 'Bergen', k: 'Norvegia', lat: 60.39, lon: 5.32, t: 2, n: 'Bryggen anseatica in legno, funicolare del Fløyen, mercato del pesce; porta d\'accesso ai fiordi' },
  { c: 'Tromsø', k: 'Norvegia', lat: 69.65, lon: 18.96, t: 2, n: 'aurora boreale da settembre a marzo (serve uscire dalla città), sole di mezzanotte a giugno, cattedrale artica' },
  { c: 'Lofoten', k: 'Norvegia', lat: 68.23, lon: 14.56, t: 3, n: 'Svolvær, Reine e Henningsvær: villaggi di pescatori rossi, rorbu come alloggio, auto indispensabile' },
  { c: 'Stavanger', k: 'Norvegia', lat: 58.97, lon: 5.73, t: 3, n: 'Gamle Stavanger in legno bianco e il Preikestolen: 4 ore di cammino andata e ritorno, non banale' },
  { c: 'Helsinki', k: 'Finlandia', lat: 60.17, lon: 24.94, t: 2, n: 'design district, Temppeliaukio scavata nella roccia, Suomenlinna in traghetto col biglietto urbano; sauna pubblica obbligatoria' },
  { c: 'Rovaniemi', k: 'Finlandia', lat: 66.5, lon: 25.73, t: 2, n: 'villaggio di Babbo Natale sul Circolo Polare, husky e renne, aurora; d\'inverno buio quasi tutto il giorno' },
  { c: 'Reykjavík', k: 'Islanda', lat: 64.15, lon: -21.94, t: 1, n: 'base per il Circolo d\'Oro e la costa sud; Blue Lagoon da prenotare, piscine geotermiche di quartiere molto più economiche' },
  { c: 'Göteborg', k: 'Svezia', lat: 57.71, lon: 11.97, t: 3, n: 'canali olandesi, Liseberg il parco più grande di Scandinavia, arcipelago meridionale senz\'auto in battello' },
  { c: 'Aarhus', k: 'Danimarca', lat: 56.16, lon: 10.2, t: 3, n: 'ARoS con l\'arcobaleno panoramico sul tetto, Den Gamle By come città-museo abitata' },
  // ══════════════════════════ EUROPA CENTRO-ORIENTALE E BALCANI ══════════════════════════
  { c: 'Cracovia', k: 'Polonia', lat: 50.06, lon: 19.94, t: 1, n: 'Rynek enorme, Wawel, Kazimierz ebraico; Auschwitz-Birkenau a 70 km va prenotato e affrontato con tempo e rispetto' },
  { c: 'Varsavia', k: 'Polonia', lat: 52.23, lon: 21.01, t: 2, n: 'centro storico ricostruito identico dopo il 1945, museo dell\'Insurrezione, POLIN; grattacieli e blocchi socialisti insieme' },
  { c: 'Danzica', k: 'Polonia', lat: 54.35, lon: 18.65, t: 2, n: 'Długi Targ hanseatica, museo della Seconda Guerra Mondiale, Solidarność ai cantieri; Sopot e le spiagge baltiche vicine' },
  { c: 'Breslavia', k: 'Polonia', lat: 51.11, lon: 17.03, t: 3, n: 'isole e ponti sull\'Oder, centinaia di gnomi di bronzo da cercare, Hala Stulecia UNESCO' },
  { c: 'Zagabria', k: 'Croazia', lat: 45.81, lon: 15.98, t: 3, n: 'città alta e bassa unite dalla funicolare più corta del mondo, mercato di Dolac, museo delle relazioni finite' },
  { c: 'Dubrovnik', k: 'Croazia', lat: 42.65, lon: 18.09, t: 1, n: 'giro delle mura al mattino presto (poi c\'è coda e caldo), funivia sul Srđ, Lokrum in barca; navi da crociera dettano l\'affollamento' },
  { c: 'Spalato', k: 'Croazia', lat: 43.51, lon: 16.44, t: 2, n: 'la città vive dentro il Palazzo di Diocleziano, non accanto; Marjan per il verde, traghetti per Hvar e Brač' },
  { c: 'Laghi di Plitvice', k: 'Croazia', lat: 44.88, lon: 15.62, t: 2, n: 'sedici laghi collegati da passerelle: percorsi a lettera, biglietto a fascia oraria, vietato uscire dai sentieri' },
  { c: 'Zara', k: 'Croazia', lat: 44.12, lon: 15.23, t: 3, n: 'organo del mare e saluto al sole sul lungomare, foro romano; Kornati e Krka in giornata' },
  { c: 'Rovigno', k: 'Croazia', lat: 45.08, lon: 13.64, t: 3, n: 'Istria veneziana e bilingue: centro su un promontorio, tartufo e olio nell\'entroterra, Pola a 40 minuti' },
  { c: 'Lubiana', k: 'Slovenia', lat: 46.06, lon: 14.51, t: 2, n: 'centro pedonale sui ponti di Plečnik, castello in funicolare, mercato coperto; piccola e verdissima' },
  { c: 'Bled', k: 'Slovenia', lat: 46.37, lon: 14.11, t: 2, n: 'isola con la chiesa raggiunta solo in pletna a remi, castello a picco, kremšnita; Bohinj più selvaggio a 30 minuti' },
  { c: 'Bratislava', k: 'Slovacchia', lat: 48.15, lon: 17.11, t: 3, n: 'castello bianco sul Danubio, centro piccolo con le statue di bronzo; un\'ora da Vienna anche in battello' },
  { c: 'Bucarest', k: 'Romania', lat: 44.43, lon: 26.1, t: 3, n: 'Palazzo del Parlamento smisurato, centro vecchio dei locali, ville art déco; contrasti forti tra quartieri' },
  { c: 'Transilvania', k: 'Romania', lat: 45.65, lon: 25.61, t: 2, n: 'Brașov, Sighișoara e i castelli di Bran e Peleș; chiese fortificate sassoni, strade di montagna lente' },
  { c: 'Sofia', k: 'Bulgaria', lat: 42.7, lon: 23.32, t: 3, n: 'Aleksandăr Nevski, rovine romane sotto la metropolitana, Vitoša alle spalle raggiungibile in giornata' },
  { c: 'Belgrado', k: 'Serbia', lat: 44.79, lon: 20.45, t: 3, n: 'fortezza di Kalemegdan alla confluenza tra Sava e Danubio, Skadarlija bohémien, splavovi galleggianti la notte' },
  { c: 'Sarajevo', k: 'Bosnia ed Erzegovina', lat: 43.86, lon: 18.41, t: 2, n: 'Baščaršija ottomana e la linea dove l\'Oriente incontra l\'Occidente segnata per terra; tunnel della guerra e rose di Sarajevo' },
  { c: 'Mostar', k: 'Bosnia ed Erzegovina', lat: 43.34, lon: 17.81, t: 3, n: 'Stari Most ricostruito e i tuffatori, bazar ottomano; Blagaj e le cascate di Kravice a mezz\'ora' },
  { c: 'Kotor', k: 'Montenegro', lat: 42.42, lon: 18.77, t: 2, n: 'bocche di Cattaro come un fiordo, mura fino a San Giovanni con 1350 gradini, Perast e la Madonna dello Scalpello' },
  { c: 'Tirana', k: 'Albania', lat: 41.33, lon: 19.82, t: 3, n: 'palazzi dipinti, bunker musealizzati (Bunk\'Art), Dajti in funivia; base per Berat e Valona' },
  { c: 'Tallinn', k: 'Estonia', lat: 59.44, lon: 24.75, t: 2, n: 'città vecchia medievale intatta e quartiere Telliskivi creativo; traghetto per Helsinki in due ore' },
  { c: 'Riga', k: 'Lettonia', lat: 56.95, lon: 24.11, t: 3, n: 'il più grande insieme art nouveau d\'Europa in via Alberta, mercato centrale negli hangar degli zeppelin' },
  { c: 'Vilnius', k: 'Lituania', lat: 54.69, lon: 25.28, t: 3, n: 'barocco della città vecchia UNESCO, repubblica autoproclamata di Užupis con la sua costituzione sul muro' },
  // ══════════════════════════ GRECIA, TURCHIA, MEDITERRANEO ORIENTALE ══════════════════════════
  { c: 'Santorini', k: 'Grecia', lat: 36.42, lon: 25.43, t: 1, n: 'Fira e Oia sulla caldera, tramonto affollatissimo, spiagge nere e rosse; muli e funivia dal porto vecchio' },
  { c: 'Mykonos', k: 'Grecia', lat: 37.45, lon: 25.33, t: 1, n: 'Chora labirintica per confondere i pirati, mulini e Little Venice; Delo archeologica in barca, carissima ovunque' },
  { c: 'Creta occidentale', k: 'Grecia', lat: 35.51, lon: 24.02, t: 1, n: 'Chania veneziana, gola di Samaria (16 km, solo in stagione), Elafonissi e Balos raggiungibili con sterrati o barca' },
  { c: 'Creta orientale', k: 'Grecia', lat: 35.34, lon: 25.13, t: 2, n: 'Heraklion col museo archeologico e Cnosso, altopiano di Lassithi, Spinalonga in barca da Elounda' },
  { c: 'Rodi', k: 'Grecia', lat: 36.44, lon: 28.22, t: 2, n: 'città medievale murata dei Cavalieri, Lindos con l\'acropoli sul mare, valle delle farfalle in estate' },
  { c: 'Corfù', k: 'Grecia', lat: 39.62, lon: 19.92, t: 2, n: 'centro veneziano UNESCO, Achilleion, Paleokastritsa; verde e italiana nell\'aspetto più di ogni altra isola greca' },
  { c: 'Naxos e Paros', k: 'Grecia', lat: 37.1, lon: 25.38, t: 3, n: 'Cicladi vivibili e meno care: Portara di Naxos, borghi di montagna, Paros con Naoussa e i traghetti veloci' },
  { c: 'Zante', k: 'Grecia', lat: 37.79, lon: 20.9, t: 3, n: 'Navagio col relitto (accesso dall\'alto limitato per frane) e le tartarughe caretta caretta nel golfo di Laganas' },
  { c: 'Meteore', k: 'Grecia', lat: 39.71, lon: 21.63, t: 2, n: 'sei monasteri su pinnacoli di roccia, ognuno col suo giorno di chiusura: abbigliamento coprente obbligatorio' },
  { c: 'Nafplio', k: 'Grecia', lat: 37.57, lon: 22.8, t: 3, n: 'prima capitale greca, veneziana nell\'impianto, Palamidi con 900 gradini; Micene ed Epidauro vicine' },
  { c: 'Salonicco', k: 'Grecia', lat: 40.64, lon: 22.94, t: 3, n: 'Torre Bianca, rotonda di Galerio e chiese bizantine UNESCO; cucina la migliore della Grecia, Ano Poli sopravvissuta all\'incendio' },
  { c: 'Cappadocia', k: 'Turchia', lat: 38.64, lon: 34.83, t: 1, n: 'Göreme, camini delle fate, città sotterranee e mongolfiere all\'alba (voli cancellati spesso per vento)' },
  { c: 'Efeso', k: 'Turchia', lat: 37.95, lon: 27.37, t: 2, n: 'la biblioteca di Celso e le case a terrazza col biglietto separato; Selçuk come base, Şirince nell\'entroterra' },
  { c: 'Pamukkale', k: 'Turchia', lat: 37.92, lon: 29.12, t: 3, n: 'terrazze di travertino da percorrere scalzi e Hierapolis sopra: mezza giornata, poi ripartire' },
  { c: 'Antalya', k: 'Turchia', lat: 36.89, lon: 30.71, t: 2, n: 'Kaleiçi vecchia dentro le mura, cascate urbane, e i siti licio-romani di Perge e Aspendos nel raggio di un\'ora' },
  { c: 'Bodrum', k: 'Turchia', lat: 37.03, lon: 27.43, t: 3, n: 'castello dei Cavalieri col museo dell\'archeologia subacquea, gulet per le baie, mausoleo tra le sette meraviglie' },
  { c: 'Fethiye e Ölüdeniz', k: 'Turchia', lat: 36.62, lon: 29.12, t: 3, n: 'laguna blu e parapendio dal Babadağ, Valle delle Farfalle, tombe licie scavate nella roccia sopra la città' },
  { c: 'La Valletta', k: 'Malta', lat: 35.9, lon: 14.51, t: 1, n: 'Co-Cattedrale con i Caravaggio, Upper Barrakka e la salva delle cannonate, Tre Città in barca; tutto in scala minuta' },
  { c: 'Gozo', k: 'Malta', lat: 36.04, lon: 14.24, t: 3, n: 'Cittadella di Victoria, templi di Ġgantija più antichi delle piramidi, mare a Ramla e Dwejra; traghetto da Ċirkewwa' },
  { c: 'Pafos', k: 'Cipro', lat: 34.78, lon: 32.42, t: 3, n: 'mosaici romani UNESCO e tombe dei re, roccia di Afrodite; Troodos coi monasteri a un\'ora' },
  // ══════════════════════════ MEDIO ORIENTE ══════════════════════════
  { c: 'Petra', k: 'Giordania', lat: 30.32, lon: 35.48, t: 1, n: 'il Siq e il Tesoro sono l\'inizio: al Monastero servono 800 gradini; Petra by Night solo in certi giorni, Wadi Musa come base' },
  { c: 'Amman', k: 'Giordania', lat: 31.95, lon: 35.93, t: 3, n: 'cittadella e teatro romano, rainbow street; Jerash a un\'ora è tra le città romane meglio conservate al mondo' },
  { c: 'Wadi Rum', k: 'Giordania', lat: 29.58, lon: 35.42, t: 2, n: 'deserto in jeep coi beduini e notte nei campi tendati: escursioni di mezza giornata, freddo di notte anche d\'estate' },
  { c: 'Gerusalemme', k: 'Israele', lat: 31.78, lon: 35.22, t: 2, n: 'quattro quartieri nella città vecchia, Muro Occidentale, Santo Sepolcro e Spianata con orari di accesso rigidi; verifica sempre la situazione prima di partire' },
  { c: 'Tel Aviv', k: 'Israele', lat: 32.08, lon: 34.78, t: 3, n: 'Bauhaus della Città Bianca UNESCO, Giaffa antica, spiagge urbane e vita notturna; shabbat ferma quasi tutto' },
  { c: 'Abu Dhabi', k: 'Emirati Arabi Uniti', lat: 24.47, lon: 54.37, t: 2, n: 'Moschea Sheikh Zayed con codice di abbigliamento severo, Louvre di Nouvel, Corniche; deserto di Liwa più a sud' },
  { c: 'Doha', k: 'Qatar', lat: 25.29, lon: 51.53, t: 3, n: 'Museo di Arte Islamica di I.M. Pei, souq Waqif restaurato, Msheireb; scali lunghi che valgono l\'uscita' },
  { c: 'Muscat', k: 'Oman', lat: 23.59, lon: 58.41, t: 3, n: 'Grande Moschea, souq di Mutrah, forti portoghesi; wadi e deserto di Wahiba nel raggio di due ore' },
  { c: 'AlUla', k: 'Arabia Saudita', lat: 26.62, lon: 37.92, t: 3, n: 'Hegra nabatea UNESCO (la sorella di Petra) e Maraya specchiante nel deserto; visite solo con guida autorizzata' },
  // ══════════════════════════ AFRICA ══════════════════════════
  { c: 'Fes', k: 'Marocco', lat: 34.03, lon: -5.0, t: 2, n: 'la medina di Fes el-Bali è la più grande zona pedonale del mondo: guida quasi obbligatoria, concerie da vedere dall\'alto' },
  { c: 'Chefchaouen', k: 'Marocco', lat: 35.17, lon: -5.27, t: 3, n: 'la città blu del Rif: mezza giornata di vicoli, poi cascate di Akchour; strade di montagna tortuose per arrivarci' },
  { c: 'Casablanca', k: 'Marocco', lat: 33.57, lon: -7.59, t: 3, n: 'moschea Hassan II sull\'oceano (visitabile anche ai non musulmani), art déco moresco del centro; più lavorativa che turistica' },
  { c: 'Essaouira', k: 'Marocco', lat: 31.51, lon: -9.77, t: 3, n: 'medina murata sull\'Atlantico, vento costante per kitesurf, porto dei pescatori e legno di thuya' },
  { c: 'Tunisi', k: 'Tunisia', lat: 36.8, lon: 10.18, t: 3, n: 'medina UNESCO, museo del Bardo coi mosaici, Cartagine e Sidi Bou Said bianco e blu col TGM' },
  { c: 'Il Cairo', k: 'Egitto', lat: 30.04, lon: 31.24, t: 1, n: 'Giza e il Grande Museo Egizio, Cairo islamico e copto, Khan el-Khalili; traffico che raddoppia ogni spostamento' },
  { c: 'Luxor', k: 'Egitto', lat: 25.69, lon: 32.64, t: 1, n: 'Karnak e Luxor sulla riva est, Valle dei Re e Hatshepsut sulla ovest; mongolfiera all\'alba, caldo estremo da giugno' },
  { c: 'Sharm el-Sheikh', k: 'Egitto', lat: 27.92, lon: 34.33, t: 2, n: 'Ras Mohammed e lo stretto di Tiran per le immersioni, Naama Bay per la vita; escursione al Sinai e Santa Caterina di notte' },
  { c: 'Hurghada', k: 'Egitto', lat: 27.26, lon: 33.81, t: 3, n: 'villaggi sul mar Rosso e isole Giftun in barca; il deserto orientale con i beduini per rompere la routine del resort' },
  { c: 'Città del Capo', k: 'Sudafrica', lat: -33.92, lon: 18.42, t: 1, n: 'Table Mountain in funivia (chiude col vento), Robben Island da prenotare, Capo di Buona Speranza e i pinguini di Boulders' },
  { c: 'Kruger', k: 'Sudafrica', lat: -25.47, lon: 30.97, t: 2, n: 'safari self-drive o con ranger, cancelli con orari rigidi; Panorama Route con Blyde River sulla strada da Nelspruit' },
  { c: 'Zanzibar', k: 'Tanzania', lat: -6.16, lon: 39.19, t: 2, n: 'Stone Town UNESCO con le porte intagliate, spice tour, spiagge a nord-est con maree che spostano l\'acqua di centinaia di metri' },
  { c: 'Serengeti e Arusha', k: 'Tanzania', lat: -3.37, lon: 36.68, t: 2, n: 'Arusha base logistica, cratere di Ngorongoro e migrazione secondo la stagione; permessi e lodge da prenotare con mesi di anticipo' },
  { c: 'Nairobi', k: 'Kenya', lat: -1.29, lon: 36.82, t: 3, n: 'parco nazionale con lo skyline sullo sfondo, orfanotrofio degli elefanti, giraffe centre; Masai Mara con volo interno' },
  { c: 'Cascate Vittoria', k: 'Zimbabwe', lat: -17.92, lon: 25.86, t: 3, n: 'portata massima da marzo a maggio (impermeabile obbligatorio), Devil\'s Pool solo a secca; lato zambiano e zimbabwese diversi' },
  { c: 'Marrakech dintorni', k: 'Marocco', lat: 31.63, lon: -8.01, t: 3, n: 'valle dell\'Ourika, Atlante e Imlil, Ait Ben Haddou verso il deserto: escursioni di uno o due giorni dalla città' },
  // ══════════════════════════ ASIA ORIENTALE ══════════════════════════
  { c: 'Osaka', k: 'Giappone', lat: 34.69, lon: 135.5, t: 1, n: 'Dotonbori e il cibo di strada, castello, Umeda Sky; base economica per Nara e Kobe, mezz\'ora da Kyoto' },
  { c: 'Hiroshima', k: 'Giappone', lat: 34.39, lon: 132.46, t: 2, n: 'Parco della Pace e il Genbaku Dome, museo durissimo e necessario; Miyajima col torii sull\'acqua in traghetto' },
  { c: 'Nara', k: 'Giappone', lat: 34.69, lon: 135.81, t: 2, n: 'il Grande Buddha del Tōdai-ji e i cervi che si inchinano per i biscotti; si fa in giornata da Kyoto o Osaka' },
  { c: 'Hakone e Monte Fuji', k: 'Giappone', lat: 35.23, lon: 139.11, t: 2, n: 'onsen, funivia sulle solfatare e battello sul lago Ashi; il Fuji si vede solo col cielo terso, spesso in inverno' },
  { c: 'Sapporo', k: 'Giappone', lat: 43.06, lon: 141.35, t: 3, n: 'ramen al miso e birra, festival della neve a febbraio; Otaru e i parchi dell\'Hokkaidō attorno' },
  { c: 'Okinawa', k: 'Giappone', lat: 26.21, lon: 127.68, t: 3, n: 'castello di Shuri, acquario di Churaumi, spiagge subtropicali e cultura ryukyuana diversa dal resto del Giappone' },
  { c: 'Seul', k: 'Corea del Sud', lat: 37.57, lon: 126.98, t: 1, n: 'palazzi Joseon con hanbok per entrare gratis, Bukchon, Hongdae e Gangnam; metropolitana perfetta, mercati notturni' },
  { c: 'Busan', k: 'Corea del Sud', lat: 35.18, lon: 129.08, t: 3, n: 'Gamcheon a colori sul pendio, mercato del pesce di Jagalchi, tempio Haedong Yonggungsa sul mare' },
  { c: 'Pechino', k: 'Cina', lat: 39.9, lon: 116.41, t: 1, n: 'Città Proibita con prenotazione e passaporto, Grande Muraglia a Mutianyu meno affollata, hutong in risciò' },
  { c: 'Shanghai', k: 'Cina', lat: 31.23, lon: 121.47, t: 1, n: 'Bund coloniale contro lo skyline di Pudong, concessione francese, giardino Yuyuan; treni veloci per Suzhou e Hangzhou' },
  { c: 'Xi\'an', k: 'Cina', lat: 34.34, lon: 108.94, t: 2, n: 'l\'Esercito di Terracotta a 40 km, mura Ming percorribili in bici, quartiere musulmano per lo street food' },
  { c: 'Guilin e Yangshuo', k: 'Cina', lat: 25.27, lon: 110.29, t: 3, n: 'crociera sul fiume Li tra i pinnacoli carsici e risaie a terrazza di Longsheng; Yangshuo in bici' },
  { c: 'Hong Kong', k: 'Cina', lat: 22.32, lon: 114.17, t: 1, n: 'Victoria Peak col tram, Star Ferry, mercati di Kowloon e isole di Lantau; verticale e velocissima' },
  { c: 'Macao', k: 'Cina', lat: 22.2, lon: 113.54, t: 3, n: 'rovine di São Paulo e centro portoghese UNESCO accanto ai casinò; un\'ora di traghetto da Hong Kong' },
  { c: 'Taipei', k: 'Taiwan', lat: 25.03, lon: 121.57, t: 2, n: 'Taipei 101, mercati notturni di Shilin e Raohe, museo del Palazzo Nazionale; Jiufen e Beitou coi bagni termali vicino' },
  // ══════════════════════════ SUD-EST ASIATICO ══════════════════════════
  { c: 'Chiang Mai', k: 'Thailandia', lat: 18.79, lon: 98.99, t: 2, n: 'città vecchia coi templi dentro il fossato, Doi Suthep sopra, santuari etici per elefanti (verifica sempre come li trattano)' },
  { c: 'Phuket', k: 'Thailandia', lat: 7.88, lon: 98.39, t: 2, n: 'Patong caotica, spiagge quiete a sud, Phang Nga e Phi Phi in barca; monsone da maggio a ottobre con bandiere rosse' },
  { c: 'Krabi', k: 'Thailandia', lat: 8.09, lon: 98.91, t: 3, n: 'Railay raggiungibile solo via mare, arrampicata su falesie, isole in long tail; Ao Nang come base' },
  { c: 'Koh Samui', k: 'Thailandia', lat: 9.51, lon: 100.01, t: 3, n: 'Chaweng e Lamai per la vita, Ang Thong in barca, Big Buddha; Koh Phangan a mezz\'ora per la full moon' },
  { c: 'Ayutthaya', k: 'Thailandia', lat: 14.35, lon: 100.58, t: 3, n: 'antica capitale in rovina UNESCO, si gira in bici o tuk tuk in un giorno; treno diretto da Bangkok' },
  { c: 'Siem Reap', k: 'Cambogia', lat: 13.36, lon: 103.86, t: 1, n: 'Angkor Wat all\'alba, Bayon e Ta Prohm tra le radici: pass da 1, 3 o 7 giorni, caldo che impone pause pomeridiane' },
  { c: 'Phnom Penh', k: 'Cambogia', lat: 11.56, lon: 104.92, t: 3, n: 'Palazzo Reale e Pagoda d\'Argento, Tuol Sleng e Choeung Ek come memoria dei khmer rossi: pesante ma essenziale' },
  { c: 'Hanoi', k: 'Vietnam', lat: 21.03, lon: 105.85, t: 1, n: 'città vecchia delle 36 corporazioni, lago Hoan Kiem, bun cha e caffè all\'uovo; traffico di scooter da attraversare con calma' },
  { c: 'Baia di Ha Long', k: 'Vietnam', lat: 20.95, lon: 107.07, t: 1, n: 'crociera di una o due notti tra i faraglioni, grotte e kayak; Lan Ha meno affollata, meteo decisivo' },
  { c: 'Ho Chi Minh', k: 'Vietnam', lat: 10.82, lon: 106.63, t: 2, n: 'ex Saigon: museo dei residuati di guerra, tunnel di Cu Chi, mercato di Ben Thanh; delta del Mekong in giornata' },
  { c: 'Hoi An', k: 'Vietnam', lat: 15.88, lon: 108.33, t: 1, n: 'città vecchia UNESCO illuminata dalle lanterne, sarti su misura in 24 ore, spiaggia di An Bang a 10 minuti in bici' },
  { c: 'Hue', k: 'Vietnam', lat: 16.46, lon: 107.59, t: 3, n: 'cittadella imperiale e tombe dei sovrani lungo il Fiume dei Profumi; passo di Hai Van verso Da Nang' },
  { c: 'Luang Prabang', k: 'Laos', lat: 19.89, lon: 102.14, t: 3, n: 'offerta dell\'elemosina ai monaci all\'alba (da rispettare, non da fotografare addosso), cascate di Kuang Si, Mekong al tramonto' },
  { c: 'Bagan', k: 'Myanmar', lat: 21.17, lon: 94.86, t: 3, n: 'migliaia di templi nella piana, alba dalle terrazze autorizzate, e-bike come mezzo; verifica la situazione del Paese prima di partire' },
  { c: 'Kuala Lumpur', k: 'Malesia', lat: 3.14, lon: 101.69, t: 2, n: 'Petronas e skybridge da prenotare, grotte di Batu, Chinatown e Little India; scalo che vale due giorni' },
  { c: 'Penang', k: 'Malesia', lat: 5.41, lon: 100.34, t: 3, n: 'George Town UNESCO con street art e case dei clan sul mare, street food tra i migliori d\'Asia' },
  { c: 'Bali - Ubud', k: 'Indonesia', lat: -8.51, lon: 115.26, t: 1, n: 'risaie di Tegallalang, tempio Tirta Empul, scimmie della Monkey Forest; traffico lentissimo, meglio pochi spostamenti' },
  { c: 'Bali - sud', k: 'Indonesia', lat: -8.69, lon: 115.17, t: 1, n: 'Seminyak, Canggu e Uluwatu col kecak al tramonto; spiagge da surf, correnti forti, Nusa Penida in barca veloce' },
  { c: 'Yogyakarta', k: 'Indonesia', lat: -7.8, lon: 110.36, t: 2, n: 'Borobudur all\'alba e Prambanan, kraton del sultano, batik; base per il vulcano Merapi' },
  { c: 'Lombok e Gili', k: 'Indonesia', lat: -8.65, lon: 116.32, t: 3, n: 'Rinjani per i trekker, Kuta Lombok per le onde, Gili senza auto né moto: solo bici e carretti' },
  { c: 'Manila', k: 'Filippine', lat: 14.6, lon: 120.98, t: 3, n: 'Intramuros spagnola e Fort Santiago, tramonto sulla baia; scalo obbligato verso le isole' },
  { c: 'Palawan', k: 'Filippine', lat: 11.2, lon: 119.42, t: 2, n: 'El Nido e le lagune col tour A/B/C/D, Coron per i relitti, fiume sotterraneo di Puerto Princesa UNESCO' },
  { c: 'Cebu e Bohol', k: 'Filippine', lat: 10.32, lon: 123.89, t: 3, n: 'squali balena a Oslob (turismo discusso, valuta le alternative), cascate di Kawasan, Chocolate Hills e tarsi a Bohol' },
  // ══════════════════════════ ASIA MERIDIONALE E CENTRALE ══════════════════════════
  { c: 'Delhi', k: 'India', lat: 28.61, lon: 77.21, t: 1, n: 'Old Delhi con Jama Masjid e Chandni Chowk, New Delhi coloniale, Qutub Minar e Humayun UNESCO; smog forte in inverno' },
  { c: 'Agra', k: 'India', lat: 27.18, lon: 78.02, t: 1, n: 'Taj Mahal all\'alba (chiuso il venerdì), Forte Rosso e Baby Taj; treno veloce da Delhi in due ore' },
  { c: 'Jaipur', k: 'India', lat: 26.91, lon: 75.79, t: 1, n: 'città rosa: Amber Fort, Hawa Mahal, City Palace e l\'osservatorio Jantar Mantar; bazar per tessuti e pietre' },
  { c: 'Udaipur', k: 'India', lat: 24.58, lon: 73.68, t: 2, n: 'palazzi sul lago Pichola, City Palace enorme, tramonti dai rooftop; la più romantica del Rajasthan' },
  { c: 'Varanasi', k: 'India', lat: 25.32, lon: 83.01, t: 2, n: 'ghat sul Gange all\'alba in barca e aarti serale; intensa e non filtrata, Sarnath buddhista a 10 km' },
  { c: 'Mumbai', k: 'India', lat: 19.08, lon: 72.88, t: 2, n: 'Gateway of India, Victoria Terminus UNESCO, Elephanta in traghetto, dabbawala e Dharavi con tour responsabili' },
  { c: 'Goa', k: 'India', lat: 15.5, lon: 73.83, t: 3, n: 'chiese portoghesi di Old Goa UNESCO, spiagge nord movimentate e sud tranquille; stagione da novembre a marzo' },
  { c: 'Kerala', k: 'India', lat: 9.93, lon: 76.27, t: 2, n: 'Kochi con le reti cinesi e il quartiere ebraico, backwaters in houseboat da Alleppey, tè a Munnar' },
  { c: 'Amritsar', k: 'India', lat: 31.63, lon: 74.87, t: 3, n: 'Tempio d\'Oro aperto a tutti con capo coperto e mensa gratuita per decine di migliaia; cerimonia del confine a Wagah' },
  { c: 'Kathmandu', k: 'Nepal', lat: 27.72, lon: 85.32, t: 2, n: 'Durbar Square, Swayambhunath e Boudhanath, Pashupatinath sul fiume; base per i trek e Bhaktapur a 30 minuti' },
  { c: 'Pokhara', k: 'Nepal', lat: 28.21, lon: 83.99, t: 3, n: 'lago Phewa con l\'Annapurna riflesso, parapendio, Sarangkot all\'alba; partenza dell\'ABC trek' },
  { c: 'Sri Lanka - Kandy', k: 'Sri Lanka', lat: 7.29, lon: 80.64, t: 2, n: 'tempio del Dente, treno panoramico per Ella tra le piantagioni, Sigiriya e Dambulla a nord' },
  { c: 'Maldive', k: 'Maldive', lat: 4.18, lon: 73.51, t: 2, n: 'isole locali (Maafushi, Dhigurah) come alternativa economica ai resort: regole di abbigliamento e alcol diverse' },
  { c: 'Samarcanda', k: 'Uzbekistan', lat: 39.65, lon: 66.96, t: 2, n: 'Registan, Shah-i-Zinda e Gur-e-Amir: la via della seta al suo massimo, treni veloci da Tashkent' },
  { c: 'Bukhara', k: 'Uzbekistan', lat: 39.77, lon: 64.42, t: 3, n: 'centro storico compatto e vivibile, minareto Kalon, caravanserragli trasformati in botteghe' },
  { c: 'Tbilisi', k: 'Georgia', lat: 41.72, lon: 44.79, t: 2, n: 'bagni sulfurei di Abanotubani, città vecchia sotto la fortezza, cucina e vini in qvevri; Mtskheta e Kazbegi vicine' },
  { c: 'Baku', k: 'Azerbaigian', lat: 40.41, lon: 49.87, t: 3, n: 'città murata UNESCO contro le Flame Towers, boulevard sul Caspio, vulcani di fango e Gobustan' },
  { c: 'Yerevan', k: 'Armenia', lat: 40.18, lon: 44.51, t: 3, n: 'Cascade e piazza della Repubblica, monasteri di Geghard e Khor Virap col Ararat di fronte' },
  // ══════════════════════════ NORD AMERICA ══════════════════════════
  { c: 'Los Angeles', k: 'Stati Uniti', lat: 34.05, lon: -118.24, t: 1, n: 'nessun centro: Hollywood, Santa Monica, Downtown e Getty sono zone lontane, auto necessaria, traffico da pianificare' },
  { c: 'San Francisco', k: 'Stati Uniti', lat: 37.77, lon: -122.42, t: 1, n: 'cable car, Alcatraz da prenotare settimane prima, Golden Gate in bici; colline ripide e nebbia estiva' },
  { c: 'Las Vegas', k: 'Stati Uniti', lat: 36.17, lon: -115.14, t: 1, n: 'la Strip si percorre a piedi ma le distanze ingannano, hotel a tema come attrazioni; base per Grand Canyon, Zion e Death Valley' },
  { c: 'Miami', k: 'Stati Uniti', lat: 25.77, lon: -80.19, t: 1, n: 'art déco di Ocean Drive, Wynwood coi murales, Little Havana; Everglades e Keys in giornata' },
  { c: 'Orlando', k: 'Stati Uniti', lat: 28.54, lon: -81.38, t: 1, n: 'Walt Disney World e Universal: prenotazione parchi e app obbligatorie, un giorno per parco è il minimo' },
  { c: 'Chicago', k: 'Stati Uniti', lat: 41.88, lon: -87.63, t: 2, n: 'architettura in crociera sul fiume (la cosa migliore), Millennium Park, Art Institute; vento e freddo veri in inverno' },
  { c: 'Washington', k: 'Stati Uniti', lat: 38.91, lon: -77.04, t: 2, n: 'National Mall coi musei Smithsonian gratuiti, Campidoglio e memoriali di sera; fioritura dei ciliegi a fine marzo' },
  { c: 'Boston', k: 'Stati Uniti', lat: 42.36, lon: -71.06, t: 2, n: 'Freedom Trail segnato sul marciapiede, Harvard e MIT oltre il fiume; New England e foliage in autunno' },
  { c: 'New Orleans', k: 'Stati Uniti', lat: 29.95, lon: -90.07, t: 2, n: 'French Quarter e Frenchmen Street per il jazz vero, Garden District col tram; cucina creola e cimiteri sopra terra' },
  { c: 'Seattle', k: 'Stati Uniti', lat: 47.61, lon: -122.33, t: 3, n: 'Pike Place Market, Space Needle e Chihuly, musei della musica e del volo; Rainier e Olympic per i parchi' },
  { c: 'San Diego', k: 'Stati Uniti', lat: 32.72, lon: -117.16, t: 3, n: 'Balboa Park coi suoi musei e lo zoo, Gaslamp, La Jolla con le foche; Tijuana appena oltre il confine' },
  { c: 'Nashville', k: 'Stati Uniti', lat: 36.16, lon: -86.78, t: 3, n: 'Broadway coi locali dal vivo tutto il giorno, Country Music Hall of Fame, Grand Ole Opry' },
  { c: 'Denver e Montagne Rocciose', k: 'Stati Uniti', lat: 39.74, lon: -104.99, t: 3, n: 'base per il Rocky Mountain National Park e Boulder; l\'altitudine si sente il primo giorno, bevi molto' },
  { c: 'Sedona', k: 'Stati Uniti', lat: 34.87, lon: -111.76, t: 3, n: 'rocce rosse e sentieri (Cathedral Rock, Devil\'s Bridge), jeep tour; Antelope Canyon e Grand Canyon a nord' },
  { c: 'Grand Canyon', k: 'Stati Uniti', lat: 36.06, lon: -112.14, t: 1, n: 'South Rim aperto tutto l\'anno con navette gratuite, North Rim chiuso d\'inverno; scendere sotto il bordo è impegnativo' },
  { c: 'Yellowstone', k: 'Stati Uniti', lat: 44.43, lon: -110.59, t: 2, n: 'geyser, sorgenti colorate e bisonti: distanze enormi dentro il parco, prenotare alloggio con mesi di anticipo' },
  { c: 'Yosemite', k: 'Stati Uniti', lat: 37.75, lon: -119.59, t: 2, n: 'El Capitan e Half Dome, cascate al massimo in maggio-giugno; permesso d\'ingresso a orario nei mesi di punta' },
  { c: 'Honolulu e Oahu', k: 'Stati Uniti', lat: 21.31, lon: -157.86, t: 2, n: 'Waikiki e Diamond Head, Pearl Harbor con prenotazione, North Shore per le onde d\'inverno' },
  { c: 'Maui', k: 'Stati Uniti', lat: 20.88, lon: -156.68, t: 3, n: 'strada per Hana con 600 curve, alba a Haleakalā su prenotazione; rispetta le zone colpite dagli incendi' },
  { c: 'Philadelphia', k: 'Stati Uniti', lat: 39.95, lon: -75.17, t: 3, n: 'Liberty Bell e Independence Hall, i gradini del Museum of Art, Reading Terminal Market' },
  { c: 'Charleston e Savannah', k: 'Stati Uniti', lat: 32.78, lon: -79.93, t: 3, n: 'Sud storico: case antebellum, querce con la barba spagnola, piazze alberate; due città a due ore l\'una dall\'altra' },
  { c: 'Toronto', k: 'Canada', lat: 43.65, lon: -79.38, t: 2, n: 'CN Tower, Distillery District, isole di fronte in traghetto; Niagara a un\'ora e mezza' },
  { c: 'Montréal', k: 'Canada', lat: 45.5, lon: -73.57, t: 2, n: 'Vieux-Montréal francofona, Mont Royal, città sotterranea per l\'inverno; festival tutta l\'estate' },
  { c: 'Québec', k: 'Canada', lat: 46.81, lon: -71.21, t: 3, n: 'l\'unica città murata a nord del Messico, Château Frontenac, Petit Champlain; carnevale invernale' },
  { c: 'Vancouver', k: 'Canada', lat: 49.28, lon: -123.12, t: 2, n: 'Stanley Park sul mare, Granville Island, Grouse e Capilano; Whistler a due ore sulla Sea to Sky' },
  { c: 'Banff e Rocciose canadesi', k: 'Canada', lat: 51.18, lon: -115.57, t: 2, n: 'Lake Louise e Moraine con navetta obbligatoria, Icefields Parkway fino a Jasper: una delle strade più belle del mondo' },
  // ══════════════════════════ MESSICO, CARAIBI, CENTRO AMERICA ══════════════════════════
  { c: 'Città del Messico', k: 'Messico', lat: 19.43, lon: -99.13, t: 1, n: 'Zócalo e Templo Mayor, Coyoacán con la Casa Azul, Teotihuacán a un\'ora; altitudine 2240 m, primo giorno lento' },
  { c: 'Cancún e Riviera Maya', k: 'Messico', lat: 21.16, lon: -86.85, t: 1, n: 'resort sulla laguna, cenote nell\'entroterra, Isla Mujeres in traghetto; sargassum variabile da maggio a ottobre' },
  { c: 'Tulum', k: 'Messico', lat: 20.21, lon: -87.46, t: 2, n: 'rovine maya a picco sul mare (arrivare all\'apertura), cenote Dos Ojos e Gran Cenote, spiagge con prezzi da capitale' },
  { c: 'Mérida e Chichén Itzá', k: 'Messico', lat: 20.97, lon: -89.62, t: 2, n: 'capitale dello Yucatán coloniale e sicura, haciendas e cenote attorno; Chichén Itzá presto per evitare caldo e folla' },
  { c: 'Oaxaca', k: 'Messico', lat: 17.07, lon: -96.72, t: 2, n: 'mole e mezcal, Monte Albán zapoteco, mercati di Tlacolula; a novembre il Día de Muertos è il momento più intenso' },
  { c: 'San Miguel de Allende', k: 'Messico', lat: 20.91, lon: -100.74, t: 3, n: 'coloniale UNESCO tutta cortili e rooftop, Guanajuato a un\'ora coi vicoli e i tunnel sotto la città' },
  { c: 'Puerto Vallarta', k: 'Messico', lat: 20.65, lon: -105.22, t: 3, n: 'malecón con le sculture, Zona Romántica, spiagge di Yelapa raggiungibili solo in barca' },
  { c: 'L\'Avana', k: 'Cuba', lat: 23.11, lon: -82.37, t: 2, n: 'Habana Vieja UNESCO, Malecón, auto d\'epoca; contante indispensabile e connessione lenta, mettilo in conto' },
  { c: 'Varadero', k: 'Cuba', lat: 23.14, lon: -81.29, t: 3, n: 'venti chilometri di spiaggia e resort all inclusive; escursioni a Matanzas e alla valle di Yumurí per vedere il Paese vero' },
  { c: 'Punta Cana', k: 'Repubblica Dominicana', lat: 18.58, lon: -68.4, t: 2, n: 'resort su Bávaro e Macao, Saona e Catalina in catamarano, Hoyo Azul; stagione degli uragani da agosto a ottobre' },
  { c: 'San Juan', k: 'Porto Rico', lat: 18.47, lon: -66.11, t: 3, n: 'Viejo San Juan colorato con i due forti, foresta di El Yunque, baia bioluminescente di Fajardo' },
  { c: 'Panama', k: 'Panama', lat: 8.98, lon: -79.52, t: 3, n: 'Canale alle chiuse di Miraflores, Casco Viejo restaurato, San Blas per le isole guna' },
  { c: 'Costa Rica', k: 'Costa Rica', lat: 10.47, lon: -84.64, t: 2, n: 'La Fortuna col vulcano Arenal e le terme, Monteverde sospesa nella nebbia, Manuel Antonio per fauna e spiaggia' },
  { c: 'Antigua Guatemala', k: 'Guatemala', lat: 14.56, lon: -90.73, t: 3, n: 'coloniale tra i vulcani, ascesa notturna all\'Acatenango per vedere il Fuego eruttare; lago Atitlán e Tikal nel Paese' },
  // ══════════════════════════ SUD AMERICA ══════════════════════════
  { c: 'Rio de Janeiro', k: 'Brasile', lat: -22.91, lon: -43.17, t: 1, n: 'Cristo e Pan di Zucchero col meteo giusto, Copacabana e Ipanema, Santa Teresa e Lapa; attenzione a orari e zone la sera' },
  { c: 'San Paolo', k: 'Brasile', lat: -23.55, lon: -46.63, t: 3, n: 'MASP e Paulista, Liberdade giapponese, Beco do Batman; gastronomia e musica più che monumenti' },
  { c: 'Salvador de Bahia', k: 'Brasile', lat: -12.97, lon: -38.51, t: 3, n: 'Pelourinho coloniale, capoeira e percussioni, cucina africana; Elevador Lacerda tra città alta e bassa' },
  { c: 'Iguazú', k: 'Argentina', lat: -25.6, lon: -54.57, t: 1, n: 'lato argentino per le passerelle e la Gola del Diavolo, brasiliano per la vista d\'insieme: servono due giorni, uno per lato' },
  { c: 'Buenos Aires', k: 'Argentina', lat: -34.6, lon: -58.38, t: 1, n: 'San Telmo la domenica, Recoleta col cimitero, La Boca solo di giorno; milonghe per il tango vero, non lo spettacolo' },
  { c: 'Bariloche', k: 'Argentina', lat: -41.13, lon: -71.31, t: 3, n: 'Circuito Chico tra laghi e boschi, cioccolato svizzero-argentino, sci a Cerro Catedral d\'inverno' },
  { c: 'Mendoza', k: 'Argentina', lat: -32.89, lon: -68.85, t: 3, n: 'malbec nelle cantine di Luján e Uco con degustazioni prenotate, Aconcagua sulla strada per il Cile' },
  { c: 'El Calafate e Patagonia', k: 'Argentina', lat: -50.34, lon: -72.27, t: 2, n: 'Perito Moreno con passerelle e minitrekking, El Chaltén per il Fitz Roy; vento fortissimo, stagione da ottobre a marzo' },
  { c: 'Cusco e Machu Picchu', k: 'Perù', lat: -13.53, lon: -71.97, t: 1, n: 'Cusco a 3400 m: due giorni di acclimatamento prima; Machu Picchu con biglietto a circuito e orario, treno da Ollantaytambo' },
  { c: 'Lima', k: 'Perù', lat: -12.05, lon: -77.04, t: 2, n: 'Miraflores e Barranco sull\'oceano, centro coloniale UNESCO, e una delle migliori cucine del mondo' },
  { c: 'Arequipa', k: 'Perù', lat: -16.41, lon: -71.54, t: 3, n: 'città bianca di sillar col monastero di Santa Catalina come città nella città; Colca per i condor all\'alba' },
  { c: 'Quito', k: 'Ecuador', lat: -0.18, lon: -78.47, t: 3, n: 'centro coloniale UNESCO a 2850 m, TelefériQo, Mitad del Mundo; porta d\'accesso alle Galápagos' },
  { c: 'La Paz e Uyuni', k: 'Bolivia', lat: -16.5, lon: -68.15, t: 3, n: 'teleferiche urbane come mezzo quotidiano, mercato delle streghe; salar di Uyuni a specchio nella stagione delle piogge' },
  { c: 'Santiago del Cile', k: 'Cile', lat: -33.45, lon: -70.67, t: 3, n: 'Cerro San Cristóbal, Bellavista di Neruda, mercati; Valparaíso coloratissima e le cantine del Maipo in giornata' },
  { c: 'Atacama', k: 'Cile', lat: -22.91, lon: -68.2, t: 3, n: 'San Pedro base per geyser del Tatio all\'alba, Valle della Luna e lagune altiplaniche; altitudine e sbalzi termici forti' },
  { c: 'Cartagena', k: 'Colombia', lat: 10.39, lon: -75.51, t: 2, n: 'città murata e Getsemaní, isole del Rosario in barca; caldo umido costante, si esce la sera' },
  { c: 'Medellín', k: 'Colombia', lat: 6.24, lon: -75.57, t: 3, n: 'metrocable sui quartieri, Comuna 13 con le scale mobili e i murales, Guatapé con la roccia da 700 gradini' },
  { c: 'Montevideo', k: 'Uruguay', lat: -34.9, lon: -56.16, t: 3, n: 'Ciudad Vieja e mercato del porto, rambla di 22 km; Colonia del Sacramento e Punta del Este vicine' },
  // ══════════════════════════ OCEANIA ══════════════════════════
  { c: 'Melbourne', k: 'Australia', lat: -37.81, lon: 144.96, t: 1, n: 'laneway con caffè e street art, mercato Queen Victoria, tram gratuito in centro; Great Ocean Road in giornata lunga' },
  { c: 'Brisbane e Gold Coast', k: 'Australia', lat: -27.47, lon: 153.03, t: 3, n: 'South Bank con la spiaggia artificiale, koala a Lone Pine, surf e parchi a un\'ora a sud' },
  { c: 'Cairns e Grande Barriera', k: 'Australia', lat: -16.92, lon: 145.77, t: 2, n: 'uscite in barca al reef esterno, Daintree foresta pluviale e Kuranda col trenino; meduse da novembre a maggio' },
  { c: 'Perth', k: 'Australia', lat: -31.95, lon: 115.86, t: 3, n: 'Kings Park sulla città, Fremantle portuale, quokka a Rottnest in traghetto e bici' },
  { c: 'Adelaide', k: 'Australia', lat: -34.93, lon: 138.6, t: 3, n: 'città ordinata coi parchi attorno, Barossa e McLaren Vale per il vino, Kangaroo Island per la fauna' },
  { c: 'Uluru', k: 'Australia', lat: -25.24, lon: 130.99, t: 2, n: 'alba e tramonto sono l\'evento, salita vietata dal 2019, base walk di 10 km; Kata Tjuta a 50 km' },
  { c: 'Tasmania', k: 'Australia', lat: -42.88, lon: 147.33, t: 3, n: 'Hobart col MONA e il Salamanca Market, Port Arthur penale, Cradle Mountain; auto indispensabile' },
  { c: 'Auckland', k: 'Nuova Zelanda', lat: -36.85, lon: 174.76, t: 2, n: 'città su 48 vulcani, Waiheke per il vino in traghetto, Sky Tower; base d\'arrivo per l\'isola del Nord' },
  { c: 'Rotorua', k: 'Nuova Zelanda', lat: -38.14, lon: 176.25, t: 3, n: 'geotermia e odore di zolfo, cultura maori con haka e hangi, Hobbiton a un\'ora' },
  { c: 'Queenstown', k: 'Nuova Zelanda', lat: -45.03, lon: 168.66, t: 2, n: 'capitale dell\'adrenalina: bungy, jet boat, sci; Milford Sound a quattro ore di strada spettacolare' },
  { c: 'Wellington', k: 'Nuova Zelanda', lat: -41.29, lon: 174.78, t: 3, n: 'Te Papa gratuito, funicolare e caffè, vento costante; traghetto per l\'isola del Sud tra i fiordi' },
  { c: 'Figi', k: 'Figi', lat: -17.8, lon: 177.42, t: 3, n: 'Nadi come arrivo, isole Mamanuca e Yasawa in catamarano, cerimonia del kava nei villaggi' },
];

/** Le zone da seminare per prime: le più visitate in assoluto. */
export const WORLD_ZONE_TIER1 = WORLD_ZONES.filter(z => z.t === 1).map(z => z.c);
