// =====================================================================
// ITAINTA · Costanti Mappa e Categorie (Centralizzate)
// Per evitare dipendenze circolari tra MapArea, PoiPopupContent, ecc.
// =====================================================================

export const CATEGORY_COLORS: Record<string, string> = {
  gemme:             "bg-[#0f766e]",
  monumenti:         "bg-[#92400e]",
  chiese:            "bg-[#4338ca]",
  musei:             "bg-[#7c3aed]",
  panorami:          "bg-[#0369a1]",
  locali:            "bg-[#e11d48]",
  utilita:           "bg-[#1e1b4b]",
  famiglie:          "bg-[#b45309]",
  esperienze_locali: "bg-[#ea580c]",
  eventi:            "bg-[#7e22ce]",
  community:         "bg-[#ec4899]",
  // Atlante dei beni vincolati: grigio pietra, volutamente spento — non deve
  // competere con i pin turistici che gli stanno accanto.
  beni_culturali:    "bg-[#78716c]",
  church:            "bg-[#4338ca]",
  museum:            "bg-[#7c3aed]",
  viewpoint:         "bg-[#0369a1]",
  castle:            "bg-[#78350f]",
  monument:          "bg-[#92400e]",
  ruins:             "bg-[#57534e]",
  archaeological_site: "bg-[#a16207]",
  artwork:           "bg-[#be185d]",
  attraction:        "bg-[#16a34a]",
  restaurant:        "bg-[#e11d48]",
  // Verticali NATURALI (harvest non culturale): palette fredda acqua/verde/roccia,
  // distinta a colpo d'occhio dai marroni e viola del patrimonio culturale.
  beach:             "bg-[#06b6d4]",
  bay:               "bg-[#0ea5e9]",
  lake:              "bg-[#0284c7]",
  island:            "bg-[#14b8a6]",
  waterfall:         "bg-[#0891b2]",
  spring:            "bg-[#0d9488]",
  cave:              "bg-[#4b5563]",
  peak:              "bg-[#64748b]",
  cliff:             "bg-[#78716c]",
  glacier:           "bg-[#38bdf8]",
  volcano:           "bg-[#dc2626]",
  nature_reserve:    "bg-[#15803d]",
  natura:            "bg-[#16a34a]",
  lighthouse:        "bg-[#0369a1]",
  aerialway:         "bg-[#0284c7]",
  winery:            "bg-[#7f1d1d]",
  // Fase 2 — patrimonio costruito (toni caldi, coerenti col culturale),
  // musei tematici (viola come i musei), all'aperto (verdi), famiglie (ambra).
  square:            "bg-[#a16207]",
  bridge:            "bg-[#78716c]",
  fountain:          "bg-[#0891b2]",
  theatre:           "bg-[#9d174d]",
  opera_house:       "bg-[#831843]",
  palace:            "bg-[#92400e]",
  tower:             "bg-[#78350f]",
  skyscraper:        "bg-[#475569]",
  cemetery:          "bg-[#44403c]",
  library:           "bg-[#6d28d9]",
  windmill:          "bg-[#a16207]",
  aqueduct:          "bg-[#57534e]",
  observatory:       "bg-[#1e40af]",
  stadium:           "bg-[#166534]",
  monastery:         "bg-[#4338ca]",
  art_museum:        "bg-[#7c3aed]",
  natural_history_museum: "bg-[#7c3aed]",
  trail:             "bg-[#65a30d]",
  scenic_road:       "bg-[#84cc16]",
  tree:              "bg-[#15803d]",
  desert:            "bg-[#d97706]",
  forest:            "bg-[#166534]",
  garden:            "bg-[#22c55e]",
  aquarium:          "bg-[#0e7490]",
  water_park:        "bg-[#06b6d4]",
};

export const CATEGORY_HEX: Record<string, string> = {
  gemme:             "#0f766e",
  monumenti:         "#92400e",
  monument:          "#92400e",
  castle:            "#78350f",
  ruins:             "#57534e",
  archaeological_site: "#a16207",
  artwork:           "#be185d",
  fountain:          "#0ea5e9",
  chiese:            "#4338ca",
  church:            "#4338ca",
  musei:             "#7c3aed",
  museum:            "#7c3aed",
  panorami:          "#0369a1",
  viewpoint:         "#0369a1",
  locali:            "#e11d48",
  restaurant:        "#e11d48",
  utilita:           "#1e1b4b",
  famiglie:          "#b45309",
  esperienze_locali: "#ea580c",
  attraction:        "#16a34a",
  community:         "#ec4899",
  beni_culturali:    "#78716c",
  // Verticali naturali — stessi valori di CATEGORY_COLORS, in esadecimale
  // (usati dai marker Leaflet, che non passano da Tailwind).
  beach:             "#06b6d4",
  bay:               "#0ea5e9",
  lake:              "#0284c7",
  island:            "#14b8a6",
  waterfall:         "#0891b2",
  spring:            "#0d9488",
  cave:              "#4b5563",
  peak:              "#64748b",
  cliff:             "#78716c",
  glacier:           "#38bdf8",
  volcano:           "#dc2626",
  nature_reserve:    "#15803d",
  natura:            "#16a34a",
  lighthouse:        "#0369a1",
  aerialway:         "#0284c7",
  winery:            "#7f1d1d",
  // NB: `fountain` è già definito più sopra in questo stesso dizionario.
  square: "#a16207", bridge: "#78716c", theatre: "#9d174d",
  opera_house: "#831843", palace: "#92400e", tower: "#78350f", skyscraper: "#475569",
  cemetery: "#44403c", library: "#6d28d9", windmill: "#a16207", aqueduct: "#57534e",
  observatory: "#1e40af", stadium: "#166534", monastery: "#4338ca",
  art_museum: "#7c3aed", natural_history_museum: "#7c3aed",
  trail: "#65a30d", scenic_road: "#84cc16", tree: "#15803d", desert: "#d97706",
  forest: "#166534", garden: "#22c55e", aquarium: "#0e7490", water_park: "#06b6d4",
};

export const CATEGORY_EMOJIS: Record<string, string> = {
  gemme: "💎",
  community: "📸",
  beni_culturali: "🏺",
  monumenti: "🏛️",
  chiese: "⛪",
  musei: "🖼️",
  panorami: "🌄",
  locali: "🍽️",
  utilita: "🛠️",
  famiglie: "👨‍👩‍👧‍👦",
  esperienze_locali: "🏺",
  eventi: "🎪",
  historic: "📜",
  amenity: "🛋️",
  leisure: "⚽",
  tourism: "📍",
  shop: "🛍️",
  craft: "🏺",
  railway: "🚂",
  highway: "🛣️",
  church: "⛪",
  museum: "🖼️",
  viewpoint: "🌄",
  castle: "🏰",
  monument: "🏛️",
  ruins: "🏚️",
  archaeological_site: "⚱️",
  artwork: "🎨",
  fountain: "⛲",
  attraction: "📍",
  restaurant: "🍽️",
  // Verticali naturali: ogni tipo ha la sua icona, così sulla mappa una
  // spiaggia si distingue da una grotta senza aprire la scheda.
  beach: "🏖️",
  bay: "🌊",
  lake: "🏞️",
  island: "🏝️",
  waterfall: "💧",
  spring: "♨️",
  cave: "🕳️",
  peak: "⛰️",
  cliff: "🧗",
  glacier: "🏔️",
  volcano: "🌋",
  nature_reserve: "🌳",
  natura: "🌿",
  lighthouse: "🗼",
  aerialway: "🚡",
  winery: "🍷",
  square: "🏙️", bridge: "🌉", theatre: "🎭", opera_house: "🎼", palace: "👑",
  tower: "🗼", skyscraper: "🏙️", cemetery: "⚰️", library: "📚", windmill: "🌾",
  aqueduct: "🏛️", observatory: "🔭", stadium: "🏟️", monastery: "🕍",
  art_museum: "🎨", natural_history_museum: "🦕",
  trail: "🥾", scenic_road: "🛣️", tree: "🌳", desert: "🏜️", forest: "🌲",
  garden: "🌺", aquarium: "🐠", water_park: "🎢",
};

export const SUB_CATEGORY_EMOJIS: Record<string, string> = {
  monumento: "🏛️",
  chiesa: "⛪",
  museo: "🖼️",
  panorama: "🌄",
  piazza: "🏙️",
  arte: "🎨",
  castle: "🏰",
  ruins: "🏚️",
  archaeological_site: "⚱️",
  artwork: "🎨",
  monument: "🏛️",
  attraction: "📍",
  church: "⛪",
  museum: "🖼️",
  viewpoint: "🌄",
  ristorante: "🍴",
  restaurant: "🍴",
  pizzeria: "🍕",
  pizza: "🍕",
  pesce: "🐟",
  carne: "🥩",
  sushi: "🍣",
  vegetariano: "🥬",
  bar: "☕",
  cafe: "☕",
  bar_caffe: "☕",
  gelateria: "🍦",
  gelati: "🍦",
  ice_cream: "🍦",
  fast_food: "🍔",
  pub: "🍺",
  glutenfree: "🌾",
  gluten_free_only: "🌾💯",
  gluten_free_options: "🌾",
  fontanella: "🚰",
  drinking_water: "🚰",
  bagni: "🚺🚹",
  toilets: "🚺🚹",
  farmacia: "💊",
  pharmacy: "💊",
  ospedale: "🏥",
  hospital: "🏥",
  taxi: "🚕",
  stazione_ferroviaria: "🚂",
  stazione_fs: "🚂",
  station: "🚂",
  casello_autostradale: "🛣️",
  metropolitana: "🚇",
  metro: "🚇",
  subway_entrance: "🚇",
  aeroporto: "🛫",
  autostrada: "🛣️",
  motorway_junction: "🛣️",
  police: "👮",
  post_office: "📮",
  parco_giochi: "🛝",
  playground: "🛝",
  parco_divertimenti: "🎢",
  theme_park: "🎢",
  divertimento: "🎢",
  acquario: "🐬",
  aquarium: "🐬",
  zoo: "🦁",
  artigianato: "🏺",
  mercato: "🎪",
  gastronomia: "🧀",
  winery: "🍷",
  craft: "🏺",
  marketplace: "🧺",
  bakery: "🥖",
  deli: "🧀",
  cheese: "🧀",
  pasta: "🍝",
  wine: "🍷",
  farm: "🚜"
};

export const CATEGORY_GRADIENT: Record<string, string> = {
  gemme: "from-teal-900 via-teal-800 to-emerald-700",
  monumenti: "from-amber-950 via-amber-900 to-amber-800",
  castle: "from-amber-950 via-amber-900 to-amber-800",
  ruins: "from-stone-800 via-stone-700 to-stone-600",
  archaeological_site: "from-yellow-900 via-amber-800 to-amber-700",
  monument: "from-amber-950 via-amber-900 to-amber-800",
  chiese: "from-indigo-900 via-indigo-800 to-violet-800",
  church: "from-indigo-900 via-indigo-800 to-violet-800",
  musei: "from-violet-950 via-violet-900 to-purple-800",
  museum: "from-violet-950 via-violet-900 to-purple-800",
  panorami: "from-sky-900 via-sky-800 to-blue-700",
  viewpoint: "from-sky-900 via-sky-800 to-blue-700",
  locali: "from-rose-900 via-rose-800 to-pink-800",
  restaurant: "from-rose-900 via-rose-800 to-pink-800",
  utilita: "from-slate-900 via-slate-800 to-slate-700",
  famiglie: "from-orange-900 via-orange-800 to-amber-700",
  esperienze_locali: "from-orange-800 via-amber-700 to-yellow-700",
  artwork: "from-pink-900 via-pink-800 to-rose-700",
  attraction: "from-green-900 via-green-800 to-emerald-700",
  community: "from-pink-900 via-pink-800 to-fuchsia-800",
  beni_culturali: "from-stone-800 via-stone-700 to-neutral-600",
};
