// =====================================================================
// ITAINTA · Costanti Mappa e Categorie (Centralizzate)
// Per evitare dipendenze circolari tra MapArea, PoiPopupContent, ecc.
// =====================================================================

export const CATEGORY_COLORS: Record<string, string> = {
  gemme:             "bg-[#0f766e]",
  monumenti:         "bg-[#92400e]",
  chiese:            "bg-[#4338ca]",
  musei:             "bg-[#7c3aed]",
  panorami:          "bg-[#0369a1]",
  locali:            "bg-[#e11d48]",
  utilita:           "bg-[#1e1b4b]",
  famiglie:          "bg-[#b45309]",
  esperienze_locali: "bg-[#ea580c]",
  eventi:            "bg-[#7e22ce]",
  church:            "bg-[#4338ca]",
  museum:            "bg-[#7c3aed]",
  viewpoint:         "bg-[#0369a1]",
  castle:            "bg-[#78350f]",
  monument:          "bg-[#92400e]",
  ruins:             "bg-[#57534e]",
  archaeological_site: "bg-[#a16207]",
  artwork:           "bg-[#be185d]",
  attraction:        "bg-[#16a34a]",
  restaurant:        "bg-[#e11d48]",
};

export const CATEGORY_HEX: Record<string, string> = {
  gemme:             "#0f766e",
  monumenti:         "#92400e",
  monument:          "#92400e",
  castle:            "#78350f",
  ruins:             "#57534e",
  archaeological_site: "#a16207",
  artwork:           "#be185d",
  fountain:          "#0ea5e9",
  chiese:            "#4338ca",
  church:            "#4338ca",
  musei:             "#7c3aed",
  museum:            "#7c3aed",
  panorami:          "#0369a1",
  viewpoint:         "#0369a1",
  locali:            "#e11d48",
  restaurant:        "#e11d48",
  utilita:           "#1e1b4b",
  famiglie:          "#b45309",
  esperienze_locali: "#ea580c",
  attraction:        "#16a34a",
};

export const CATEGORY_EMOJIS: Record<string, string> = {
  gemme: "💎",
  monumenti: "🏛️",
  chiese: "⛪",
  musei: "🖼️",
  panorami: "🌄",
  locali: "🍽️",
  utilita: "🛠️",
  famiglie: "👨‍👩‍👧‍👦",
  esperienze_locali: "🏺",
  eventi: "🎪",
  historic: "📜",
  amenity: "🛋️",
  leisure: "⚽",
  tourism: "📍",
  shop: "🛍️",
  craft: "🏺",
  railway: "🚂",
  highway: "🛣️",
  church: "⛪",
  museum: "🖼️",
  viewpoint: "🌄",
  castle: "🏰",
  monument: "🏛️",
  ruins: "🏚️",
  archaeological_site: "⚱️",
  artwork: "🎨",
  fountain: "⛲",
  attraction: "📍",
  restaurant: "🍽️",
};

export const SUB_CATEGORY_EMOJIS: Record<string, string> = {
  monumento: "🏛️",
  chiesa: "⛪",
  museo: "🖼️",
  panorama: "🌄",
  piazza: "🏙️",
  arte: "🎨",
  castle: "🏰",
  ruins: "🏚️",
  archaeological_site: "⚱️",
  artwork: "🎨",
  monument: "🏛️",
  attraction: "📍",
  church: "⛪",
  museum: "🖼️",
  viewpoint: "🌄",
  ristorante: "🍴",
  restaurant: "🍴",
  pizzeria: "🍕",
  pizza: "🍕",
  pesce: "🐟",
  carne: "🥩",
  sushi: "🍣",
  vegetariano: "🥬",
  bar: "☕",
  cafe: "☕",
  bar_caffe: "☕",
  gelateria: "🍦",
  gelati: "🍦",
  ice_cream: "🍦",
  fast_food: "🍔",
  pub: "🍺",
  glutenfree: "🌾",
  gluten_free_only: "🌾💯",
  gluten_free_options: "🌾",
  fontanella: "🚰",
  drinking_water: "🚰",
  bagni: "🚺🚹",
  toilets: "🚺🚹",
  farmacia: "💊",
  pharmacy: "💊",
  ospedale: "🏥",
  hospital: "🏥",
  taxi: "🚕",
  stazione_ferroviaria: "🚂",
  stazione_fs: "🚂",
  station: "🚂",
  casello_autostradale: "🛣️",
  metropolitana: "🚇",
  metro: "🚇",
  subway_entrance: "🚇",
  aeroporto: "🛫",
  autostrada: "🛣️",
  motorway_junction: "🛣️",
  police: "👮",
  post_office: "📮",
  parco_giochi: "🛝",
  playground: "🛝",
  parco_divertimenti: "🎢",
  theme_park: "🎢",
  divertimento: "🎢",
  acquario: "🐬",
  aquarium: "🐬",
  zoo: "🦁",
  artigianato: "🏺",
  mercato: "🎪",
  gastronomia: "🧀",
  winery: "🍷",
  craft: "🏺",
  marketplace: "🧺",
  bakery: "🥖",
  deli: "🧀",
  cheese: "🧀",
  pasta: "🍝",
  wine: "🍷",
  farm: "🚜"
};

export const CATEGORY_GRADIENT: Record<string, string> = {
  gemme: "from-teal-900 via-teal-800 to-emerald-700",
  monumenti: "from-amber-950 via-amber-900 to-amber-800",
  castle: "from-amber-950 via-amber-900 to-amber-800",
  ruins: "from-stone-800 via-stone-700 to-stone-600",
  archaeological_site: "from-yellow-900 via-amber-800 to-amber-700",
  monument: "from-amber-950 via-amber-900 to-amber-800",
  chiese: "from-indigo-900 via-indigo-800 to-violet-800",
  church: "from-indigo-900 via-indigo-800 to-violet-800",
  musei: "from-violet-950 via-violet-900 to-purple-800",
  museum: "from-violet-950 via-violet-900 to-purple-800",
  panorami: "from-sky-900 via-sky-800 to-blue-700",
  viewpoint: "from-sky-900 via-sky-800 to-blue-700",
  locali: "from-rose-900 via-rose-800 to-pink-800",
  restaurant: "from-rose-900 via-rose-800 to-pink-800",
  utilita: "from-slate-900 via-slate-800 to-slate-700",
  famiglie: "from-orange-900 via-orange-800 to-amber-700",
  esperienze_locali: "from-orange-800 via-amber-700 to-yellow-700",
  artwork: "from-pink-900 via-pink-800 to-rose-700",
  attraction: "from-green-900 via-green-800 to-emerald-700",
};
