import type { Language } from '../i18n';

// Chiavi della bonifica lingua 24/08/2026 — area: radar/giro/nav/day pass
// (PoiRadarPanel, TourBanner, RoutePoisModal, DayPass*, dayPassService…).
export const TRAD_GIRO: Record<string, Partial<Record<Language, string>>> = {
  // Arrivo a una tappa SENZA audioguida (pranzo, pausa, trasferimento): si
  // annuncia il nome e si tace. Fa parte del giro, non ha una storia.
  tour_sei_arrivato: {
    IT: "Sei arrivato a", EN: "You've arrived at", FR: "Vous êtes arrivé à",
    ES: "Has llegado a", DE: "Du bist angekommen bei", RU: "Вы прибыли в", ZH: "你已到达",
  },
  // ── Giro in corso: il tasto d'avvio della navigazione sulla mappa ──
  tour_naviga: {
    IT: 'Naviga verso la tappa',
    EN: 'Navigate to the stop',
    FR: "Naviguer vers l'étape",
    ES: 'Navegar hasta la parada',
    DE: 'Zur Station navigieren',
    RU: 'Проложить маршрут к точке',
    ZH: '导航到该站点',
  },
  // Il pass c'e` ma il server non l'ha riconosciuto (28/08/2026): si dice
  // questo, non «attiva il Day Pass» a chi l'ha appena pagato.
  gr_pass_non_riconosciuto: {
    IT: 'Il tuo Day Pass è attivo, ma il server non lo ha riconosciuto.',
    EN: 'Your Day Pass is active, but the server did not recognise it.',
    FR: "Votre Day Pass est actif, mais le serveur ne l'a pas reconnu.",
    ES: 'Tu Day Pass está activo, pero el servidor no lo ha reconocido.',
    DE: 'Dein Day Pass ist aktiv, aber der Server hat ihn nicht erkannt.',
    RU: 'Ваш Day Pass активен, но сервер его не распознал.',
    ZH: '你的 Day Pass 已激活，但服务器未能识别。',
  },
  gr_riprova: {
    IT: 'Riprova', EN: 'Retry', FR: 'Réessayer', ES: 'Reintentar', DE: 'Erneut versuchen', RU: 'Повторить', ZH: '重试',
  },
  // Il tasto sulla mappa che avvia il giro intero dalle tappe scelte
  // (28/08/2026): «Crea il giro» stava solo nel pannello.
  gr_avvia_giro: {
    IT: 'Avvia il giro', EN: 'Start the tour', FR: 'Démarrer le parcours', ES: 'Iniciar el recorrido', DE: 'Tour starten', RU: 'Начать маршрут', ZH: '开始行程',
  },
  // Avvio ESPLICITO del giro (28/08/2026): creato = pronto e fermo; la
  // navigazione parte solo con questo tasto.
  gr_avvia_navigazione: {
    IT: 'Avvia la navigazione', EN: 'Start navigation', FR: 'Démarrer la navigation', ES: 'Iniciar la navegación', DE: 'Navigation starten', RU: 'Начать навигацию', ZH: '开始导航',
  },
  gr_pronto_a_partire: {
    IT: 'Pronto a partire', EN: 'Ready to go', FR: 'Prêt à partir', ES: 'Listo para salir', DE: 'Startbereit', RU: 'Готов к старту', ZH: '准备出发',
  },
  // Il tasto sul giorno dell'itinerario che lo porta nel radar della mappa.
  gr_nel_radar: {
    IT: 'Nel radar', EN: 'To the radar', FR: 'Vers le radar', ES: 'Al radar', DE: 'Ins Radar', RU: 'В радар', ZH: '加入雷达',
  },
  // Ad anello, dopo l'ultima tappa: la meta` e` il punto di partenza.
  tour_ritorno_partenza: {
    IT: 'Ritorno al punto di partenza',
    EN: 'Back to the starting point',
    FR: 'Retour au point de départ',
    ES: 'Vuelta al punto de partida',
    DE: 'Zurück zum Startpunkt',
    RU: 'Возвращение к точке старта',
    ZH: '返回出发点',
  },
  // La pillola sulla linea d'aria di ripiego: dice che NON e` un percorso.
  gr_linea_stimata: {
    IT: 'tracciato stimato',
    EN: 'estimated line',
    FR: 'tracé estimé',
    ES: 'trazado estimado',
    DE: 'geschätzte Linie',
    RU: 'приблизительная линия',
    ZH: '估算路线',
  },
  gr_linea_stimata_pass: {
    IT: 'tracciato stimato · serve il Day Pass',
    EN: 'estimated line · Day Pass required',
    FR: 'tracé estimé · Day Pass requis',
    ES: 'trazado estimado · se necesita el Day Pass',
    DE: 'geschätzte Linie · Day Pass nötig',
    RU: 'приблизительная линия · нужен Day Pass',
    ZH: '估算路线 · 需要 Day Pass',
  },
  /**
   * La terza chip di «Arrivo»: anello che si chiude dove ci si trova adesso
   * invece che sul punto di partenza. La differenza si vede solo dopo un
   * ricalcolo per strada, ed e` per quello che esiste.
   */
  gr_torno_dove_sono: {
    IT: 'Torno dove mi trovo',
    EN: 'Loop from where I am',
    FR: "Boucle depuis l'endroit où je suis",
    ES: 'Vuelvo a donde estoy',
    DE: 'Rundweg von meinem Standort',
    RU: 'Возврат туда, где я сейчас',
    ZH: '回到我当前位置',
  },
  gr_finisci_a_distanza: {
    IT: 'finisci a {d} dal punto di partenza',
    EN: 'you finish {d} from your starting point',
    FR: 'vous terminez à {d} du point de départ',
    ES: 'terminas a {d} del punto de partida',
    DE: 'du endest {d} vom Startpunkt entfernt',
    RU: 'финиш в {d} от точки старта',
    ZH: '终点距出发点 {d}',
  },
  // ── PoiRadarPanel ──
  gr_tempo_tutto: { IT: 'Tutto', EN: 'All', FR: 'Tout', ES: 'Todo', DE: 'Alles', RU: 'Всё', ZH: '全部' },
  gr_giro_pieno: {
    IT: 'Giro pieno: dieci tappe al massimo.',
    EN: 'Tour full: ten stops at most.',
    FR: 'Parcours complet : dix étapes au maximum.',
    ES: 'Recorrido completo: diez paradas como máximo.',
    DE: 'Rundgang voll: höchstens zehn Stationen.',
    RU: 'Маршрут заполнен: не более десяти точек.',
    ZH: '路线已满：最多十个站点。',
  },
  gr_pass_richiesto: {
    IT: 'Il giro a piu` tappe e` incluso nel Day Pass. Attivalo dal profilo per usarlo.',
    EN: 'The multi-stop tour is included in the Day Pass. Activate it from your profile to use it.',
    FR: "Le parcours à plusieurs étapes est inclus dans le Day Pass. Activez-le depuis votre profil pour l'utiliser.",
    ES: 'El recorrido de varias paradas está incluido en el Day Pass. Actívalo desde tu perfil para usarlo.',
    DE: 'Der Rundgang mit mehreren Stationen ist im Day Pass enthalten. Aktiviere ihn im Profil, um ihn zu nutzen.',
    RU: 'Маршрут с несколькими точками входит в Day Pass. Активируйте его в профиле, чтобы им пользоваться.',
    ZH: '多站点路线包含在 Day Pass 中。请在个人资料中激活后使用。',
  },
  // Cruscotto: ridurre a barretta / riaprire, e la conferma prima di chiudere il giro.
  gr_riduci_cruscotto: {
    IT: 'Riduci il cruscotto', EN: 'Minimise the dashboard', FR: 'Réduire le tableau de bord',
    ES: 'Reducir el panel', DE: 'Cockpit verkleinern', RU: 'Свернуть панель', ZH: '收起面板',
  },
  gr_espandi_cruscotto: {
    IT: 'Apri il cruscotto', EN: 'Open the dashboard', FR: 'Ouvrir le tableau de bord',
    ES: 'Abrir el panel', DE: 'Cockpit öffnen', RU: 'Развернуть панель', ZH: '展开面板',
  },
  gr_chiudi_giro_conferma: {
    IT: 'Chiudere il giro? Tappe fatte e percorso andranno persi. Per nasconderlo e basta usa la freccia in basso.',
    EN: 'End the tour? Completed stops and the route will be lost. To just hide it, use the arrow at the bottom.',
    FR: "Terminer le parcours ? Les étapes faites et l'itinéraire seront perdus. Pour seulement le masquer, utilisez la flèche en bas.",
    ES: 'Terminar el recorrido? Las paradas hechas y la ruta se perderán. Para solo ocultarlo usa la flecha de abajo.',
    DE: 'Rundgang beenden? Erledigte Stationen und Route gehen verloren. Zum Ausblenden den Pfeil unten verwenden.',
    RU: 'Завершить маршрут? Пройденные точки и путь будут потеряны. Чтобы просто скрыть, нажмите стрелку внизу.',
    ZH: '结束路线？已完成的站点和路径将丢失。只想隐藏请用底部箭头。',
  },
  gr_giro_non_riuscito: {
    IT: 'Giro non riuscito.',
    EN: 'Could not create the tour.',
    FR: 'Échec de la création du parcours.',
    ES: 'No se pudo crear el recorrido.',
    DE: 'Rundgang fehlgeschlagen.',
    RU: 'Не удалось создать маршрут.',
    ZH: '路线创建失败。',
  },
  gr_calcolo_percorso: {
    IT: 'Calcolo il percorso…',
    EN: 'Calculating the route…',
    FR: "Calcul de l'itinéraire…",
    ES: 'Calculando la ruta…',
    DE: 'Route wird berechnet…',
    RU: 'Расчёт маршрута…',
    ZH: '正在计算路线…',
  },
  gr_anteprima_pass: {
    IT: 'Anteprima del percorso col Day Pass: le tappe restano scelte.',
    EN: 'Route preview comes with the Day Pass: your stops stay selected.',
    FR: "Aperçu de l'itinéraire avec le Day Pass : vos étapes restent sélectionnées.",
    ES: 'La vista previa de la ruta llega con el Day Pass: tus paradas siguen seleccionadas.',
    DE: 'Routenvorschau mit dem Day Pass: deine Stationen bleiben ausgewählt.',
    RU: 'Предпросмотр маршрута — с Day Pass: выбранные точки сохраняются.',
    ZH: '路线预览需要 Day Pass：已选站点会保留。',
  },
  gr_serve_posizione: {
    IT: 'Serve la posizione per disegnare il percorso da dove sei.',
    EN: 'Your location is needed to draw the route from where you are.',
    FR: "Votre position est nécessaire pour tracer l'itinéraire depuis là où vous êtes.",
    ES: 'Se necesita tu ubicación para trazar la ruta desde donde estás.',
    DE: 'Dein Standort wird benötigt, um die Route von dort zu zeichnen, wo du bist.',
    RU: 'Нужна геопозиция, чтобы построить маршрут от вашего местоположения.',
    ZH: '需要你的位置才能从你所在地绘制路线。',
  },
  gr_min_a_piedi: {
    IT: 'min a piedi',
    EN: 'min on foot',
    FR: 'min à pied',
    ES: 'min a pie',
    DE: 'Min. zu Fuß',
    RU: 'мин пешком',
    ZH: '分钟步行',
  },
  gr_anello_da_dove_sei: {
    IT: 'ad anello da dove sei',
    EN: 'loop from where you are',
    FR: 'en boucle depuis là où vous êtes',
    ES: 'circular desde donde estás',
    DE: 'Rundweg von deinem Standort',
    RU: 'кольцом от вашего местоположения',
    ZH: '从你所在地环形往返',
  },
  gr_fino_ultima_tappa: {
    IT: 'da dove sei all’ultima tappa',
    EN: 'from where you are to the last stop',
    FR: 'de là où vous êtes à la dernière étape',
    ES: 'desde donde estás hasta la última parada',
    DE: 'von deinem Standort bis zur letzten Station',
    RU: 'от вашего местоположения до последней точки',
    ZH: '从你所在地到最后一站',
  },
  gr_wipnav_ordina: {
    IT: 'WIP Nav mette le tappe nell’ordine che fa camminare meno',
    EN: 'WIP Nav orders the stops so you walk the least',
    FR: 'WIP Nav ordonne les étapes pour marcher le moins possible',
    ES: 'WIP Nav ordena las paradas para caminar lo menos posible',
    DE: 'WIP Nav ordnet die Stationen so, dass du am wenigsten läufst',
    RU: 'WIP Nav расставляет точки так, чтобы идти меньше',
    ZH: 'WIP Nav 会按最省脚力的顺序排列站点',
  },
  gr_radar_titolo: {
    IT: 'Radar Audioguida',
    EN: 'Audio Guide Radar',
    FR: 'Radar Audioguide',
    ES: 'Radar Audioguía',
    DE: 'Audioguide-Radar',
    RU: 'Радар аудиогида',
    ZH: '语音导览雷达',
  },
  gr_luoghi_monitorati: {
    IT: '{n} luoghi monitorati',
    EN: '{n} places monitored',
    FR: '{n} lieux surveillés',
    ES: '{n} lugares monitorizados',
    DE: '{n} überwachte Orte',
    RU: 'отслеживается мест: {n}',
    ZH: '正在监测 {n} 个地点',
  },
  gr_tappa_scelta: {
    IT: 'tappa scelta',
    EN: 'stop selected',
    FR: 'étape choisie',
    ES: 'parada elegida',
    DE: 'Station ausgewählt',
    RU: 'точка выбрана',
    ZH: '个已选站点',
  },
  gr_tappe_scelte: {
    IT: 'tappe scelte',
    EN: 'stops selected',
    FR: 'étapes choisies',
    ES: 'paradas elegidas',
    DE: 'Stationen ausgewählt',
    RU: 'точек выбрано',
    ZH: '个已选站点',
  },
  gr_massimo: { IT: 'massimo', EN: 'maximum', FR: 'maximum', ES: 'máximo', DE: 'Maximum', RU: 'максимум', ZH: '已达上限' },
  gr_annulla: { IT: 'Annulla', EN: 'Cancel', FR: 'Annuler', ES: 'Cancelar', DE: 'Abbrechen', RU: 'Отмена', ZH: '取消' },
  gr_calcolo: { IT: 'Calcolo…', EN: 'Calculating…', FR: 'Calcul…', ES: 'Calculando…', DE: 'Berechne…', RU: 'Расчёт…', ZH: '计算中…' },
  gr_crea_giro: {
    IT: 'Crea il giro',
    EN: 'Create the tour',
    FR: 'Créer le parcours',
    ES: 'Crear el recorrido',
    DE: 'Rundgang erstellen',
    RU: 'Создать маршрут',
    ZH: '创建路线',
  },
  gr_crea_giro_n: {
    IT: 'Crea il giro ({n})',
    EN: 'Create the tour ({n})',
    FR: 'Créer le parcours ({n})',
    ES: 'Crear el recorrido ({n})',
    DE: 'Rundgang erstellen ({n})',
    RU: 'Создать маршрут ({n})',
    ZH: '创建路线（{n}）',
  },
  gr_daypass_incluso: {
    IT: 'Il giro a più tappe e l’ascolto fluido — avviso, teaser e audioguida da soli — sono inclusi nel Day Pass.',
    EN: 'The multi-stop tour and seamless listening — alert, teaser and audio guide on their own — are included in the Day Pass.',
    FR: "Le parcours à plusieurs étapes et l'écoute fluide — alerte, teaser et audioguide tout seuls — sont inclus dans le Day Pass.",
    ES: 'El recorrido de varias paradas y la escucha fluida — aviso, teaser y audioguía por sí solos — están incluidos en el Day Pass.',
    DE: 'Der Rundgang mit mehreren Stationen und das nahtlose Hören — Hinweis, Teaser und Audioguide von allein — sind im Day Pass enthalten.',
    RU: 'Маршрут с несколькими точками и плавное прослушивание — уведомление, тизер и аудиогид сами по себе — входят в Day Pass.',
    ZH: '多站点路线和流畅收听（提醒、预告和语音导览自动播放）都包含在 Day Pass 中。',
  },
  gr_attiva_daypass: {
    IT: 'Attiva il Day Pass',
    EN: 'Activate the Day Pass',
    FR: 'Activer le Day Pass',
    ES: 'Activa el Day Pass',
    DE: 'Day Pass aktivieren',
    RU: 'Активировать Day Pass',
    ZH: '激活 Day Pass',
  },
  gr_tempo_che_hai: {
    IT: 'Tempo che hai',
    EN: 'Time you have',
    FR: 'Temps disponible',
    ES: 'Tiempo que tienes',
    DE: 'Deine Zeit',
    RU: 'Сколько у вас времени',
    ZH: '可用时间',
  },
  gr_arrivo: { IT: 'Arrivo', EN: 'Finish', FR: 'Arrivée', ES: 'Llegada', DE: 'Ziel', RU: 'Финиш', ZH: '终点' },
  gr_torno_da_dove_parto: {
    IT: '🔁 Torno da dove parto',
    EN: '🔁 Back to where I start',
    FR: '🔁 Retour au point de départ',
    ES: '🔁 Vuelvo a donde empiezo',
    DE: '🔁 Zurück zum Start',
    RU: '🔁 Вернусь к началу',
    ZH: '🔁 回到出发点',
  },
  gr_finisco_ultima: {
    IT: '🏁 Finisco all’ultima tappa',
    EN: '🏁 Finish at the last stop',
    FR: '🏁 Terminer à la dernière étape',
    ES: '🏁 Termino en la última parada',
    DE: '🏁 An der letzten Station enden',
    RU: '🏁 Закончу на последней точке',
    ZH: '🏁 在最后一站结束',
  },
  gr_tempo_ci_sta_1: {
    IT: 'Nel tempo che hai ci sta 1 tappa su {m}: le altre restano fuori dal giro.',
    EN: 'In the time you have, 1 stop out of {m} fits: the others stay out of the tour.',
    FR: 'Dans le temps dont vous disposez, 1 étape sur {m} tient : les autres restent hors du parcours.',
    ES: 'En el tiempo que tienes cabe 1 parada de {m}: las demás quedan fuera del recorrido.',
    DE: 'In deiner Zeit passt 1 von {m} Stationen: die anderen bleiben außen vor.',
    RU: 'В ваше время помещается 1 точка из {m}: остальные останутся вне маршрута.',
    ZH: '在你的时间里只能安排 {m} 站中的 1 站：其余不列入路线。',
  },
  gr_tempo_ci_stanno_n: {
    IT: 'Nel tempo che hai ci stanno {n} tappe su {m}: le altre restano fuori dal giro.',
    EN: 'In the time you have, {n} stops out of {m} fit: the others stay out of the tour.',
    FR: 'Dans le temps dont vous disposez, {n} étapes sur {m} tiennent : les autres restent hors du parcours.',
    ES: 'En el tiempo que tienes caben {n} paradas de {m}: las demás quedan fuera del recorrido.',
    DE: 'In deiner Zeit passen {n} von {m} Stationen: die anderen bleiben außen vor.',
    RU: 'В ваше время помещаются {n} точек из {m}: остальные останутся вне маршрута.',
    ZH: '在你的时间里能安排 {m} 站中的 {n} 站：其余不列入路线。',
  },
  gr_ordine_trascina: {
    IT: 'Ordine del giro · trascina per cambiarlo',
    EN: 'Tour order · drag to change it',
    FR: 'Ordre du parcours · glissez pour le changer',
    ES: 'Orden del recorrido · arrastra para cambiarlo',
    DE: 'Reihenfolge · zum Ändern ziehen',
    RU: 'Порядок маршрута · перетащите, чтобы изменить',
    ZH: '路线顺序 · 拖动即可调整',
  },
  gr_riordina_per_me: {
    IT: 'Riordina per me',
    EN: 'Reorder for me',
    FR: 'Réordonner pour moi',
    ES: 'Reordenar por mí',
    DE: 'Für mich sortieren',
    RU: 'Упорядочить за меня',
    ZH: '帮我重新排序',
  },
  gr_fuori_tempo: {
    IT: 'fuori tempo',
    EN: 'out of time',
    FR: 'hors délai',
    ES: 'fuera de tiempo',
    DE: 'außerhalb der Zeit',
    RU: 'не по времени',
    ZH: '超出时间',
  },
  gr_togli_dal_giro: {
    IT: 'Togli dal giro',
    EN: 'Remove from the tour',
    FR: 'Retirer du parcours',
    ES: 'Quitar del recorrido',
    DE: 'Aus dem Rundgang entfernen',
    RU: 'Убрать из маршрута',
    ZH: '从路线中移除',
  },
  gr_lungo_strada_1: {
    IT: 'Lungo la strada · 1 posto che il giro sfiora',
    EN: 'Along the way · 1 place the tour brushes past',
    FR: 'En chemin · 1 lieu que le parcours frôle',
    ES: 'Por el camino · 1 lugar que el recorrido roza',
    DE: 'Unterwegs · 1 Ort, den der Rundgang streift',
    RU: 'По пути · 1 место рядом с маршрутом',
    ZH: '沿途 · 1 个路线擦身而过的地点',
  },
  gr_lungo_strada_n: {
    IT: 'Lungo la strada · {n} posti che il giro sfiora',
    EN: 'Along the way · {n} places the tour brushes past',
    FR: 'En chemin · {n} lieux que le parcours frôle',
    ES: 'Por el camino · {n} lugares que el recorrido roza',
    DE: 'Unterwegs · {n} Orte, die der Rundgang streift',
    RU: 'По пути · {n} мест рядом с маршрутом',
    ZH: '沿途 · {n} 个路线擦身而过的地点',
  },
  gr_cerco: { IT: 'cerco…', EN: 'searching…', FR: 'recherche…', ES: 'buscando…', DE: 'suche…', RU: 'ищу…', ZH: '搜索中…' },
  gr_dal_percorso: {
    IT: 'a {n} m dal percorso · km {x}',
    EN: '{n} m off the route · km {x}',
    FR: "à {n} m de l'itinéraire · km {x}",
    ES: 'a {n} m de la ruta · km {x}',
    DE: '{n} m von der Route · km {x}',
    RU: 'в {n} м от маршрута · км {x}',
    ZH: '距路线 {n} 米 · 第 {x} 公里',
  },
  gr_aggiungi_al_giro: {
    IT: 'Aggiungi al giro',
    EN: 'Add to the tour',
    FR: 'Ajouter au parcours',
    ES: 'Añadir al recorrido',
    DE: 'Zum Rundgang hinzufügen',
    RU: 'Добавить в маршрут',
    ZH: '加入路线',
  },
  gr_altri_passando: {
    IT: 'e altri {n}: li sentirai passando, se sono a meno di 40 m.',
    EN: "and {n} more: you'll hear them as you pass, if they are within 40 m.",
    FR: "et {n} autres : vous les entendrez en passant, s'ils sont à moins de 40 m.",
    ES: 'y otros {n}: los oirás al pasar, si están a menos de 40 m.',
    DE: 'und {n} weitere: du hörst sie im Vorbeigehen, wenn sie näher als 40 m sind.',
    RU: 'и ещё {n}: вы услышите их по пути, если они ближе 40 м.',
    ZH: '还有 {n} 个：经过时若距离不到 40 米，你会听到它们。',
  },
  gr_nessun_poi: {
    IT: 'Nessun POI attivo. Muoviti per trovarne di nuovi o controlla il Setup.',
    EN: 'No active POIs. Move around to find new ones or check the Setup.',
    FR: 'Aucun POI actif. Déplacez-vous pour en trouver de nouveaux ou vérifiez le Setup.',
    ES: 'Ningún POI activo. Muévete para encontrar nuevos o revisa el Setup.',
    DE: 'Keine aktiven POIs. Beweg dich, um neue zu finden, oder prüfe das Setup.',
    RU: 'Нет активных POI. Пройдитесь, чтобы найти новые, или проверьте Setup.',
    ZH: '没有活跃的 POI。四处走动寻找新的，或检查 Setup。',
  },

  // ── TourBanner ──
  gr_salvataggio_fallito: {
    IT: 'Salvataggio non riuscito',
    EN: 'Save failed',
    FR: "Échec de l'enregistrement",
    ES: 'No se pudo guardar',
    DE: 'Speichern fehlgeschlagen',
    RU: 'Не удалось сохранить',
    ZH: '保存失败',
  },
  gr_condivisione_fallita: {
    IT: 'Condivisione non riuscita',
    EN: 'Share failed',
    FR: 'Échec du partage',
    ES: 'No se pudo compartir',
    DE: 'Teilen fehlgeschlagen',
    RU: 'Не удалось поделиться',
    ZH: '分享失败',
  },
  gr_nuovo_giro_da_qui: {
    IT: 'Nuovo giro da qui →',
    EN: 'New tour from here →',
    FR: "Nouveau parcours d'ici →",
    ES: 'Nuevo recorrido desde aquí →',
    DE: 'Neuer Rundgang von hier →',
    RU: 'Новый маршрут отсюда →',
    ZH: '从这里开始新路线 →',
  },
  gr_poi_prossima: { IT: 'poi', EN: 'next', FR: 'ensuite', ES: 'después', DE: 'dann', RU: 'далее', ZH: '下一站' },
  gr_pioggia_probabile: {
    IT: 'pioggia probabile ({n}%)',
    EN: 'rain likely ({n}%)',
    FR: 'pluie probable ({n} %)',
    ES: 'lluvia probable ({n} %)',
    DE: 'Regen wahrscheinlich ({n} %)',
    RU: 'вероятен дождь ({n} %)',
    ZH: '可能降雨（{n}%）',
  },
  gr_arrivo_eta: { IT: 'arrivo', EN: 'ETA', FR: 'arrivée', ES: 'llegada', DE: 'Ankunft', RU: 'прибытие', ZH: '到达' },

  // ── PoiPopupContent (tasto giro) ──
  gr_nel_giro: {
    IT: 'Nel giro',
    EN: 'In the tour',
    FR: 'Dans le parcours',
    ES: 'En el recorrido',
    DE: 'Im Rundgang',
    RU: 'В маршруте',
    ZH: '已在路线中',
  },
  gr_rifaccio_percorso: {
    IT: 'Rifaccio il percorso…',
    EN: 'Recalculating the route…',
    FR: "Je recalcule l'itinéraire…",
    ES: 'Rehaciendo la ruta…',
    DE: 'Route wird neu berechnet…',
    RU: 'Пересчитываю маршрут…',
    ZH: '正在重新计算路线…',
  },
  gr_giro_pieno_dieci: {
    IT: 'Giro pieno (dieci tappe)',
    EN: 'Tour full (ten stops)',
    FR: 'Parcours complet (dix étapes)',
    ES: 'Recorrido completo (diez paradas)',
    DE: 'Rundgang voll (zehn Stationen)',
    RU: 'Маршрут заполнен (десять точек)',
    ZH: '路线已满（十个站点）',
  },
  gr_aggiungi_giro_in_corso: {
    IT: 'Aggiungi al giro in corso',
    EN: 'Add to the current tour',
    FR: 'Ajouter au parcours en cours',
    ES: 'Añadir al recorrido en curso',
    DE: 'Zum laufenden Rundgang hinzufügen',
    RU: 'Добавить в текущий маршрут',
    ZH: '加入当前路线',
  },

  // ── RoutePoisModal ──
  gr_percorso_lungo: {
    IT: "Il percorso è di oltre {km} km in linea d'aria: potrebbe richiedere molto tempo a piedi.",
    EN: 'The route is over {km} km in a straight line: it may take a long time on foot.',
    FR: "L'itinéraire fait plus de {km} km à vol d'oiseau : cela peut prendre beaucoup de temps à pied.",
    ES: 'La ruta supera los {km} km en línea recta: puede llevar mucho tiempo a pie.',
    DE: 'Die Strecke beträgt über {km} km Luftlinie: zu Fuß kann das sehr lange dauern.',
    RU: 'Маршрут — более {km} км по прямой: пешком это может занять много времени.',
    ZH: '路线直线距离超过 {km} 公里：步行可能需要很长时间。',
  },
  gr_wipnav_cose_1: {
    IT: "WIP Nav è il navigatore integrato dell'app: ti guida in tempo reale lungo i percorsi dell'itinerario con indicazioni vocali, e lungo la strada fa partire da sole le audioguide dei luoghi geofenzati che scegli qui sotto — senza uscire dall'app.",
    EN: "WIP Nav is the app's built-in navigator: it guides you in real time along your itinerary with voice directions, and automatically plays the audio guides of the geofenced places you select below — without leaving the app.",
    FR: "WIP Nav est le navigateur intégré de l'app : il vous guide en temps réel le long des parcours de l'itinéraire avec des indications vocales, et en chemin il lance tout seul les audioguides des lieux géorepérés que vous choisissez ci-dessous — sans quitter l'app.",
    ES: 'WIP Nav es el navegador integrado de la app: te guía en tiempo real por los recorridos del itinerario con indicaciones de voz, y por el camino reproduce solas las audioguías de los lugares geolocalizados que elijas aquí abajo — sin salir de la app.',
    DE: 'WIP Nav ist der integrierte Navigator der App: er führt dich in Echtzeit mit Sprachansagen entlang der Routen deiner Reise, und unterwegs startet er von selbst die Audioguides der Geofence-Orte, die du unten auswählst — ohne die App zu verlassen.',
    RU: 'WIP Nav — встроенный навигатор приложения: он в реальном времени ведёт вас по маршруту с голосовыми подсказками, а по пути сам запускает аудиогиды выбранных ниже мест с геозонами — не выходя из приложения.',
    ZH: 'WIP Nav 是应用内置的导航器：它通过语音指示实时引导你走完行程路线，沿途自动播放你在下方选择的地理围栏地点的语音导览 — 无需离开应用。',
  },
  gr_wipnav_cose_2: {
    IT: 'A differenza di Google Maps (navigatore stradale generalista punto-punto basato sul traffico), WIP Nav è ottimizzato per il turismo di prossimità: ascolto contestuale delle tracce audio e scoperta dei punti di interesse curati lungo il tracciato.',
    EN: 'Unlike Google Maps (a general-purpose point-to-point road navigator built around traffic), WIP Nav is optimized for proximity tourism: contextual audio playback and discovery of curated points of interest along your route.',
    FR: "Contrairement à Google Maps (navigateur routier généraliste point à point basé sur le trafic), WIP Nav est optimisé pour le tourisme de proximité : écoute contextuelle des pistes audio et découverte des points d'intérêt sélectionnés le long du tracé.",
    ES: 'A diferencia de Google Maps (navegador vial generalista punto a punto basado en el tráfico), WIP Nav está optimizado para el turismo de proximidad: escucha contextual de las pistas de audio y descubrimiento de puntos de interés seleccionados a lo largo del trazado.',
    DE: 'Anders als Google Maps (ein allgemeiner Punkt-zu-Punkt-Straßennavigator auf Verkehrsbasis) ist WIP Nav für den Nahtourismus optimiert: kontextbezogene Audiowiedergabe und Entdeckung kuratierter Sehenswürdigkeiten entlang der Strecke.',
    RU: 'В отличие от Google Maps (универсального дорожного навигатора «из точки в точку» на основе трафика), WIP Nav оптимизирован для туризма поблизости: контекстное воспроизведение аудио и открытие отобранных достопримечательностей вдоль маршрута.',
    ZH: '与 Google Maps（基于交通的通用点对点道路导航）不同，WIP Nav 为近距离旅游而优化：情境化播放音频，并沿途发现精选的兴趣点。',
  },
  gr_info: { IT: 'Info', EN: 'Info', FR: 'Infos', ES: 'Información', DE: 'Info', RU: 'Инфо', ZH: '信息' },
  gr_chiudi: { IT: 'Chiudi', EN: 'Close', FR: 'Fermer', ES: 'Cerrar', DE: 'Schließen', RU: 'Закрыть', ZH: '关闭' },

  // ── ApproachBanner ──
  gr_gemma: { IT: 'Gemma', EN: 'Gem', FR: 'Pépite', ES: 'Joya', DE: 'Juwel', RU: 'Жемчужина', ZH: '宝藏' },

  // ── GeofenceAudioGuide ──
  gr_tour_gruppo_finito: {
    IT: 'Il tour di gruppo è terminato.',
    EN: 'The group tour has ended.',
    FR: 'La visite de groupe est terminée.',
    ES: 'El tour de grupo ha terminado.',
    DE: 'Die Gruppentour ist beendet.',
    RU: 'Групповой тур завершён.',
    ZH: '团队导览已结束。',
  },
  gr_poi_caricati: {
    IT: '✅ {n} POI caricati nel radar. Ora puoi spegnere il display!',
    EN: '✅ {n} POIs loaded into the radar. You can turn off the display now!',
    FR: "✅ {n} POI chargés dans le radar. Vous pouvez maintenant éteindre l'écran !",
    ES: '✅ {n} POI cargados en el radar. ¡Ya puedes apagar la pantalla!',
    DE: '✅ {n} POIs im Radar geladen. Du kannst das Display jetzt ausschalten!',
    RU: '✅ {n} POI загружено в радар. Теперь можно выключить экран!',
    ZH: '✅ 已将 {n} 个 POI 加载到雷达。现在可以关闭屏幕了！',
  },

  // ── Day Pass (Card, Badge, OfferModal, dayPassService) ──
  gr_dp_confirm: {
    IT: "Attivare il WIP Day Pass?\n\n{costo} crediti — per 24 ore l'audioguida completa parte da sola quando ti avvicini a un luogo (fino a {cap} guide), anche offline e a schermo spento. Metti le cuffie e basta.",
    EN: 'Activate the WIP Day Pass?\n\n{costo} credits — for 24 hours the full audio guide starts on its own when you approach a place (up to {cap} guides), even offline and with the screen off. Just put on your headphones.',
    FR: "Activer le WIP Day Pass ?\n\n{costo} crédits — pendant 24 heures, l'audioguide complet démarre tout seul quand vous approchez d'un lieu (jusqu'à {cap} guides), même hors ligne et écran éteint. Mettez vos écouteurs, c'est tout.",
    ES: '¿Activar el WIP Day Pass?\n\n{costo} créditos — durante 24 horas la audioguía completa arranca sola cuando te acercas a un lugar (hasta {cap} guías), incluso sin conexión y con la pantalla apagada. Ponte los auriculares y ya está.',
    DE: 'Den WIP Day Pass aktivieren?\n\n{costo} Credits — 24 Stunden lang startet der komplette Audioguide von selbst, wenn du dich einem Ort näherst (bis zu {cap} Guides), auch offline und bei ausgeschaltetem Display. Einfach Kopfhörer aufsetzen.',
    RU: 'Активировать WIP Day Pass?\n\n{costo} кредитов — 24 часа полный аудиогид запускается сам, когда вы подходите к месту (до {cap} гидов), даже офлайн и с выключенным экраном. Просто наденьте наушники.',
    ZH: '激活 WIP Day Pass？\n\n{costo} 积分 — 24 小时内，当你靠近某个地点时，完整语音导览会自动播放（最多 {cap} 次），离线和熄屏也能用。戴上耳机就行。',
  },
  gr_dp_attivo_notify: {
    IT: 'Day Pass attivo! Per 24 ore non devi fare più nulla: solo attivare le cuffie.',
    EN: "Day Pass active! For 24 hours you don't have to do anything else: just put on your headphones.",
    FR: "Day Pass actif ! Pendant 24 heures, vous n'avez plus rien à faire : juste mettre vos écouteurs.",
    ES: '¡Day Pass activo! Durante 24 horas no tienes que hacer nada más: solo ponerte los auriculares.',
    DE: 'Day Pass aktiv! 24 Stunden lang musst du nichts mehr tun: nur Kopfhörer aufsetzen.',
    RU: 'Day Pass активен! 24 часа ничего не нужно делать — только наденьте наушники.',
    ZH: 'Day Pass 已激活！24 小时内什么都不用做：戴上耳机即可。',
  },
  gr_dp_attivazione_fallita: {
    IT: 'Attivazione non riuscita.',
    EN: 'Activation failed.',
    FR: "Échec de l'activation.",
    ES: 'No se pudo activar.',
    DE: 'Aktivierung fehlgeschlagen.',
    RU: 'Не удалось активировать.',
    ZH: '激活失败。',
  },
  gr_dp_stato_attivo: {
    IT: 'Attivo — {n} guide rimaste, scade alle {ora}',
    EN: 'Active — {n} guides left, expires at {ora}',
    FR: 'Actif — {n} guides restants, expire à {ora}',
    ES: 'Activo — quedan {n} guías, caduca a las {ora}',
    DE: 'Aktiv — {n} Guides übrig, läuft um {ora} ab',
    RU: 'Активен — осталось {n} гидов, истекает в {ora}',
    ZH: '已激活 — 剩余 {n} 次导览，{ora} 到期',
  },
  gr_dp_pitch: {
    IT: '24 ore hands-free: avviso, teaser e audioguida completa automatici (fino a {cap} guide), anche offline e a schermo spento.',
    EN: '24 hours hands-free: automatic alert, teaser and full audio guide (up to {cap} guides), even offline and with the screen off.',
    FR: "24 heures mains libres : alerte, teaser et audioguide complet automatiques (jusqu'à {cap} guides), même hors ligne et écran éteint.",
    ES: '24 horas manos libres: aviso, teaser y audioguía completa automáticos (hasta {cap} guías), incluso sin conexión y con la pantalla apagada.',
    DE: '24 Stunden hands-free: Hinweis, Teaser und kompletter Audioguide automatisch (bis zu {cap} Guides), auch offline und bei ausgeschaltetem Display.',
    RU: '24 часа hands-free: уведомление, тизер и полный аудиогид автоматически (до {cap} гидов), даже офлайн и с выключенным экраном.',
    ZH: '24 小时解放双手：自动提醒、预告和完整语音导览（最多 {cap} 次），离线和熄屏也能用。',
  },
  gr_dp_crediti: {
    IT: '{n} crediti',
    EN: '{n} credits',
    FR: '{n} crédits',
    ES: '{n} créditos',
    DE: '{n} Credits',
    RU: '{n} кредитов',
    ZH: '{n} 积分',
  },
  gr_dp_badge_title: {
    IT: 'Day Pass attivo: {n} guide rimaste',
    EN: 'Day Pass active: {n} guides left',
    FR: 'Day Pass actif : {n} guides restants',
    ES: 'Day Pass activo: quedan {n} guías',
    DE: 'Day Pass aktiv: {n} Guides übrig',
    RU: 'Day Pass активен: осталось {n} гидов',
    ZH: 'Day Pass 已激活：剩余 {n} 次导览',
  },
  gr_dp_offer_luoghi: {
    IT: '{n}+ luoghi da scoprire a {city}',
    EN: '{n}+ places to discover in {city}',
    FR: '{n}+ lieux à découvrir à {city}',
    ES: '{n}+ lugares por descubrir en {city}',
    DE: '{n}+ Orte in {city} zu entdecken',
    RU: '{n}+ мест для открытия: {city}',
    ZH: '在{city}有 {n}+ 个地点等你发现',
  },
  gr_dp_offer_scopri: {
    IT: 'Scopri {city} a mani libere',
    EN: 'Discover {city} hands-free',
    FR: 'Découvrez {city} mains libres',
    ES: 'Descubre {city} con las manos libres',
    DE: 'Entdecke {city} hands-free',
    RU: 'Откройте {city} без рук',
    ZH: '解放双手探索{city}',
  },
  gr_dp_offer_testo: {
    IT: 'Attiva il Day Pass e per 24 ore WIP fa tutto da solo: avviso, teaser e audioguida completa quando ti avvicini a un luogo — anche in tasca, a schermo spento e senza rete.',
    EN: 'Activate the Day Pass and for 24 hours WIP does everything on its own: alert, teaser and full audio guide when you approach a place — even in your pocket, with the screen off and without a connection.',
    FR: "Activez le Day Pass et pendant 24 heures WIP fait tout tout seul : alerte, teaser et audioguide complet quand vous approchez d'un lieu — même dans la poche, écran éteint et sans réseau.",
    ES: 'Activa el Day Pass y durante 24 horas WIP lo hace todo solo: aviso, teaser y audioguía completa cuando te acercas a un lugar — incluso en el bolsillo, con la pantalla apagada y sin red.',
    DE: 'Aktiviere den Day Pass und 24 Stunden lang macht WIP alles von allein: Hinweis, Teaser und kompletter Audioguide, wenn du dich einem Ort näherst — auch in der Tasche, bei ausgeschaltetem Display und ohne Netz.',
    RU: 'Активируйте Day Pass — и 24 часа WIP всё делает сам: уведомление, тизер и полный аудиогид, когда вы подходите к месту — даже в кармане, с выключенным экраном и без сети.',
    ZH: '激活 Day Pass，24 小时内 WIP 全自动运行：靠近地点时自动提醒、预告并播放完整语音导览 — 即使手机在口袋里、熄屏、没有网络。',
  },
  gr_non_ora: { IT: 'Non ora', EN: 'Not now', FR: 'Pas maintenant', ES: 'Ahora no', DE: 'Jetzt nicht', RU: 'Не сейчас', ZH: '暂不' },
  gr_dp_accedi: {
    IT: 'Accedi per attivare il Day Pass.',
    EN: 'Sign in to activate the Day Pass.',
    FR: 'Connectez-vous pour activer le Day Pass.',
    ES: 'Inicia sesión para activar el Day Pass.',
    DE: 'Melde dich an, um den Day Pass zu aktivieren.',
    RU: 'Войдите, чтобы активировать Day Pass.',
    ZH: '请登录以激活 Day Pass。',
  },
  gr_dp_gia_attivo: {
    IT: 'Hai già un Day Pass attivo.',
    EN: 'You already have an active Day Pass.',
    FR: 'Vous avez déjà un Day Pass actif.',
    ES: 'Ya tienes un Day Pass activo.',
    DE: 'Du hast bereits einen aktiven Day Pass.',
    RU: 'У вас уже есть активный Day Pass.',
    ZH: '你已有一个激活的 Day Pass。',
  },
  gr_dp_fallita_riprova: {
    IT: 'Attivazione non riuscita. Riprova.',
    EN: 'Activation failed. Try again.',
    FR: "Échec de l'activation. Réessayez.",
    ES: 'No se pudo activar. Inténtalo de nuevo.',
    DE: 'Aktivierung fehlgeschlagen. Versuch es erneut.',
    RU: 'Не удалось активировать. Попробуйте ещё раз.',
    ZH: '激活失败。请重试。',
  },
  gr_dp_crediti_insufficienti: {
    IT: 'Crediti insufficienti: il Day Pass costa {n} crediti.',
    EN: 'Not enough credits: the Day Pass costs {n} credits.',
    FR: 'Crédits insuffisants : le Day Pass coûte {n} crédits.',
    ES: 'Créditos insuficientes: el Day Pass cuesta {n} créditos.',
    DE: 'Nicht genug Credits: der Day Pass kostet {n} Credits.',
    RU: 'Недостаточно кредитов: Day Pass стоит {n} кредитов.',
    ZH: '积分不足：Day Pass 需要 {n} 积分。',
  },
};
