import type { Language } from '../i18n';

// Chiavi della bonifica lingua 24/08/2026 — area: mappa (MapArea: pannello
// layer, popup Leaflet, banner, ricerca, carta del sole).
export const TRAD_MAPPA: Record<string, Partial<Record<Language, string>>> = {
  // ── Carta del sole: consigliSole (lib/sunIndex.ts) — 24/08/2026 ──
  mp_sole_percepiti_ombra: {
    IT: 'Percepiti {temp}°: acqua con te e ombra nelle ore centrali.',
    EN: 'Feels like {temp}°: carry water and stay in the shade midday.',
    FR: 'Ressenti {temp}° : prends de l\'eau et reste à l\'ombre aux heures centrales.',
    ES: 'Sensación de {temp}°: lleva agua y busca sombra en las horas centrales.',
    DE: 'Gefühlt {temp}°: Wasser mitnehmen und mittags im Schatten bleiben.',
    RU: 'Ощущается как {temp}°: возьмите воду и держитесь в тени в середине дня.',
    ZH: '体感 {temp}°：请随身带水，正午时段待在阴凉处。',
  },
  mp_sole_crema_cappello: {
    IT: 'Crema solare e cappello: il sole scotta anche con le nuvole.',
    EN: 'Sunscreen and a hat: it burns even through clouds.',
    FR: 'Crème solaire et chapeau : le soleil brûle même sous les nuages.',
    ES: 'Protector solar y sombrero: el sol quema incluso con nubes.',
    DE: 'Sonnencreme und Hut: Die Sonne brennt auch bei Wolken.',
    RU: 'Солнцезащитный крем и шляпа: солнце обжигает даже сквозь облака.',
    ZH: '请涂防晒霜并戴帽子：即使多云也会晒伤。',
  },
  mp_sole_crema_mezzora: {
    IT: "Crema solare se resti fuori più di mezz'ora.",
    EN: 'Sunscreen if you stay out over half an hour.',
    FR: 'Crème solaire si tu restes dehors plus d\'une demi-heure.',
    ES: 'Protector solar si vas a estar fuera más de media hora.',
    DE: 'Sonnencreme, wenn du länger als eine halbe Stunde draußen bleibst.',
    RU: 'Солнцезащитный крем, если вы будете на улице дольше получаса.',
    ZH: '如果户外停留超过半小时，请涂防晒霜。',
  },
  mp_sole_freddo: {
    IT: "Fa freddo: copriti bene per le soste all'aperto.",
    EN: 'It is cold: dress warmly for outdoor stops.',
    FR: 'Il fait froid : couvre-toi bien pour les arrêts en extérieur.',
    ES: 'Hace frío: abrígate bien para las paradas al aire libre.',
    DE: 'Es ist kalt: Zieh dich für Pausen im Freien warm an.',
    RU: 'Холодно: одевайтесь теплее для остановок на улице.',
    ZH: '天气寒冷：户外停留时请注意保暖。',
  },
  mp_sole_tranquillo: {
    IT: 'Condizioni tranquille per stare all\'aperto.',
    EN: 'Comfortable conditions for being outdoors.',
    FR: 'Conditions agréables pour rester dehors.',
    ES: 'Condiciones tranquilas para estar al aire libre.',
    DE: 'Angenehme Bedingungen, um draußen zu sein.',
    RU: 'Комфортные условия для пребывания на улице.',
    ZH: '户外活动条件舒适。',
  },

  // ── Banner errori dati ──
  mp_luoghi_vicini_errore: {
    IT: 'Impossibile aggiornare i luoghi vicini. Riprova più tardi.',
    EN: 'Unable to refresh nearby places. Please try again later.',
    FR: 'Impossible de mettre à jour les lieux à proximité. Réessayez plus tard.',
    ES: 'No se han podido actualizar los lugares cercanos. Inténtalo de nuevo más tarde.',
    DE: 'Die Orte in der Nähe konnten nicht aktualisiert werden. Versuche es später erneut.',
    RU: 'Не удалось обновить места поблизости. Повторите попытку позже.',
    ZH: '无法更新附近地点，请稍后重试。',
  },
  mp_servizi_errore: {
    IT: 'Servizi (fontanelle, bagni, panchine) non disponibili al momento. Riprova più tardi.',
    EN: 'Services (fountains, toilets, benches) unavailable right now. Try again later.',
    FR: 'Services (fontaines, toilettes, bancs) indisponibles pour le moment. Réessayez plus tard.',
    ES: 'Los servicios (fuentes, baños, bancos) no están disponibles ahora mismo. Inténtalo más tarde.',
    DE: 'Services (Trinkbrunnen, Toiletten, Bänke) sind derzeit nicht verfügbar. Versuche es später erneut.',
    RU: 'Сервисы (фонтанчики, туалеты, скамейки) сейчас недоступны. Повторите попытку позже.',
    ZH: '便民设施（饮水点、卫生间、长椅）暂不可用，请稍后重试。',
  },
  mp_db_pausa: {
    IT: 'Troppi errori di rete recenti: pausa di sicurezza sul caricamento dei luoghi dal database.',
    EN: 'Too many recent network errors: pausing place loading from the database as a safety measure.',
    FR: "Trop d'erreurs réseau récentes : pause de sécurité du chargement des lieux depuis la base de données.",
    ES: 'Demasiados errores de red recientes: pausa de seguridad en la carga de lugares desde la base de datos.',
    DE: 'Zu viele Netzwerkfehler in letzter Zeit: Sicherheitspause beim Laden der Orte aus der Datenbank.',
    RU: 'Слишком много сетевых ошибок: загрузка мест из базы данных приостановлена в целях безопасности.',
    ZH: '近期网络错误过多：已暂停从数据库加载地点以保护应用。',
  },
  mp_overpass_errore: {
    IT: 'Servizio mappe OpenStreetMap non raggiungibile. Alcuni luoghi potrebbero mancare.',
    EN: 'OpenStreetMap map service unreachable. Some places may be missing.',
    FR: 'Service cartographique OpenStreetMap injoignable. Certains lieux peuvent manquer.',
    ES: 'El servicio de mapas de OpenStreetMap no está accesible. Pueden faltar algunos lugares.',
    DE: 'OpenStreetMap-Kartendienst nicht erreichbar. Einige Orte können fehlen.',
    RU: 'Сервис карт OpenStreetMap недоступен. Некоторые места могут отсутствовать.',
    ZH: '无法连接 OpenStreetMap 地图服务，部分地点可能缺失。',
  },
  mp_err_db_titolo: {
    IT: 'Luoghi Vicini', EN: 'Nearby Places', FR: 'Lieux à proximité',
    ES: 'Lugares cercanos', DE: 'Orte in der Nähe', RU: 'Места поблизости', ZH: '附近地点',
  },
  mp_err_servizi_titolo: {
    IT: 'Servizi', EN: 'Services', FR: 'Services',
    ES: 'Servicios', DE: 'Services', RU: 'Сервисы', ZH: '便民设施',
  },
  mp_gps_attiva: {
    IT: 'Attiva la posizione GPS per vedere i luoghi attorno a te.',
    EN: 'Enable GPS location to see places around you.',
    FR: 'Activez la localisation GPS pour voir les lieux autour de vous.',
    ES: 'Activa la ubicación GPS para ver los lugares a tu alrededor.',
    DE: 'Aktiviere die GPS-Ortung, um Orte in deiner Umgebung zu sehen.',
    RU: 'Включите GPS, чтобы увидеть места вокруг вас.',
    ZH: '开启 GPS 定位即可查看您周围的地点。',
  },

  // ── Popup Leaflet (sentieri, ciclabili, gusto, neve) ──
  mp_punto_partenza_osm: {
    IT: 'Punto di partenza · © contributori OpenStreetMap',
    EN: 'Starting point · © OpenStreetMap contributors',
    FR: 'Point de départ · © contributeurs OpenStreetMap',
    ES: 'Punto de salida · © colaboradores de OpenStreetMap',
    DE: 'Startpunkt · © OpenStreetMap-Mitwirkende',
    RU: 'Точка старта · © участники OpenStreetMap',
    ZH: '起点 · © OpenStreetMap 贡献者',
  },
  mp_osm_contributori: {
    IT: '© contributori OpenStreetMap',
    EN: '© OpenStreetMap contributors',
    FR: '© contributeurs OpenStreetMap',
    ES: '© colaboradores de OpenStreetMap',
    DE: '© OpenStreetMap-Mitwirkende',
    RU: '© участники OpenStreetMap',
    ZH: '© OpenStreetMap 贡献者',
  },
  mp_punto_partenza_percorso: {
    IT: 'Punto di partenza del percorso', EN: 'Route starting point',
    FR: "Point de départ de l'itinéraire", ES: 'Punto de salida de la ruta',
    DE: 'Startpunkt der Route', RU: 'Начало маршрута', ZH: '路线起点',
  },
  mp_sito_ufficiale: {
    IT: 'sito ufficiale', EN: 'official website', FR: 'site officiel',
    ES: 'sitio oficial', DE: 'offizielle Website', RU: 'официальный сайт', ZH: '官方网站',
  },
  mp_sito: {
    IT: 'sito', EN: 'website', FR: 'site', ES: 'sitio web',
    DE: 'Website', RU: 'сайт', ZH: '网站',
  },
  mp_verifica_orari_osm: {
    IT: 'Verifica sempre orari e prenotazione · © contributori OpenStreetMap',
    EN: 'Always check hours and booking · © OpenStreetMap contributors',
    FR: 'Vérifiez toujours les horaires et la réservation · © contributeurs OpenStreetMap',
    ES: 'Comprueba siempre horarios y reservas · © colaboradores de OpenStreetMap',
    DE: 'Öffnungszeiten und Reservierung immer prüfen · © OpenStreetMap-Mitwirkende',
    RU: 'Всегда проверяйте часы работы и бронирование · © участники OpenStreetMap',
    ZH: '请务必确认营业时间和预订 · © OpenStreetMap 贡献者',
  },
  mp_rifugio_alpino: {
    IT: 'Rifugio alpino', EN: 'Mountain hut', FR: 'Refuge de montagne',
    ES: 'Refugio de montaña', DE: 'Berghütte', RU: 'Горный приют', ZH: '山间小屋',
  },
  mp_comprensorio_sci: {
    IT: 'Comprensorio sciistico', EN: 'Ski area', FR: 'Domaine skiable',
    ES: 'Estación de esquí', DE: 'Skigebiet', RU: 'Горнолыжный курорт', ZH: '滑雪场',
  },
  mp_impianto_risalita: {
    IT: 'Impianto di risalita', EN: 'Ski lift', FR: 'Remontée mécanique',
    ES: 'Remonte', DE: 'Skilift', RU: 'Подъёмник', ZH: '滑雪缆车',
  },
  mp_pista_sci: {
    IT: 'Pista da sci', EN: 'Ski piste', FR: 'Piste de ski',
    ES: 'Pista de esquí', DE: 'Skipiste', RU: 'Горнолыжная трасса', ZH: '滑雪道',
  },
  mp_condizioni_non_disponibili: {
    IT: 'condizioni non disponibili', EN: 'conditions unavailable',
    FR: 'conditions indisponibles', ES: 'condiciones no disponibles',
    DE: 'Bedingungen nicht verfügbar', RU: 'нет данных об условиях', ZH: '暂无实况信息',
  },

  // ── Popup acque di balneazione (EEA) ──
  mp_qualita: {
    IT: 'Qualità', EN: 'Quality', FR: 'Qualité', ES: 'Calidad',
    DE: 'Qualität', RU: 'Качество', ZH: '水质',
  },
  mp_acqua_excellent: {
    IT: 'Eccellente', EN: 'Excellent', FR: 'Excellente', ES: 'Excelente',
    DE: 'Ausgezeichnet', RU: 'Отличное', ZH: '极佳',
  },
  mp_acqua_good: {
    IT: 'Buona', EN: 'Good', FR: 'Bonne', ES: 'Buena',
    DE: 'Gut', RU: 'Хорошее', ZH: '良好',
  },
  mp_acqua_sufficient: {
    IT: 'Sufficiente', EN: 'Sufficient', FR: 'Suffisante', ES: 'Suficiente',
    DE: 'Ausreichend', RU: 'Удовлетворительное', ZH: '合格',
  },
  mp_acqua_poor: {
    IT: 'Scarsa', EN: 'Poor', FR: 'Mauvaise', ES: 'Mala',
    DE: 'Mangelhaft', RU: 'Плохое', ZH: '较差',
  },
  mp_acqua_unknown: {
    IT: 'Non classificata', EN: 'Not classified', FR: 'Non classée',
    ES: 'Sin clasificar', DE: 'Nicht klassifiziert', RU: 'Не классифицировано', ZH: '未分级',
  },
  mp_acqua_onde_ora: {
    IT: 'Acqua e onde ora (Open-Meteo)', EN: 'Water and waves now (Open-Meteo)',
    FR: 'Eau et vagues en ce moment (Open-Meteo)', ES: 'Agua y oleaje ahora (Open-Meteo)',
    DE: 'Wasser und Wellen jetzt (Open-Meteo)', RU: 'Вода и волны сейчас (Open-Meteo)',
    ZH: '当前水温与海浪（Open-Meteo）',
  },
  mp_classificazione_eea: {
    IT: 'Classificazione ufficiale UE (EEA) — verifica i divieti temporanei in loco',
    EN: 'Official EU classification (EEA) — check temporary bans on site',
    FR: "Classification officielle de l'UE (AEE) — vérifiez sur place les interdictions temporaires",
    ES: 'Clasificación oficial de la UE (AEMA) — comprueba in situ las prohibiciones temporales',
    DE: 'Offizielle EU-Klassifizierung (EEA) — vorübergehende Badeverbote vor Ort prüfen',
    RU: 'Официальная классификация ЕС (EEA) — проверяйте временные запреты на месте',
    ZH: '欧盟官方分级（EEA）——请在现场确认临时禁泳通知',
  },

  // ── ZTL: banner, disclaimer e avviso vocale ──
  mp_ztl_entrando: {
    IT: 'Stai per entrare nella ZTL{name} — rischio multa',
    EN: 'Entering limited traffic zone{name} — fine risk',
    FR: "Vous entrez dans la zone à circulation restreinte{name} — risque d'amende",
    ES: 'Estás entrando en la zona de tráfico restringido{name} — riesgo de multa',
    DE: 'Du fährst gleich in die verkehrsbeschränkte Zone{name} — Bußgeldrisiko',
    RU: 'Вы въезжаете в зону ограниченного движения{name} — риск штрафа',
    ZH: '即将进入交通限行区{name}——有罚款风险',
  },
  mp_ztl_dentro: {
    IT: 'Sei nella ZTL{name} — rischio multa',
    EN: 'Inside limited traffic zone{name} — fine risk',
    FR: "Vous êtes dans la zone à circulation restreinte{name} — risque d'amende",
    ES: 'Estás en la zona de tráfico restringido{name} — riesgo de multa',
    DE: 'Du bist in der verkehrsbeschränkten Zone{name} — Bußgeldrisiko',
    RU: 'Вы в зоне ограниченного движения{name} — риск штрафа',
    ZH: '您已进入交通限行区{name}——有罚款风险',
  },
  mp_ztl_vocale: {
    IT: 'Attenzione, zona a traffico limitato',
    EN: 'Warning, limited traffic zone',
    FR: 'Attention, zone à circulation restreinte',
    ES: 'Atención, zona de tráfico restringido',
    DE: 'Achtung, Zone mit Verkehrsbeschränkung',
    RU: 'Внимание, зона с ограниченным движением',
    ZH: '注意，前方是交通限行区',
  },
  mp_chiudi_avviso_ztl: {
    IT: 'Chiudi avviso ZTL', EN: 'Dismiss ZTL alert', FR: "Fermer l'alerte ZTL",
    ES: 'Cerrar aviso de ZTL', DE: 'ZTL-Hinweis schließen',
    RU: 'Закрыть предупреждение о зоне', ZH: '关闭限行区提醒',
  },
  mp_chiudi: {
    IT: 'Chiudi', EN: 'Close', FR: 'Fermer', ES: 'Cerrar',
    DE: 'Schließen', RU: 'Закрыть', ZH: '关闭',
  },
  mp_ztl_copertura: {
    IT: 'Copertura basata su OpenStreetMap: non tutte le ZTL sono mappate, verifica sempre la segnaletica.',
    EN: 'Coverage based on OpenStreetMap: not all restricted zones are mapped, always check road signs.',
    FR: 'Couverture basée sur OpenStreetMap : toutes les zones restreintes ne sont pas cartographiées, vérifiez toujours la signalisation.',
    ES: 'Cobertura basada en OpenStreetMap: no todas las zonas restringidas están cartografiadas, comprueba siempre la señalización.',
    DE: 'Abdeckung auf Basis von OpenStreetMap: Nicht alle Zonen sind erfasst, achte immer auf die Beschilderung.',
    RU: 'Покрытие на основе OpenStreetMap: не все зоны нанесены на карту, всегда сверяйтесь с дорожными знаками.',
    ZH: '数据来自 OpenStreetMap：并非所有限行区都已收录，请务必以现场交通标志为准。',
  },
  mp_balneazione_disclaimer: {
    IT: 'Qualità delle acque di balneazione: classificazione annuale ufficiale UE (EEA). Copertura solo europea; avvicina la mappa per vedere i siti.',
    EN: 'Bathing water quality: official annual EU classification (EEA). Europe-only coverage; zoom in to see the sites.',
    FR: "Qualité des eaux de baignade : classification annuelle officielle de l'UE (AEE). Couverture européenne uniquement ; zoomez pour voir les sites.",
    ES: 'Calidad de las aguas de baño: clasificación anual oficial de la UE (AEMA). Cobertura solo europea; acerca el mapa para ver los sitios.',
    DE: 'Badegewässerqualität: offizielle jährliche EU-Klassifizierung (EEA). Nur Europa; heranzoomen, um die Badestellen zu sehen.',
    RU: 'Качество воды для купания: официальная ежегодная классификация ЕС (EEA). Только Европа; приблизьте карту, чтобы увидеть пляжи.',
    ZH: '海水浴场水质：欧盟官方年度分级（EEA）。仅覆盖欧洲；放大地图查看各浴场。',
  },

  // ── Banner offline, beni culturali, pioggia/al coperto ──
  mp_sei_offline: {
    IT: 'Sei offline', EN: "You're offline", FR: 'Vous êtes hors ligne',
    ES: 'Estás sin conexión', DE: 'Du bist offline', RU: 'Вы офлайн', ZH: '当前离线',
  },
  mp_beni_fascia_ab: {
    IT: 'Beni culturali: solo i principali (fascia A e B) — avvicinati per tutti',
    EN: 'Heritage: main sites only (tier A–B) — zoom in for all',
    FR: 'Patrimoine : sites principaux uniquement (catégories A–B) — zoomez pour tout voir',
    ES: 'Patrimonio: solo los principales (categorías A y B) — acércate para verlos todos',
    DE: 'Kulturerbe: nur die wichtigsten Stätten (Stufe A–B) — heranzoomen für alle',
    RU: 'Культурное наследие: только главные объекты (уровни A–B) — приблизьте, чтобы увидеть все',
    ZH: '文化遗产：仅显示主要地点（A、B 级）——放大查看全部',
  },
  mp_beni_fascia_a: {
    IT: 'Beni culturali: solo i grandi monumenti (fascia A) — avvicinati per gli altri',
    EN: 'Heritage: major monuments only (tier A) — zoom in for more',
    FR: 'Patrimoine : grands monuments uniquement (catégorie A) — zoomez pour en voir plus',
    ES: 'Patrimonio: solo los grandes monumentos (categoría A) — acércate para ver más',
    DE: 'Kulturerbe: nur die großen Denkmäler (Stufe A) — heranzoomen für mehr',
    RU: 'Культурное наследие: только крупнейшие памятники (уровень A) — приблизьте, чтобы увидеть больше',
    ZH: '文化遗产：仅显示重要古迹（A 级）——放大查看更多',
  },
  mp_pioggia_domanda: {
    IT: 'Pioggia in arrivo — vuoi vedere i luoghi al coperto?',
    EN: 'Rain coming — want to see indoor places?',
    FR: 'Pluie en approche — voir les lieux couverts ?',
    ES: 'Lluvia a la vista — ¿quieres ver los lugares cubiertos?',
    DE: 'Regen im Anmarsch — Orte im Trockenen anzeigen?',
    RU: 'Скоро дождь — показать места под крышей?',
    ZH: '快要下雨了——要看看室内景点吗？',
  },
  mp_al_coperto: {
    IT: 'Al coperto', EN: 'Indoor', FR: "À l'abri", ES: 'A cubierto',
    DE: 'Drinnen', RU: 'Под крышей', ZH: '室内',
  },
  mp_no_grazie: {
    IT: 'No grazie', EN: 'No thanks', FR: 'Non merci', ES: 'No, gracias',
    DE: 'Nein danke', RU: 'Нет, спасибо', ZH: '不用了',
  },
  mp_al_coperto_attivo: {
    IT: 'Al coperto attivo', EN: 'Indoor mode on', FR: "Mode à l'abri activé",
    ES: 'Modo a cubierto activado', DE: 'Drinnen-Modus an',
    RU: 'Режим «под крышей» включён', ZH: '室内模式已开启',
  },

  // ── Pannello dei livelli (ⓘ / Layers) ──
  mp_livelli_mappa: {
    IT: 'Livelli della mappa', EN: 'Map layers', FR: 'Couches de la carte',
    ES: 'Capas del mapa', DE: 'Kartenebenen', RU: 'Слои карты', ZH: '地图图层',
  },
  mp_attivi: {
    IT: 'attivi', EN: 'active', FR: 'actives', ES: 'activas',
    DE: 'aktiv', RU: 'включено', ZH: '已开启',
  },
  mp_livelli_attivi: {
    IT: 'Livelli attivi', EN: 'Active layers', FR: 'Couches actives',
    ES: 'Capas activas', DE: 'Aktive Ebenen', RU: 'Включённые слои', ZH: '已开启的图层',
  },
  mp_dove_andare: {
    IT: 'Dove andare', EN: 'Where to go', FR: 'Où aller', ES: 'Dónde ir',
    DE: 'Wohin gehen', RU: 'Куда пойти', ZH: '去哪儿',
  },
  mp_come_adesso: {
    IT: 'Com’è adesso', EN: 'Conditions now', FR: 'Conditions actuelles',
    ES: 'Cómo está ahora', DE: 'Aktuelle Bedingungen', RU: 'Условия сейчас', ZH: '当前状况',
  },
  mp_sfondo_mappa: {
    IT: 'Sfondo', EN: 'Background', FR: 'Fond de carte', ES: 'Fondo',
    DE: 'Hintergrund', RU: 'Подложка', ZH: '底图',
  },
  mp_layer_satellite_nome: {
    IT: 'Satellite', EN: 'Satellite', FR: 'Satellite', ES: 'Satélite',
    DE: 'Satellit', RU: 'Спутник', ZH: '卫星图',
  },
  mp_layer_satellite_det: {
    IT: 'Foto dall’alto al posto della mappa', EN: 'Aerial imagery instead of the map',
    FR: 'Vue aérienne à la place de la carte', ES: 'Imagen aérea en lugar del mapa',
    DE: 'Luftbild statt Karte', RU: 'Снимки вместо карты', ZH: '用航拍影像代替地图',
  },
  mp_avvicinati: {
    IT: 'avvicinati per vederli', EN: 'zoom in to see them', FR: 'zoomez pour les voir',
    ES: 'acércate para verlos', DE: 'heranzoomen, um sie zu sehen',
    RU: 'приблизьте, чтобы увидеть', ZH: '放大后可见',
  },
  mp_spegni_tutti: {
    IT: 'Spegni tutti ({n})', EN: 'Turn all off ({n})', FR: 'Tout éteindre ({n})',
    ES: 'Apagar todo ({n})', DE: 'Alle ausschalten ({n})',
    RU: 'Выключить все ({n})', ZH: '全部关闭（{n}）',
  },
  mp_layer_sentieri_nome: {
    IT: 'Sentieri e cammini', EN: 'Trails and pilgrim ways', FR: 'Sentiers et chemins',
    ES: 'Senderos y caminos', DE: 'Wanderwege und Pilgerwege',
    RU: 'Тропы и пешие маршруты', ZH: '步道与朝圣之路',
  },
  mp_layer_sentieri_det: {
    IT: 'con ippovie, rifugi, corsa, canoa e itinerari storici',
    EN: 'with bridleways, huts, running, canoe and historic routes',
    FR: 'avec voies équestres, refuges, course, canoë et itinéraires historiques',
    ES: 'con vías ecuestres, refugios, rutas para correr, canoa e itinerarios históricos',
    DE: 'mit Reitwegen, Hütten, Lauf-, Kanu- und historischen Routen',
    RU: 'с конными тропами, приютами, беговыми, каноэ и историческими маршрутами',
    ZH: '含骑马道、山屋、跑步、皮划艇与历史路线',
  },
  mp_layer_ciclabili_nome: {
    IT: 'Ciclovie e mountain bike', EN: 'Cycle routes and MTB', FR: 'Voies cyclables et VTT',
    ES: 'Rutas ciclistas y BTT', DE: 'Radwege und Mountainbike',
    RU: 'Веломаршруты и маунтинбайк', ZH: '自行车道与山地车',
  },
  mp_layer_ciclabili_det: {
    IT: 'EuroVelo e reti nazionali', EN: 'EuroVelo and national networks',
    FR: 'EuroVelo et réseaux nationaux', ES: 'EuroVelo y redes nacionales',
    DE: 'EuroVelo und nationale Netze', RU: 'EuroVelo и национальные сети',
    ZH: 'EuroVelo 与各国路网',
  },
  mp_layer_gusto_nome: {
    IT: 'Vino e gusto', EN: 'Wine & food', FR: 'Vin et gastronomie',
    ES: 'Vino y gastronomía', DE: 'Wein und Genuss',
    RU: 'Вино и гастрономия', ZH: '美酒与美食',
  },
  mp_layer_gusto_det: {
    IT: 'cantine, strade e botteghe', EN: 'cellars, routes and shops',
    FR: 'caves, routes et boutiques', ES: 'bodegas, rutas y tiendas',
    DE: 'Weingüter, Straßen und Läden', RU: 'винодельни, маршруты и лавки',
    ZH: '酒庄、酒乡之路与特色小店',
  },
  mp_layer_servizi_nome: {
    IT: 'Fontanelle, bagni, panchine', EN: 'Water, toilets, benches',
    FR: 'Fontaines, toilettes, bancs', ES: 'Fuentes, baños, bancos',
    DE: 'Trinkbrunnen, Toiletten, Bänke', RU: 'Фонтанчики, туалеты, скамейки',
    ZH: '饮水点、卫生间、长椅',
  },
  mp_layer_neve_nome: {
    IT: 'Neve: piste, impianti e rifugi', EN: 'Snow: pistes, lifts and huts',
    FR: 'Neige : pistes, remontées et refuges', ES: 'Nieve: pistas, remontes y refugios',
    DE: 'Schnee: Pisten, Lifte und Hütten', RU: 'Снег: трассы, подъёмники и приюты',
    ZH: '雪场：雪道、缆车与山屋',
  },
  mp_layer_neve_det: {
    IT: '9.569 piste disegnate + copertura satellitare NASA (giornaliera)',
    EN: '9,569 pistes drawn + NASA satellite snow cover (daily)',
    FR: '9 569 pistes tracées + couverture satellite NASA (quotidienne)',
    ES: '9.569 pistas dibujadas + cobertura satelital NASA (diaria)',
    DE: '9.569 eingezeichnete Pisten + NASA-Satelliten-Schneebedeckung (täglich)',
    RU: '9 569 трасс на карте + спутниковый снежный покров NASA (ежедневно)',
    ZH: '已绘制 9,569 条雪道 + NASA 卫星积雪覆盖（每日）',
  },
  mp_layer_sole_nome: {
    IT: 'Sole: UV e caldo percepito', EN: 'Sun: UV and feels-like',
    FR: 'Soleil : UV et température ressentie', ES: 'Sol: UV y sensación térmica',
    DE: 'Sonne: UV und gefühlte Temperatur', RU: 'Солнце: УФ и ощущаемая температура',
    ZH: '日照：紫外线与体感温度',
  },
  // ── Clima: il periodo migliore per visitare (lib/climaIndex.ts) — 24/09/2026 ──
  mp_layer_clima_nome: {
    IT: 'Clima: il periodo migliore', EN: 'Climate: the best time to visit',
    FR: 'Climat : la meilleure période', ES: 'Clima: la mejor época',
    DE: 'Klima: die beste Reisezeit', RU: 'Климат: лучшее время для визита', ZH: '气候：最佳旅行时间',
  },
  mp_layer_clima_det: {
    IT: 'Pioggia e temperature medie 2001-2020 (NASA POWER) + analisi AI',
    EN: 'Average rain and temperatures 2001-2020 (NASA POWER) + AI analysis',
    FR: 'Pluie et températures moyennes 2001-2020 (NASA POWER) + analyse IA',
    ES: 'Lluvia y temperaturas medias 2001-2020 (NASA POWER) + análisis IA',
    DE: 'Regen und Temperaturen im Mittel 2001-2020 (NASA POWER) + KI-Analyse',
    RU: 'Средние осадки и температуры 2001-2020 (NASA POWER) + ИИ-анализ',
    ZH: '2001-2020 年平均降雨与气温（NASA POWER）+ AI 分析',
  },
  mp_clima_migliore: {
    IT: 'Periodo migliore', EN: 'Best time', FR: 'Meilleure période', ES: 'Mejor época',
    DE: 'Beste Zeit', RU: 'Лучший период', ZH: '最佳时间',
  },
  mp_clima_evitare: {
    IT: 'Da evitare', EN: 'Avoid', FR: 'À éviter', ES: 'A evitar', DE: 'Vermeiden', RU: 'Избегать', ZH: '不宜',
  },
  mp_clima_piovoso: {
    IT: 'più piovoso', EN: 'wettest', FR: 'le plus pluvieux', ES: 'más lluvioso', DE: 'am regenreichsten', RU: 'самый дождливый', ZH: '最多雨',
  },
  mp_clima_caldo: {
    IT: 'più caldo', EN: 'hottest', FR: 'le plus chaud', ES: 'más caluroso', DE: 'am heißesten', RU: 'самый жаркий', ZH: '最热',
  },
  mp_clima_freddo: {
    IT: 'più freddo', EN: 'coldest', FR: 'le plus froid', ES: 'más frío', DE: 'am kältesten', RU: 'самый холодный', ZH: '最冷',
  },
  mp_clima_oggi_migliore: {
    IT: 'Questo mese è nel periodo migliore.', EN: 'This month is in the best period.',
    FR: 'Ce mois fait partie de la meilleure période.', ES: 'Este mes está en la mejor época.',
    DE: 'Dieser Monat liegt in der besten Zeit.', RU: 'Этот месяц входит в лучший период.', ZH: '本月正处于最佳时间。',
  },
  mp_clima_oggi_peggiore: {
    IT: 'Questo mese è tra i meno favorevoli.', EN: 'This month is among the least favourable.',
    FR: 'Ce mois est parmi les moins favorables.', ES: 'Este mes está entre los menos favorables.',
    DE: 'Dieser Monat gehört zu den ungünstigsten.', RU: 'Этот месяц один из наименее благоприятных.', ZH: '本月属于较不适宜的时间。',
  },
  mp_clima_oggi_medio: {
    IT: 'Questo mese: {p}/100.', EN: 'This month: {p}/100.', FR: 'Ce mois : {p}/100.', ES: 'Este mes: {p}/100.',
    DE: 'Dieser Monat: {p}/100.', RU: 'Этот месяц: {p}/100.', ZH: '本月：{p}/100。',
  },
  mp_clima_accedi: {
    IT: 'Accedi per l\'analisi AI di questa zona', EN: 'Sign in for the AI analysis of this area',
    FR: 'Connectez-vous pour l\'analyse IA de cette zone', ES: 'Inicia sesión para el análisis IA de esta zona',
    DE: 'Anmelden für die KI-Analyse dieser Gegend', RU: 'Войдите, чтобы получить ИИ-анализ этой зоны', ZH: '登录以查看该地区的 AI 分析',
  },
  mp_clima_non_disp: {
    IT: 'Statistiche non disponibili per questo punto', EN: 'No statistics available for this point',
    FR: 'Statistiques indisponibles pour ce point', ES: 'Estadísticas no disponibles para este punto',
    DE: 'Für diesen Punkt keine Statistiken', RU: 'Для этой точки нет статистики', ZH: '该位置暂无统计数据',
  },
  mp_clima_report: {
    IT: 'Report completo', EN: 'Full report', FR: 'Rapport complet', ES: 'Informe completo', DE: 'Vollständiger Bericht', RU: 'Полный отчёт', ZH: '完整报告',
  },
  mp_clima_report_titolo: {
    IT: 'Quando visitare', EN: 'When to visit', FR: 'Quand visiter', ES: 'Cuándo visitar', DE: 'Wann reisen', RU: 'Когда ехать', ZH: '何时前往',
  },
  mp_clima_report_attesa: {
    IT: 'Sto leggendo il web e le statistiche di vent\'anni: fino a un minuto.',
    EN: 'Reading the web and twenty years of statistics: up to a minute.',
    FR: 'Je lis le web et vingt ans de statistiques : jusqu\'à une minute.',
    ES: 'Leyendo la web y veinte años de estadísticas: hasta un minuto.',
    DE: 'Ich lese das Web und zwanzig Jahre Statistik: bis zu einer Minute.',
    RU: 'Читаю веб и статистику за двадцать лет: до минуты.',
    ZH: '正在阅读网络资料和二十年统计数据：最多一分钟。',
  },
  mp_clima_report_accedi: {
    IT: 'Il report lo scrive l\'AI per chi ha l\'account: accedi per generarlo, poi resta disponibile a tutti.',
    EN: 'The AI writes the report for account holders: sign in to generate it, then it stays available to everyone.',
    FR: 'L\'IA écrit le rapport pour les comptes : connectez-vous pour le générer, il reste ensuite disponible à tous.',
    ES: 'La IA escribe el informe para quien tiene cuenta: inicia sesión para generarlo, luego queda disponible para todos.',
    DE: 'Die KI schreibt den Bericht für Kontoinhaber: anmelden, um ihn zu erzeugen, danach bleibt er für alle verfügbar.',
    RU: 'ИИ пишет отчёт для владельцев аккаунта: войдите, чтобы создать его, потом он доступен всем.',
    ZH: 'AI 为账户用户撰写报告：登录后生成，之后对所有人可用。',
  },
  mp_clima_report_errore: {
    IT: 'Report non disponibile in questo momento. Riprova tra poco.', EN: 'Report not available right now. Try again shortly.',
    FR: 'Rapport indisponible pour le moment. Réessayez bientôt.', ES: 'Informe no disponible ahora. Inténtalo en breve.',
    DE: 'Bericht gerade nicht verfügbar. Bitte gleich noch einmal versuchen.', RU: 'Отчёт сейчас недоступен. Попробуйте позже.', ZH: '报告暂时不可用，请稍后再试。',
  },
  mp_clima_sez_numeri: { IT: 'In numeri', EN: 'In numbers', FR: 'En chiffres', ES: 'En cifras', DE: 'In Zahlen', RU: 'В цифрах', ZH: '数据一览' },
  mp_clima_sez_panoramica: { IT: 'Panoramica', EN: 'Overview', FR: 'Aperçu', ES: 'Panorámica', DE: 'Überblick', RU: 'Обзор', ZH: '概览' },
  mp_clima_sez_web: { IT: 'Consigli e suggerimenti dal web', EN: 'Tips and advice from the web', FR: 'Conseils et suggestions du web', ES: 'Consejos y sugerencias de la web', DE: 'Tipps und Hinweise aus dem Web', RU: 'Советы и подсказки из веба', ZH: '来自网络的建议' },
  mp_clima_sez_esperienze: { IT: 'Esperienze dei viaggiatori', EN: 'Travellers\' experiences', FR: 'Expériences de voyageurs', ES: 'Experiencias de viajeros', DE: 'Erfahrungen von Reisenden', RU: 'Опыт путешественников', ZH: '旅行者的经历' },
  mp_clima_sez_mesi: { IT: 'Mese per mese', EN: 'Month by month', FR: 'Mois par mois', ES: 'Mes a mes', DE: 'Monat für Monat', RU: 'Месяц за месяцем', ZH: '逐月分析' },
  mp_clima_sez_portare: { IT: 'Cosa portare', EN: 'What to pack', FR: 'Quoi emporter', ES: 'Qué llevar', DE: 'Was mitnehmen', RU: 'Что взять с собой', ZH: '携带物品' },
  mp_clima_sez_orari: { IT: 'Orari migliori', EN: 'Best hours', FR: 'Meilleures heures', ES: 'Mejores horas', DE: 'Beste Tageszeiten', RU: 'Лучшие часы', ZH: '最佳时段' },
  mp_clima_sez_avvertenze: { IT: 'Avvertenze', EN: 'Warnings', FR: 'Avertissements', ES: 'Advertencias', DE: 'Hinweise', RU: 'Предупреждения', ZH: '注意事项' },
  mp_clima_sez_statistiche: { IT: 'Statistiche', EN: 'Statistics', FR: 'Statistiques', ES: 'Estadísticas', DE: 'Statistiken', RU: 'Статистика', ZH: '统计' },
  mp_clima_adesso: { IT: 'Questa settimana', EN: 'This week', FR: 'Cette semaine', ES: 'Esta semana', DE: 'Diese Woche', RU: 'На этой неделе', ZH: '本周' },
  mp_clima_sopra_media: { IT: 'sopra la media del mese', EN: 'above the monthly average', FR: 'au-dessus de la moyenne du mois', ES: 'por encima de la media del mes', DE: 'über dem Monatsmittel', RU: 'выше нормы месяца', ZH: '高于本月平均' },
  mp_clima_sotto_media: { IT: 'sotto la media del mese', EN: 'below the monthly average', FR: 'en dessous de la moyenne du mois', ES: 'por debajo de la media del mes', DE: 'unter dem Monatsmittel', RU: 'ниже нормы месяца', ZH: '低于本月平均' },
  mp_clima_nella_media: { IT: 'nella media del mese', EN: 'in line with the monthly average', FR: 'dans la moyenne du mois', ES: 'en la media del mes', DE: 'im Monatsmittel', RU: 'в пределах нормы месяца', ZH: '与本月平均持平' },
  mp_clima_pioggia_prevista: { IT: 'pioggia prevista', EN: 'rain expected', FR: 'pluie prévue', ES: 'lluvia prevista', DE: 'Regen erwartet', RU: 'ожидаемые осадки', ZH: '预计降雨' },
  mp_clima_attesa_mese: { IT: 'attesa per il periodo', EN: 'typical for the period', FR: 'habituelle pour la période', ES: 'habitual en el periodo', DE: 'üblich für den Zeitraum', RU: 'обычно за период', ZH: '同期通常' },
  mp_clima_col_luce: { IT: 'Luce', EN: 'Daylight', FR: 'Jour', ES: 'Luz', DE: 'Tageslicht', RU: 'Светло', ZH: '日照时长' },
  mp_clima_avviso_peggiore: {
    IT: '{mese} è tra i mesi meno favorevoli per {citta}: {tmax}° di massima e {mm} mm di pioggia. Il periodo migliore è {migliori}.',
    EN: '{mese} is among the least favourable months for {citta}: highs of {tmax}° and {mm} mm of rain. The best time is {migliori}.',
    FR: '{mese} est parmi les mois les moins favorables pour {citta} : {tmax}° de maximale et {mm} mm de pluie. La meilleure période est {migliori}.',
    ES: '{mese} está entre los meses menos favorables para {citta}: máximas de {tmax}° y {mm} mm de lluvia. La mejor época es {migliori}.',
    DE: '{mese} gehört für {citta} zu den ungünstigsten Monaten: Höchstwerte {tmax}° und {mm} mm Regen. Die beste Zeit ist {migliori}.',
    RU: '{mese} — один из наименее благоприятных месяцев для {citta}: максимум {tmax}° и {mm} мм осадков. Лучший период: {migliori}.',
    ZH: '{mese} 是 {citta} 较不适宜的月份之一：最高 {tmax}°，降雨 {mm} 毫米。最佳时间为 {migliori}。',
  },
  mp_clima_avviso_migliore: {
    IT: '{mese} è nel periodo migliore per {citta}: {tmin}–{tmax}° e {mm} mm di pioggia.',
    EN: '{mese} is in the best period for {citta}: {tmin}–{tmax}° and {mm} mm of rain.',
    FR: '{mese} est dans la meilleure période pour {citta} : {tmin}–{tmax}° et {mm} mm de pluie.',
    ES: '{mese} está en la mejor época para {citta}: {tmin}–{tmax}° y {mm} mm de lluvia.',
    DE: '{mese} liegt für {citta} in der besten Zeit: {tmin}–{tmax}° und {mm} mm Regen.',
    RU: '{mese} входит в лучший период для {citta}: {tmin}–{tmax}° и {mm} мм осадков.',
    ZH: '{mese} 是 {citta} 的最佳时间：{tmin}–{tmax}°，降雨 {mm} 毫米。',
  },
  mp_clima_avviso_medio: {
    IT: '{mese} a {citta}: {tmin}–{tmax}° e {mm} mm di pioggia. Il periodo migliore è {migliori}.',
    EN: '{mese} in {citta}: {tmin}–{tmax}° and {mm} mm of rain. The best time is {migliori}.',
    FR: '{mese} à {citta} : {tmin}–{tmax}° et {mm} mm de pluie. La meilleure période est {migliori}.',
    ES: '{mese} en {citta}: {tmin}–{tmax}° y {mm} mm de lluvia. La mejor época es {migliori}.',
    DE: '{mese} in {citta}: {tmin}–{tmax}° und {mm} mm Regen. Die beste Zeit ist {migliori}.',
    RU: '{mese} в {citta}: {tmin}–{tmax}° и {mm} мм осадков. Лучший период: {migliori}.',
    ZH: '{citta} 的 {mese}：{tmin}–{tmax}°，降雨 {mm} 毫米。最佳时间为 {migliori}。',
  },
  mp_clima_sez_tendenza: { IT: 'Ultimi anni rispetto alla media', EN: 'Recent years vs the average', FR: 'Dernières années vs la moyenne', ES: 'Últimos años frente a la media', DE: 'Letzte Jahre gegenüber dem Mittel', RU: 'Последние годы против нормы', ZH: '近年与平均值对比' },
  mp_clima_tendenza_media: { IT: 'in media', EN: 'on average', FR: 'en moyenne', ES: 'de media', DE: 'im Mittel', RU: 'в среднем', ZH: '平均' },
  mp_clima_tendenza_pioggia: { IT: 'pioggia', EN: 'rain', FR: 'pluie', ES: 'lluvia', DE: 'Regen', RU: 'осадки', ZH: '降雨' },
  // ── Modo Anno / Mese, mare, confronto, PDF, voce (24/09/2026) ──
  mp_clima_modo_anno: { IT: 'Anno', EN: 'Year', FR: 'Année', ES: 'Año', DE: 'Jahr', RU: 'Год', ZH: '全年' },
  mp_clima_modo_mese: { IT: 'Mese', EN: 'Month', FR: 'Mois', ES: 'Mes', DE: 'Monat', RU: 'Месяц', ZH: '月份' },
  mp_clima_classifica: { IT: '{n}° mese migliore su 12', EN: '#{n} best month of 12', FR: '{n}ᵉ meilleur mois sur 12', ES: '{n}.º mejor mes de 12', DE: '{n}. bester Monat von 12', RU: '{n}-й лучший месяц из 12', ZH: '12 个月中第 {n} 佳' },
  mp_clima_vs_prima: { IT: 'rispetto a {mese}', EN: 'compared with {mese}', FR: 'par rapport à {mese}', ES: 'respecto a {mese}', DE: 'gegenüber {mese}', RU: 'по сравнению с {mese}', ZH: '与 {mese} 相比' },
  mp_clima_report_mese: { IT: 'Scheda di {mese}', EN: '{mese} sheet', FR: 'Fiche de {mese}', ES: 'Ficha de {mese}', DE: 'Steckbrief {mese}', RU: 'Карточка: {mese}', ZH: '{mese} 详情' },
  mp_clima_sez_aspettarsi: { IT: 'Cosa aspettarsi', EN: 'What to expect', FR: 'À quoi s\'attendre', ES: 'Qué esperar', DE: 'Was zu erwarten ist', RU: 'Чего ожидать', ZH: '预期情况' },
  mp_clima_sez_eventi: { IT: 'Cosa succede in questo mese', EN: 'What happens this month', FR: 'Ce qui se passe ce mois-ci', ES: 'Qué pasa este mes', DE: 'Was in diesem Monat los ist', RU: 'Что происходит в этом месяце', ZH: '本月活动' },
  mp_clima_sez_alternativa: { IT: 'Se non è il mese giusto', EN: 'If it\'s not the right month', FR: 'Si ce n\'est pas le bon mois', ES: 'Si no es el mes adecuado', DE: 'Falls es nicht der richtige Monat ist', RU: 'Если месяц не подходит', ZH: '如果不是合适的月份' },
  mp_clima_sez_mare: { IT: 'Mesi per il bagno', EN: 'Months for swimming', FR: 'Mois pour la baignade', ES: 'Meses para el baño', DE: 'Monate zum Baden', RU: 'Месяцы для купания', ZH: '适合游泳的月份' },
  mp_clima_mare_acqua: { IT: 'acqua', EN: 'water', FR: 'eau', ES: 'agua', DE: 'Wasser', RU: 'вода', ZH: '水温' },
  mp_clima_mare_nessuno: { IT: 'Acqua sotto i 22° tutto l\'anno', EN: 'Water below 22° all year', FR: 'Eau sous 22° toute l\'année', ES: 'Agua por debajo de 22° todo el año', DE: 'Wasser ganzjährig unter 22°', RU: 'Вода ниже 22° весь год', ZH: '全年水温低于 22°' },
  mp_clima_confronta: { IT: 'Confronta con un\'altra città', EN: 'Compare with another city', FR: 'Comparer avec une autre ville', ES: 'Comparar con otra ciudad', DE: 'Mit einer anderen Stadt vergleichen', RU: 'Сравнить с другим городом', ZH: '与其他城市比较' },
  mp_clima_confronta_cerca: { IT: 'Scrivi una città…', EN: 'Type a city…', FR: 'Saisir une ville…', ES: 'Escribe una ciudad…', DE: 'Stadt eingeben…', RU: 'Введите город…', ZH: '输入城市…' },
  mp_clima_confronta_non_trovata: { IT: 'Città non trovata', EN: 'City not found', FR: 'Ville introuvable', ES: 'Ciudad no encontrada', DE: 'Stadt nicht gefunden', RU: 'Город не найден', ZH: '未找到城市' },
  mp_clima_pdf: { IT: 'PDF', EN: 'PDF', FR: 'PDF', ES: 'PDF', DE: 'PDF', RU: 'PDF', ZH: 'PDF' },
  mp_clima_ascolta: { IT: 'Ascolta', EN: 'Listen', FR: 'Écouter', ES: 'Escuchar', DE: 'Anhören', RU: 'Слушать', ZH: '收听' },
  mp_clima_pdf_non_riuscito: { IT: 'PDF non riuscito', EN: 'PDF failed', FR: 'PDF échoué', ES: 'PDF fallido', DE: 'PDF fehlgeschlagen', RU: 'PDF не создан', ZH: 'PDF 生成失败' },
  mp_clima_quando_andare: { IT: 'Quando andare', EN: 'When to go', FR: 'Quand partir', ES: 'Cuándo ir', DE: 'Wann reisen', RU: 'Когда ехать', ZH: '何时出发' },
  mp_clima_quando_andare_desc: { IT: 'Il periodo migliore, mese per mese, con statistiche e consigli dal web', EN: 'The best time, month by month, with statistics and tips from the web', FR: 'La meilleure période, mois par mois, avec statistiques et conseils du web', ES: 'La mejor época, mes a mes, con estadísticas y consejos de la web', DE: 'Die beste Zeit, Monat für Monat, mit Statistiken und Tipps aus dem Web', RU: 'Лучшее время, месяц за месяцем, со статистикой и советами из веба', ZH: '逐月最佳时间，含统计与网络建议' },
  mp_clima_vedi_scheda: { IT: 'Vedi la scheda di {mese}', EN: 'See the {mese} sheet', FR: 'Voir la fiche de {mese}', ES: 'Ver la ficha de {mese}', DE: 'Steckbrief {mese} ansehen', RU: 'Открыть карточку: {mese}', ZH: '查看 {mese} 详情' },
  // Riga clima sotto ogni giorno dell'itinerario e chip della libreria (24/09/2026)
  mp_clima_giorno_solito: { IT: 'Di solito a {mese}: {tmin}–{tmax}°, {mm} mm di pioggia nel mese', EN: 'Usually in {mese}: {tmin}–{tmax}°, {mm} mm of rain in the month', FR: 'En général en {mese} : {tmin}–{tmax}°, {mm} mm de pluie dans le mois', ES: 'Normalmente en {mese}: {tmin}–{tmax}°, {mm} mm de lluvia en el mes', DE: 'Üblicherweise im {mese}: {tmin}–{tmax}°, {mm} mm Regen im Monat', RU: 'Обычно в {mese}: {tmin}–{tmax}°, {mm} мм осадков за месяц', ZH: '{mese}通常：{tmin}–{tmax}°，当月降雨 {mm} 毫米' },
  mp_clima_consiglio_pioggia: { IT: 'Mese piovoso: tieni a portata le tappe al chiuso', EN: 'Rainy month: keep the indoor stops handy', FR: 'Mois pluvieux : gardez les étapes couvertes sous la main', ES: 'Mes lluvioso: ten a mano las paradas bajo techo', DE: 'Regnerischer Monat: Innenstationen bereithalten', RU: 'Дождливый месяц: держите под рукой крытые остановки', ZH: '多雨月份：备好室内景点' },
  mp_clima_consiglio_caldo: { IT: 'Ore calde 13–16: meglio al chiuso o all\'ombra', EN: 'Hot hours 1–4 pm: better indoors or in the shade', FR: 'Heures chaudes 13h–16h : mieux à l\'intérieur ou à l\'ombre', ES: 'Horas de calor 13–16: mejor bajo techo o a la sombra', DE: 'Heiße Stunden 13–16 Uhr: besser drinnen oder im Schatten', RU: 'Жаркие часы 13–16: лучше в помещении или в тени', ZH: '13–16 点最热：宜在室内或阴凉处' },
  mp_clima_consiglio_freddo: { IT: 'Freddo: vestiti a strati', EN: 'Cold: dress in layers', FR: 'Froid : habillez-vous en couches', ES: 'Frío: vístete por capas', DE: 'Kalt: im Zwiebellook anziehen', RU: 'Холодно: одевайтесь слоями', ZH: '寒冷：分层穿衣' },
  mp_clima_data_partenza: { IT: 'Data di partenza (facoltativa: per il meteo dei giorni)', EN: 'Departure date (optional: for the daily weather)', FR: 'Date de départ (facultative : pour la météo des jours)', ES: 'Fecha de salida (opcional: para el tiempo de cada día)', DE: 'Abreisedatum (optional: für das Wetter der Tage)', RU: 'Дата отъезда (необязательно: для погоды по дням)', ZH: '出发日期（可选：用于每日天气）' },
  mp_clima_giorno_previsione: { IT: 'Previsione {data}: {tmin}–{tmax}°, {mm} mm', EN: 'Forecast {data}: {tmin}–{tmax}°, {mm} mm', FR: 'Prévision {data} : {tmin}–{tmax}°, {mm} mm', ES: 'Previsión {data}: {tmin}–{tmax}°, {mm} mm', DE: 'Vorhersage {data}: {tmin}–{tmax}°, {mm} mm', RU: 'Прогноз {data}: {tmin}–{tmax}°, {mm} мм', ZH: '{data} 预报：{tmin}–{tmax}°，{mm} 毫米' },
  mp_clima_consiglio_pioggia_giorno: { IT: 'Pioggia prevista: tieni a portata le tappe al chiuso', EN: 'Rain forecast: keep the indoor stops handy', FR: 'Pluie prévue : gardez les étapes couvertes sous la main', ES: 'Lluvia prevista: ten a mano las paradas bajo techo', DE: 'Regen erwartet: Innenstationen bereithalten', RU: 'Ожидается дождь: держите под рукой крытые остановки', ZH: '预计有雨：备好室内景点' },
  mp_clima_periodo_migliore: { IT: 'Periodo migliore: {periodo}', EN: 'Best time: {periodo}', FR: 'Meilleure période : {periodo}', ES: 'Mejor época: {periodo}', DE: 'Beste Zeit: {periodo}', RU: 'Лучший период: {periodo}', ZH: '最佳时间：{periodo}' },
  mp_clima_sez_conclusioni: { IT: 'Conclusioni dell\'AI', EN: 'AI conclusions', FR: 'Conclusions de l\'IA', ES: 'Conclusiones de la IA', DE: 'Fazit der KI', RU: 'Выводы ИИ', ZH: 'AI 结论' },
  mp_clima_sez_fonti: { IT: 'Fonti', EN: 'Sources', FR: 'Sources', ES: 'Fuentes', DE: 'Quellen', RU: 'Источники', ZH: '来源' },
  mp_clima_fonte_affidabile: { IT: 'fonte affidabile', EN: 'reliable source', FR: 'source fiable', ES: 'fuente fiable', DE: 'verlässliche Quelle', RU: 'надёжный источник', ZH: '可靠来源' },
  mp_clima_fonte_blog: { IT: 'blog o sito, non verificato', EN: 'blog or site, unverified', FR: 'blog ou site, non vérifié', ES: 'blog o sitio, sin verificar', DE: 'Blog oder Website, ungeprüft', RU: 'блог или сайт, не проверено', ZH: '博客或网站，未经核实' },
  mp_clima_fonte_forum: { IT: 'forum o recensioni, opinioni personali', EN: 'forum or reviews, personal opinions', FR: 'forum ou avis, opinions personnelles', ES: 'foro o reseñas, opiniones personales', DE: 'Forum oder Bewertungen, persönliche Meinungen', RU: 'форум или отзывы, личные мнения', ZH: '论坛或评论，个人观点' },
  mp_clima_col_mese: { IT: 'Mese', EN: 'Month', FR: 'Mois', ES: 'Mes', DE: 'Monat', RU: 'Месяц', ZH: '月份' },
  mp_clima_col_temp: { IT: 'Min–max', EN: 'Min–max', FR: 'Min–max', ES: 'Mín–máx', DE: 'Min–max', RU: 'Мин–макс', ZH: '最低–最高' },
  mp_clima_col_pioggia: { IT: 'Pioggia', EN: 'Rain', FR: 'Pluie', ES: 'Lluvia', DE: 'Regen', RU: 'Осадки', ZH: '降雨' },
  mp_clima_col_sole: { IT: 'Sole', EN: 'Sun', FR: 'Soleil', ES: 'Sol', DE: 'Sonne', RU: 'Солнце', ZH: '日照' },
  mp_clima_col_umidita: { IT: 'Umidità', EN: 'Humidity', FR: 'Humidité', ES: 'Humedad', DE: 'Luftfeuchte', RU: 'Влажность', ZH: '湿度' },
  mp_clima_col_voto: { IT: 'Voto', EN: 'Score', FR: 'Note', ES: 'Nota', DE: 'Wert', RU: 'Оценка', ZH: '评分' },
  mp_clima_nessuna_pagina: {
    IT: 'Nessuna pagina web utile trovata per questa zona: il report si basa solo sulle statistiche.',
    EN: 'No useful web page found for this area: the report relies on statistics only.',
    FR: 'Aucune page web utile trouvée pour cette zone : le rapport repose uniquement sur les statistiques.',
    ES: 'No se encontró ninguna página web útil para esta zona: el informe se basa solo en estadísticas.',
    DE: 'Keine brauchbare Webseite für diese Gegend gefunden: der Bericht stützt sich nur auf Statistiken.',
    RU: 'Полезных веб-страниц для этой зоны не найдено: отчёт основан только на статистике.',
    ZH: '未找到该地区的有用网页：报告仅基于统计数据。',
  },
  mp_clima_ottimo: { IT: 'ottimo', EN: 'excellent', FR: 'excellent', ES: 'excelente', DE: 'sehr gut', RU: 'отлично', ZH: '极佳' },
  mp_clima_buono: { IT: 'buono', EN: 'good', FR: 'bon', ES: 'bueno', DE: 'gut', RU: 'хорошо', ZH: '良好' },
  mp_clima_discreto: { IT: 'discreto', EN: 'fair', FR: 'moyen', ES: 'regular', DE: 'mäßig', RU: 'средне', ZH: '一般' },
  mp_clima_scarso: { IT: 'scarso', EN: 'poor', FR: 'médiocre', ES: 'malo', DE: 'schlecht', RU: 'плохо', ZH: '较差' },
  mp_layer_balneazione_nome: {
    IT: 'Qualità acqua del mare', EN: 'Bathing water quality',
    FR: 'Qualité des eaux de baignade', ES: 'Calidad del agua de baño',
    DE: 'Badegewässerqualität', RU: 'Качество воды для купания', ZH: '海水浴场水质',
  },
  // ── Aree protette Natura 2000 (EEA) — 27/08/2026 ──
  mp_layer_natura2000_nome: {
    IT: 'Aree protette Natura 2000', EN: 'Natura 2000 protected areas',
    FR: 'Aires protégées Natura 2000', ES: 'Áreas protegidas Natura 2000',
    DE: 'Natura-2000-Schutzgebiete', RU: 'Охраняемые территории Natura 2000', ZH: 'Natura 2000 保护区',
  },
  mp_layer_natura2000_det: {
    IT: '~27.000 siti UE con confini (Agenzia Europea dell\'Ambiente)',
    EN: '~27,000 EU sites with boundaries (European Environment Agency)',
    FR: '~27 000 sites UE avec leurs limites (Agence européenne pour l\'environnement)',
    ES: '~27.000 sitios de la UE con sus límites (Agencia Europea de Medio Ambiente)',
    DE: '~27.000 EU-Gebiete mit Grenzen (Europäische Umweltagentur)',
    RU: '~27 000 участков ЕС с границами (Европейское агентство по окружающей среде)',
    ZH: '约 27,000 个欧盟保护区及其边界（欧洲环境署）',
  },
  // Turismo dello Shopping e Turismo di Lusso (06/09/2026): layer del
  // pannello ⓘ, stesso schema di Vino e Gusto — vedi CategoryChips.tsx.
  mp_layer_shopping_nome: {
    IT: 'Shopping', EN: 'Shopping', FR: 'Shopping', ES: 'Compras',
    DE: 'Shopping', RU: 'Шопинг', ZH: '购物',
  },
  mp_layer_shopping_det: {
    IT: 'vie e centri commerciali, grandi magazzini, outlet, souk',
    EN: 'shopping streets and malls, department stores, outlets, souks',
    FR: 'rues et centres commerciaux, grands magasins, outlets, souks',
    ES: 'calles y centros comerciales, grandes almacenes, outlets, zocos',
    DE: 'Einkaufsstraßen und -zentren, Kaufhäuser, Outlets, Basare',
    RU: 'торговые улицы и центры, универмаги, аутлеты, базары',
    ZH: '购物街与商场、百货商店、奥特莱斯、集市',
  },
  mp_layer_lusso_nome: {
    IT: 'Lusso', EN: 'Luxury', FR: 'Luxe', ES: 'Lujo',
    DE: 'Luxus', RU: 'Люкс', ZH: '奢华',
  },
  mp_layer_lusso_det: {
    IT: 'hotel 5 stelle, ristoranti stellati, marine, club esclusivi',
    EN: '5-star hotels, starred restaurants, marinas, exclusive clubs',
    FR: 'hôtels 5 étoiles, restaurants étoilés, marinas, clubs exclusifs',
    ES: 'hoteles 5 estrellas, restaurantes con estrellas, marinas, clubes exclusivos',
    DE: '5-Sterne-Hotels, Sternerestaurants, Yachthäfen, exklusive Clubs',
    RU: 'пятизвёздочные отели, рестораны со звёздами, марины, эксклюзивные клубы',
    ZH: '五星级酒店、米其林星级餐厅、游艇码头、尊享会所',
  },
  mp_n2k_habitat: {
    IT: 'Sito di importanza comunitaria (habitat)', EN: 'Habitats Directive site (SCI/SAC)',
    FR: 'Site d\'importance communautaire (habitats)', ES: 'Lugar de importancia comunitaria (hábitats)',
    DE: 'FFH-Gebiet (Lebensräume)', RU: 'Участок Директивы о местообитаниях', ZH: '栖息地指令保护区',
  },
  mp_n2k_uccelli: {
    IT: 'Zona di protezione speciale (uccelli)', EN: 'Special Protection Area (birds)',
    FR: 'Zone de protection spéciale (oiseaux)', ES: 'Zona de especial protección para las aves',
    DE: 'Vogelschutzgebiet', RU: 'Особая охраняемая зона (птицы)', ZH: '特别保护区（鸟类）',
  },
  mp_cdda_nazionale: {
    IT: 'Area protetta nazionale', EN: 'Nationally designated area', FR: 'Aire protégée nationale',
    ES: 'Área protegida nacional', DE: 'National ausgewiesenes Schutzgebiet', RU: 'Национальная охраняемая территория', ZH: '国家级保护区',
  },
  mp_n2k_scheda: {
    IT: 'Scheda ufficiale', EN: 'Official factsheet', FR: 'Fiche officielle', ES: 'Ficha oficial',
    DE: 'Offizielles Datenblatt', RU: 'Официальная карточка', ZH: '官方资料页',
  },
  mp_n2k_fonte: {
    IT: 'Fonte: Agenzia Europea dell\'Ambiente (CC BY 4.0) — rispetta i regolamenti del sito',
    EN: 'Source: European Environment Agency (CC BY 4.0) — respect the site rules',
    FR: 'Source : Agence européenne pour l\'environnement (CC BY 4.0) — respectez la réglementation du site',
    ES: 'Fuente: Agencia Europea de Medio Ambiente (CC BY 4.0) — respeta las normas del lugar',
    DE: 'Quelle: Europäische Umweltagentur (CC BY 4.0) — beachte die Schutzgebietsregeln',
    RU: 'Источник: Европейское агентство по окружающей среде (CC BY 4.0) — соблюдайте правила территории',
    ZH: '来源：欧洲环境署（CC BY 4.0）——请遵守保护区规定',
  },
  mp_natura2000_disclaimer: {
    IT: 'Confini ufficiali della rete Natura 2000 (EEA). Solo Europa; avvicina la mappa per vederli.',
    EN: 'Official Natura 2000 network boundaries (EEA). Europe only; zoom in to see them.',
    FR: 'Limites officielles du réseau Natura 2000 (AEE). Europe uniquement ; zoomez pour les voir.',
    ES: 'Límites oficiales de la red Natura 2000 (AEMA). Solo Europa; acerca el mapa para verlos.',
    DE: 'Offizielle Grenzen des Natura-2000-Netzes (EUA). Nur Europa; zum Anzeigen hineinzoomen.',
    RU: 'Официальные границы сети Natura 2000 (ЕАОС). Только Европа; приблизьте карту.',
    ZH: 'Natura 2000 网络官方边界（EEA）。仅限欧洲；请放大地图查看。',
  },
  // ── Scheda POI: denominazioni d'origine e link ai registri esterni — 27/08/2026 ──
  poi_denominazioni_zona: {
    IT: 'Denominazioni della zona', EN: 'Designations of origin in the area', FR: 'Appellations de la zone',
    ES: 'Denominaciones de la zona', DE: 'Herkunftsbezeichnungen der Gegend', RU: 'Наименования происхождения этой зоны', ZH: '该地区的原产地名称',
  },
  poi_denominazioni_nota: {
    IT: 'Registro UE eAmbrosia (CC BY 4.0). Aggancio per zona, non certificazione del produttore.',
    EN: 'EU eAmbrosia register (CC BY 4.0). Matched by area, not a producer certification.',
    FR: 'Registre UE eAmbrosia (CC BY 4.0). Rattachement par zone, pas une certification du producteur.',
    ES: 'Registro UE eAmbrosia (CC BY 4.0). Vinculado por zona, no es una certificación del productor.',
    DE: 'EU-Register eAmbrosia (CC BY 4.0). Zuordnung nach Gebiet, keine Zertifizierung des Erzeugers.',
    RU: 'Реестр ЕС eAmbrosia (CC BY 4.0). Привязка по зоне, не сертификация производителя.',
    ZH: '欧盟 eAmbrosia 登记册（CC BY 4.0）。按地区匹配，并非生产者认证。',
  },
  mp_denominazione_area: {
    IT: 'Zona di denominazione', EN: 'Designation area', FR: 'Zone d\'appellation', ES: 'Zona de denominación',
    DE: 'Herkunftsgebiet', RU: 'Зона наименования происхождения', ZH: '原产地名称区域',
  },
  mp_area_ufficiale: {
    IT: 'confine ufficiale', EN: 'official boundary', FR: 'limite officielle', ES: 'límite oficial',
    DE: 'amtliche Grenze', RU: 'официальная граница', ZH: '官方边界',
  },
  mp_area_indicativa: {
    IT: 'area indicativa (confini dei comuni), non il disciplinare', EN: 'indicative area (municipal boundaries), not the specification',
    FR: 'zone indicative (limites communales), pas le cahier des charges', ES: 'zona indicativa (límites municipales), no el pliego de condiciones',
    DE: 'ungefähres Gebiet (Gemeindegrenzen), nicht die Produktspezifikation', RU: 'ориентировочная зона (границы муниципалитетов), не спецификация', ZH: '示意区域（市镇边界），并非产品规范',
  },
  poi_prenota_su: {
    IT: 'Biglietti e visite su', EN: 'Tickets and tours on', FR: 'Billets et visites sur', ES: 'Entradas y visitas en',
    DE: 'Tickets und Touren auf', RU: 'Билеты и экскурсии на', ZH: '门票与游览：',
  },
  poi_scheda_rcdb: {
    IT: 'Scheda su RCDB', EN: 'RCDB entry', FR: 'Fiche RCDB', ES: 'Ficha en RCDB', DE: 'RCDB-Eintrag', RU: 'Карточка RCDB', ZH: 'RCDB 资料页',
  },
  poi_scheda_wwd: {
    IT: 'Scheda su World Waterfall Database', EN: 'World Waterfall Database entry', FR: 'Fiche World Waterfall Database',
    ES: 'Ficha en World Waterfall Database', DE: 'Eintrag in der World Waterfall Database', RU: 'Карточка World Waterfall Database', ZH: 'World Waterfall Database 资料页',
  },
  // ── Pericolo valanghe (avalanche.report, Euregio) — 27/08/2026 ──
  mp_valanghe: {
    IT: 'Pericolo valanghe', EN: 'Avalanche danger', FR: 'Risque d\'avalanche', ES: 'Peligro de aludes',
    DE: 'Lawinengefahr', RU: 'Лавинная опасность', ZH: '雪崩危险',
  },
  mp_valanghe_0: {
    IT: 'nessuna neve', EN: 'no snow', FR: 'pas de neige', ES: 'sin nieve', DE: 'kein Schnee', RU: 'нет снега', ZH: '无雪',
  },
  mp_valanghe_1: {
    IT: 'debole', EN: 'low', FR: 'faible', ES: 'débil', DE: 'gering', RU: 'низкая', ZH: '低',
  },
  mp_valanghe_2: {
    IT: 'moderato', EN: 'moderate', FR: 'limité', ES: 'limitado', DE: 'mäßig', RU: 'умеренная', ZH: '中等',
  },
  mp_valanghe_3: {
    IT: 'marcato', EN: 'considerable', FR: 'marqué', ES: 'notable', DE: 'erheblich', RU: 'значительная', ZH: '较高',
  },
  mp_valanghe_4: {
    IT: 'forte', EN: 'high', FR: 'fort', ES: 'fuerte', DE: 'groß', RU: 'высокая', ZH: '高',
  },
  mp_valanghe_5: {
    IT: 'molto forte', EN: 'very high', FR: 'très fort', ES: 'muy fuerte', DE: 'sehr groß', RU: 'очень высокая', ZH: '极高',
  },
  mp_valanghe_fuori_stagione: {
    IT: 'ultimo bollettino della stagione, non aggiornato', EN: 'last bulletin of the season, not current',
    FR: 'dernier bulletin de la saison, non actualisé', ES: 'último boletín de la temporada, no actualizado',
    DE: 'letztes Bulletin der Saison, nicht aktuell', RU: 'последний бюллетень сезона, не обновлён', ZH: '本季最后一期公报，非最新',
  },
  mp_valanghe_fonte: {
    IT: 'avalanche.report (Euregio, CC BY 4.0)', EN: 'avalanche.report (Euregio, CC BY 4.0)',
    FR: 'avalanche.report (Euregio, CC BY 4.0)', ES: 'avalanche.report (Euregio, CC BY 4.0)',
    DE: 'lawinen.report (Euregio, CC BY 4.0)', RU: 'avalanche.report (Euregio, CC BY 4.0)', ZH: 'avalanche.report（Euregio，CC BY 4.0）',
  },

  // ── Carta del sole ──
  mp_uv_basso: {
    IT: 'Basso', EN: 'Low', FR: 'Faible', ES: 'Bajo',
    DE: 'Niedrig', RU: 'Низкий', ZH: '低',
  },
  mp_uv_moderato: {
    IT: 'Moderato', EN: 'Moderate', FR: 'Modéré', ES: 'Moderado',
    DE: 'Mäßig', RU: 'Умеренный', ZH: '中等',
  },
  mp_uv_alto: {
    IT: 'Alto', EN: 'High', FR: 'Élevé', ES: 'Alto',
    DE: 'Hoch', RU: 'Высокий', ZH: '高',
  },
  mp_uv_molto_alto: {
    IT: 'Molto alto', EN: 'Very high', FR: 'Très élevé', ES: 'Muy alto',
    DE: 'Sehr hoch', RU: 'Очень высокий', ZH: '很高',
  },
  mp_uv_estremo: {
    IT: 'Estremo', EN: 'Extreme', FR: 'Extrême', ES: 'Extremo',
    DE: 'Extrem', RU: 'Экстремальный', ZH: '极高',
  },
  mp_percepiti: {
    IT: 'percepiti', EN: 'feels like', FR: 'ressenti', ES: 'sensación de',
    DE: 'gefühlt', RU: 'ощущается', ZH: '体感',
  },
  mp_reali: {
    IT: 'reali', EN: 'actual', FR: 'réels', ES: 'reales',
    DE: 'tatsächlich', RU: 'фактически', ZH: '实际',
  },
  mp_sole_forte: {
    IT: 'Sole forte', EN: 'Strong sun', FR: 'Soleil fort', ES: 'Sol fuerte',
    DE: 'Starke Sonne', RU: 'Сильное солнце', ZH: '烈日时段',
  },
  mp_sole_sempre_alto: {
    IT: 'Sole sempre sopra l’orizzonte', EN: 'Sun never sets',
    FR: 'Le soleil ne se couche pas', ES: 'El sol no se pone',
    DE: 'Die Sonne geht nicht unter', RU: 'Солнце не заходит за горизонт',
    ZH: '太阳整日不落',
  },
  mp_ora_locale_di: {
    IT: 'ora locale di', EN: 'local time,', FR: 'heure locale de',
    ES: 'hora local de', DE: 'Ortszeit', RU: 'местное время:', ZH: '当地时间：',
  },
  mp_ora_oro: {
    IT: 'Ora d’oro dalle', EN: 'Golden hour from', FR: 'Heure dorée à partir de',
    ES: 'Hora dorada desde las', DE: 'Goldene Stunde ab',
    RU: 'Золотой час с', ZH: '黄金时刻始于',
  },

  // ── Ricerca ──
  mp_ricerca_in_corso: {
    IT: 'Ricerca in corso…', EN: 'Searching…', FR: 'Recherche en cours…',
    ES: 'Buscando…', DE: 'Suche läuft…', RU: 'Идёт поиск…', ZH: '搜索中…',
  },
  mp_nessun_risultato: {
    IT: 'Nessun risultato per "{q}"', EN: 'No results for "{q}"',
    FR: 'Aucun résultat pour « {q} »', ES: 'Sin resultados para "{q}"',
    DE: 'Keine Treffer für "{q}"', RU: 'Ничего не найдено по запросу "{q}"',
    ZH: '未找到与“{q}”相关的结果',
  },
  mp_accendi_categoria: {
    IT: 'Accendi la categoria sulla mappa', EN: 'Turn the category on',
    FR: 'Activer la catégorie sur la carte', ES: 'Enciende la categoría en el mapa',
    DE: 'Kategorie auf der Karte einschalten', RU: 'Включить категорию на карте',
    ZH: '在地图上开启该类别',
  },
  mp_percorso: {
    IT: 'Percorso', EN: 'Route', FR: 'Itinéraire', ES: 'Ruta',
    DE: 'Route', RU: 'Маршрут', ZH: '路线',
  },
};
